### ISSUE TITLE
Test Error while trying to compile tag 1.4.1

### ISSUE THREAD

**Issue by saggarsunil** [snowflakedb/snowflake-kafka-connector#186]
We are trying to add some local changes to the connector release version 1.4.1. The local build test cases are failing with the following error. Is there anything which i am missing ?

```
[SF_KAFKA_CONNECTOR] Invalid snowflake.topic2table.map config format: jfsja,,
[ERROR] Tests run: 12, Failures: 9, Errors: 1, Skipped: 0, Time elapsed: 0.039 s <<< FAILURE! - in com.snowflake.kafka.connector.ConnectorTest
[ERROR] testValidateErrorPassphraseConfig(com.snowflake.kafka.connector.ConnectorTest)  Time elapsed: 0.008 s  <<< ERROR!
java.lang.RuntimeException: java.io.FileNotFoundException: profile.json (No such file or directory)
	at com.snowflake.kafka.connector.ConnectorTest.getCorrectConfig(ConnectorTest.java:104)
	at com.snowflake.kafka.connector.ConnectorTest.testValidateErrorPassphraseConfig(ConnectorTest.java:216)
Caused by: java.io.FileNotFoundException: profile.json (No such file or directory)
	at com.snowflake.kafka.connector.ConnectorTest.getCorrectConfig(ConnectorTest.java:104)
	at com.snowflake.kafka.connector.ConnectorTest.testValidateErrorPassphraseConfig(ConnectorTest.java:216)


```

```
ERROR] Failures: 
[ERROR]   ConnectorTest.testValidateCorrectConfig:140->assertPropHasError:49
[ERROR]   ConnectorTest.testValidateEmptyPasswordConfig:197->assertPropHasError:49
[ERROR]   ConnectorTest.testValidateErrorDatabaseConfig:231->assertPropHasError:49
[ERROR]   ConnectorTest.testValidateErrorPasswordConfig:186->assertPropHasError:49
[ERROR]   ConnectorTest.testValidateErrorSchemaConfig:242->assertPropHasError:49
[ERROR]   ConnectorTest.testValidateErrorURLAccountConfig:160->assertPropHasError:46
[ERROR]   ConnectorTest.testValidateErrorURLFormatConfig:149->assertPropHasError:46
[ERROR]   ConnectorTest.testValidateErrorUserConfig:173->assertPropHasError:49
[ERROR]   ConnectorTest.testValidateNullPasswordConfig:208->assertPropHasError:49
[ERROR] Errors: 
[ERROR]   ConnectorTest.testValidateErrorPassphraseConfig:216->getCorrectConfig:104 » Runtime
[ERROR]   SecurityTest.testRSAPasswordOutput:27 » NullPointer
[ERROR]   FIPSTest.testFips:23 » NullPointer
[ERROR]   InternalUtilsTest.testCreateProperties:89 » NullPointer
[ERROR]   InternalUtilsTest.testPrivateKey:24 » NullPointer
[INFO] 
[ERROR] Tests run: 78, Failures: 9, Errors: 5, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

```

Build went fine if we skip tests.

**Comment by sfc-gh-zli** [comment]
You need a profile.json that contains snowflake user name / private key to run test.
