### ISSUE TITLE
Complex Json Schemas break Connector

### ISSUE THREAD

**Issue by dschnied** [snowflakedb/snowflake-kafka-connector#207]
boolean objectMode;
          if (schema == null) {
            objectMode = true;
            for (Map.Entry<?, ?> entry : map.entrySet()) {
              if (!(entry.getKey() instanceof String)) {
                objectMode = false;
                break;
              }
            }
          } else {
            objectMode = schema.keySchema().type() == Schema.Type.STRING;
          }

schema.keySchema() will always return NULL, which is why the else clause will always fail. This code is executed for Json schemas which include a Java Map during parsing in convertToJson within RecordService

**Comment by sfc-gh-zli** [comment]
Which version are you using? And please provide a sample JSON so that we can reproduce this.

**Comment by dschnied** [comment]
I used version 1.4.1. Regarding the Json structure I need to generate a minimal example first. However, the error here seems clear to me:

schema.keySchema() will return NULL, see class SnowflakeJsonSchema: 
  @Override
  public Schema keySchema()
  {
    return null;
  }

Therefore, any execution of the else case above will fail with a nullpointer exception (which is what I was seeing).
However, the code within the else case seems to be planned as a more elegant version of the code in the if case: Determining wether all keys are of type string. I was able to fix the issue by simply removing the if/else and only executing the code within the if case.

I will try to provide a minimal Json that reproduces the issue.

**Comment by sfc-gh-zli** [comment]
If you are using snowflake JSON/AVRO converters, the conversion happens here https://github.com/snowflakedb/snowflake-kafka-connector/blob/master/src/main/java/com/snowflake/kafka/connector/records/SnowflakeAvroConverter.java#L175 .

**Comment by dschnied** [comment]
A closer investigation reveals that in fact the Json message is not the problem. The key is a simple string and converted as such, however there is also a header that gets send with the message that has a Json format. I suspect this to be the culprit here, I will try to verify this.

How and where is the header converted by the Snowflake connector? As I see them in the RECORD_METADATA column, I assume they are parsed somehow.

**Comment by sfc-gh-zli** [comment]
https://github.com/snowflakedb/snowflake-kafka-connector/blob/master/src/main/java/com/snowflake/kafka/connector/records/RecordService.java#L205

**Comment by dschnied** [comment]
A minimal example Test was conducted. Here the details:

Prerequisites: 

Free confluent platform 5.5.0 
Snowflake Kafka Connector 1.4.2 

Test description: 

1. Launch Zookeeper with default properties. 
2. Launch Kafka Server. 
3. Create topic “test” with 3 partitions and replication-factor 1. 
4. Launch a standalone Kafka connector.
5. Send json data {"parameter1":"my_value","parameter2":"123456789"} with the header [('header1','value1'),('header2','value2')]. 
6. Send json data {"parameter1":"my_value","parameter2":"123456789"} with the header [('header1','value1'),('header2','{}')] 

Results: 

1. Zookeeper started successfully. 
2. Kafka Server started successfully. 
3. Topic created successfully. 
4. A Kafka standalone connector started.  
5. The data is received in Snowflake successfully:

 
RECORD_METADATA:  
{ 
  "CreateTime": 1598433590561, 
  "headers": { 
    "header1": "value1", 
    "header2": "value2" 
  }, 
  "key": "my_key", 
  "offset": 4, 
  "partition": 0, 
  "topic": "test" 
} 

RECORD_CONTENT: 
{ 
  "parameter1": "my_value", 
  "parameter2": "123456789" 
} 

6. The connector crashes with: 
[SF_KAFKA_CONNECTOR] SnowflakeSinkTask[ID:0]:put 1 records (com.snowflake.kafka.connector.SnowflakeSinkTask:205) 
[2020-08-26 09:25:53,200] ERROR WorkerSinkTask{id=snowflakeConnect-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. Error: null (org.apache.kafka.connect.runtime.WorkerSinkTask:566) 
java.lang.NullPointerException 
        at com.snowflake.kafka.connector.records.RecordService.convertToJson(RecordService.java:302) 
        at com.snowflake.kafka.connector.records.RecordService.parseHeaders(RecordService.java:199) 
        at com.snowflake.kafka.connector.records.RecordService.processRecord(RecordService.java:138) 
        at com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1$ServiceContext$PartitionBuffer.insert(SnowflakeSinkServiceV1.java:882) 
        at com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1$ServiceContext$PartitionBuffer.access$400(SnowflakeSinkServiceV1.java:843) 
        at com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1$ServiceContext.insert(SnowflakeSinkServiceV1.java:435) 
        at com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1$ServiceContext.access$100(SnowflakeSinkServiceV1.java:241) 
        at com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1.insert(SnowflakeSinkServiceV1.java:90) 
        at java.util.ArrayList.forEach(ArrayList.java:1259) 
        at com.snowflake.kafka.connector.SnowflakeSinkTask.put(SnowflakeSinkTask.java:208) 
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:546) 
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:326) 
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:228) 
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:196) 
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:184) 
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 
        at java.lang.Thread.run(Thread.java:748)

**Comment by sfc-gh-zli** [comment]
Can you try using simple header converter in your Snowflake Kafka Connector's configuration? Also could you please test with newer versions like 1.4.3 or 1.4.4?

**Comment by sfc-gh-zli** [comment]
Fixed in this PR: https://github.com/snowflakedb/snowflake-kafka-connector/pull/224
