### ISSUE TITLE
Deadlock when initializing converters

### ISSUE THREAD

**Issue by ivanyu** [snowflakedb/snowflake-kafka-connector#23]
Hi,

We have the following issue with the connector. Two instances of the connector defined, one uses `SnowflakeAvroConverter` as `value.converter`, another, `SnowflakeJsonConverter`. When Kafka Connect initializes everything, it deadlocks in a way like this

```
Found one Java-level deadlock:
=============================
"pool-14-thread-6":
  waiting to lock monitor 0x00007f2d980339c8 (object 0x00000000d100e920, a org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader),
  which is held by "pool-14-thread-5"
"pool-14-thread-5":
  waiting to lock monitor 0x00007f2d98032b58 (object 0x00000000d2b03558, a org.apache.kafka.connect.runtime.isolation.PluginClassLoader),
  which is held by "pool-14-thread-1"
"pool-14-thread-1":
  waiting to lock monitor 0x00007f2d980339c8 (object 0x00000000d100e920, a org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader),
  which is held by "pool-14-thread-5"

Java stack information for the threads listed above:
===================================================
"pool-14-thread-6":
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:709)
	at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:471)
	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:464)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:62)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:75)
	at org.apache.kafka.connect.runtime.ConnectorConfig.<init>(ConnectorConfig.java:205)
	at org.apache.kafka.connect.runtime.ConnectorConfig.<init>(ConnectorConfig.java:201)
	at org.apache.kafka.connect.runtime.Worker.startTask(Worker.java:405)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startTask(DistributedHerder.java:865)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1600(DistributedHerder.java:110)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$13.call(DistributedHerder.java:880)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$13.call(DistributedHerder.java:876)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
"pool-14-thread-5":
	at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:91)
	- waiting to lock <0x00000000d2b03558> (a org.apache.kafka.connect.runtime.isolation.PluginClassLoader)
	at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.loadClass(DelegatingClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:709)
	at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:471)
	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:464)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:62)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:75)
	at org.apache.kafka.connect.runtime.ConnectorConfig.<init>(ConnectorConfig.java:205)
	at org.apache.kafka.connect.runtime.ConnectorConfig.<init>(ConnectorConfig.java:201)
	at org.apache.kafka.connect.runtime.Worker.startTask(Worker.java:405)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startTask(DistributedHerder.java:865)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1600(DistributedHerder.java:110)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$13.call(DistributedHerder.java:880)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$13.call(DistributedHerder.java:876)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
"pool-14-thread-1":
	at java.lang.ClassLoader.loadClass(ClassLoader.java:404)
	- waiting to lock <0x00000000d100e920> (a org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
	at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.loadClass(DelegatingClassLoader.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	- locked <0x00000000d045eed8> (a java.lang.Object)
	at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:104)
	- locked <0x00000000d045eed8> (a java.lang.Object)
	- locked <0x00000000d2b03558> (a org.apache.kafka.connect.runtime.isolation.PluginClassLoader)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:96)
	- locked <0x00000000d045ef20> (a java.lang.Object)
	- locked <0x00000000d2b03558> (a org.apache.kafka.connect.runtime.isolation.PluginClassLoader)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.snowflake.kafka.connector.records.SnowflakeConverter.<clinit>(SnowflakeConverter.java:39)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:709)
	at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:471)
	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:464)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:62)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:75)
	at org.apache.kafka.connect.runtime.ConnectorConfig.<init>(ConnectorConfig.java:205)
	at org.apache.kafka.connect.runtime.ConnectorConfig.<init>(ConnectorConfig.java:201)
	at org.apache.kafka.connect.runtime.Worker.startConnector(Worker.java:234)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startConnector(DistributedHerder.java:908)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1300(DistributedHerder.java:110)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$15.call(DistributedHerder.java:924)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$15.call(DistributedHerder.java:920)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I managed to boil it down to the following reproducing code:

```java
package org.apache.kafka.connect.runtime;

import java.util.HashMap;
import java.util.Map;

import org.apache.kafka.connect.runtime.isolation.Plugins;

import static org.apache.kafka.connect.runtime.WorkerConfig.PLUGIN_PATH_CONFIG;

public class Xxxxxx {
    public static void main(String[] args) throws InterruptedException {
        Map<String, String> props = new HashMap<>();
        props.put(PLUGIN_PATH_CONFIG, "<path>");
        Plugins plugins = new Plugins(props);
        plugins.compareAndSwapWithDelegatingLoader();

        Thread1 t1 = new Thread1(plugins);
        Thread2 t2 = new Thread2(plugins);

        t1.start();
        t2.start();

        t1.join();
        t2.join();
    }

    private static class Thread1 extends Thread {
        private final Plugins plugins;

        private Thread1(final Plugins plugins) {
            super("Thread-1");
            this.plugins = plugins;
        }

        @Override
        public void run() {
            try {
                Thread.sleep(50);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            Map<String, String> props = new HashMap<>();
            props.put("name", "snowflake_avro");
            props.put("connector.class", "com.snowflake.kafka.connector.SnowflakeSinkConnector");
            props.put("value.converter", "com.snowflake.kafka.connector.records.SnowflakeAvroConverter");
            ConnectorConfig connectorConfig = new ConnectorConfig(plugins, props);
        }
    }

    private static class Thread2 extends Thread {
        private final Plugins plugins;

        private Thread2(final Plugins plugins) {
            super("Thread-2");
            this.plugins = plugins;
        }

        @Override
        public void run() {
            Map<String, String> props = new HashMap<>();
            props.put("name", "snowflake_json");
            props.put("connector.class", "com.snowflake.kafka.connector.SnowflakeSinkConnector");
            props.put("value.converter", "com.snowflake.kafka.connector.records.SnowflakeJsonConverter");
            ConnectorConfig connectorConfig = new ConnectorConfig(plugins, props);
        }
    }
}
```
(reproduces in ~40% of runs).

I'm not absolutely sure now, but this may be caused by https://issues.apache.org/jira/browse/KAFKA-7421. This issue may be fixed at some point, but who knows when and if it will be backported.

I propose to address this with https://github.com/snowflakedb/snowflake-kafka-connector/pull/24. The idea is very simple: delay `ObjectMapper` initialization to object creation by making it non-static. It's not far (in real time) from the class loading, but it's enought to break the lock. The change is very small in introduces close to 0 overhead.

**Comment by binglihub** [comment]
Thank you for your help. Merged your change.
