### ISSUE TITLE
SnowflakeKafkaConnectorException "Class  could not be found." using snowflake-kafka-connector:1.5.0 with confluentinc/cp-kafka-connect:6.0.0

### ISSUE THREAD

**Issue by rvertigo** [snowflakedb/snowflake-kafka-connector#234]
Updated to latest Snowflake Connector `snowflake-kafka-connector:1.5.0` and latest Confluent Kafka Connect `confluentinc/cp-kafka-connect:6.0.0`, which resulted in this error:
```
com.snowflake.kafka.connector.internal.SnowflakeKafkaConnectorException: 
[SF_KAFKA_CONNECTOR] Exception: Failed to connect schema registry service
[SF_KAFKA_CONNECTOR] Error Code: 0012
[SF_KAFKA_CONNECTOR] Detail: Schema registry service is not available
[SF_KAFKA_CONNECTOR] Message: Invalid value  for configuration schema.registry.ssl.engine.factory.class: Class  could not be found.
[SF_KAFKA_CONNECTOR] io.confluent.common.config.ConfigDef.parseType(ConfigDef.java:392)
[SF_KAFKA_CONNECTOR] io.confluent.common.config.ConfigDef.define(ConfigDef.java:110)
[SF_KAFKA_CONNECTOR] io.confluent.common.config.ConfigDef.define(ConfigDef.java:154)
[SF_KAFKA_CONNECTOR] io.confluent.kafka.schemaregistry.client.SchemaRegistryClientConfig.withClientSslSupport(SchemaRegistryClientConfig.java:44)
[SF_KAFKA_CONNECTOR] io.confluent.kafka.serializers.AbstractKafkaAvroSerDeConfig.baseConfigDef(AbstractKafkaAvroSerDeConfig.java:155)
[SF_KAFKA_CONNECTOR] com.snowflake.kafka.connector.records.AvroConverterConfig.<init>(AvroConverterConfig.java:27)
[SF_KAFKA_CONNECTOR] com.snowflake.kafka.connector.records.SnowflakeAvroConverter.configure(SnowflakeAvroConverter.java:56)
[SF_KAFKA_CONNECTOR] org.apache.kafka.connect.runtime.isolation.Plugins.newConverter(Plugins.java:298)
[SF_KAFKA_CONNECTOR] org.apache.kafka.connect.runtime.Worker.startTask(Worker.java:532)
[SF_KAFKA_CONNECTOR] org.apache.kafka.connect.runtime.distributed.DistributedHerder.startTask(DistributedHerder.java:1251)
[SF_KAFKA_CONNECTOR] org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1700(DistributedHerder.java:127)
[SF_KAFKA_CONNECTOR] org.apache.kafka.connect.runtime.distributed.DistributedHerder$10.call(DistributedHerder.java:1266)
[SF_KAFKA_CONNECTOR] org.apache.kafka.connect.runtime.distributed.DistributedHerder$10.call(DistributedHerder.java:1262)
[SF_KAFKA_CONNECTOR] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[SF_KAFKA_CONNECTOR] java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[SF_KAFKA_CONNECTOR] java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[SF_KAFKA_CONNECTOR] java.base/java.lang.Thread.run(Thread.java:834)
    at com.snowflake.kafka.connector.internal.SnowflakeErrors.getException(SnowflakeErrors.java:427)
    at com.snowflake.kafka.connector.internal.SnowflakeErrors.getException(SnowflakeErrors.java:403)
    at com.snowflake.kafka.connector.internal.SnowflakeErrors.getException(SnowflakeErrors.java:390)
    at com.snowflake.kafka.connector.records.SnowflakeAvroConverter.configure(SnowflakeAvroConverter.java:65)
    at org.apache.kafka.connect.runtime.isolation.Plugins.newConverter(Plugins.java:298)
    at org.apache.kafka.connect.runtime.Worker.startTask(Worker.java:532)
    at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startTask(DistributedHerder.java:1251)
    at org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1700(DistributedHerder.java:127)
    at org.apache.kafka.connect.runtime.distributed.DistributedHerder$10.call(DistributedHerder.java:1266)
    at org.apache.kafka.connect.runtime.distributed.DistributedHerder$10.call(DistributedHerder.java:1262)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)

```

Assuming this is a Snowflake Connector issue and not a Confluent Kafka Connect issue only because all other Connectors are working after the upgrade.

**Comment by sfc-gh-zli** [comment]
Can you provide configs/steps for me to reproduce this problem? I cannot reproduce this on my end.

**Comment by rvertigo** [comment]
There is a similar error in issue [221](https://github.com/snowflakedb/snowflake-kafka-connector/issues/221) as well.

These connectors were functional in `confluentinc/cp-kafka-connect:5.5.1` with `snowflakeinc/snowflake-kafka-connector:1.4.3`
Upgraded Confluent Kafka Connect (et al) to 6.0.0. and Snowflake connector to 1.5.0.

We had several functional connectors. Here is a sample of one:
```
{
  "value.converter.schema.registry.url": "http://schemaregistry.company.com/",
  "consumer.override.auto.offset.reset": "earliest",
  "name": "event-some-data-snowflake-sink",
  "connector.class": "com.snowflake.kafka.connector.SnowflakeSinkConnector",
  "tasks.max": "1",
  "key.converter": "org.apache.kafka.connect.storage.StringConverter",
  "value.converter": "com.snowflake.kafka.connector.records.SnowflakeAvroConverter",
  "errors.tolerance": "all",
  "errors.log.enable": "true",
  "errors.log.include.messages": "true",
  "topics": [
    "event-some-data"
  ],
  "errors.deadletterqueue.topic.name": "event-some-data-snowflake-dlt",
  "errors.deadletterqueue.topic.replication.factor": "3",
  "errors.deadletterqueue.context.headers.enable": "true",
  "snowflake.url.name": "https://*******.snowflakecomputing.com/",
  "snowflake.user.name": "SNOWFLAKE_CONNECTOR",
  "snowflake.private.key": "*******",
  "snowflake.database.name": "some",
  "snowflake.schema.name": "data",
  "snowflake.topic2table.map": "event-some-data:event_some_data_connector",
  "buffer.flush.time": "10"
}
```

Dockerfile:
```
FROM confluentinc/cp-kafka-connect:6.0.0

ENV QA_PLUGIN_PATH=/usr/share/confluent-hub-components-qa

ENV KAFKA_JMX_OPTS="-Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"
ENV JMX_JAVAAGENT_CONF=/etc/jmx_prometheus_javaagent/jmx_exporter_config.yml
ENV JMX_JAVAAGENT_JAR=/opt/jmx_prometheus_javaagent/jmx_prometheus_javaagent.jar
ENV JMX_JAVAAGENT_PORT=8081
ENV KAFKA_JMX_OPTS="${KAFKA_JMX_OPTS} -javaagent:${JMX_JAVAAGENT_JAR}=${JMX_JAVAAGENT_PORT}:${JMX_JAVAAGENT_CONF}"
ENV JMX_JAVAAGENT_VERSION=0.14.0

COPY jmx_exporter_config.yml ${JMX_JAVAAGENT_CONF}

ADD https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/${JMX_JAVAAGENT_VERSION}/jmx_prometheus_javaagent-${JMX_JAVAAGENT_VERSION}.jar ${JMX_JAVAAGENT_JAR}

USER root
RUN mkdir -m 0775 -p ${QA_PLUGIN_PATH}; \
    chown appuser:appuser ${QA_PLUGIN_PATH}; \
    chmod a+r ${JMX_JAVAAGENT_JAR};
USER appuser

RUN confluent-hub install confluentinc/connect-transforms:latest           --no-prompt; \
    confluent-hub install confluentinc/kafka-connect-aws-dynamodb:latest   --no-prompt --component-dir ${QA_PLUGIN_PATH}; \
    confluent-hub install confluentinc/kafka-connect-aws-lambda:latest     --no-prompt --component-dir ${QA_PLUGIN_PATH}; \
    confluent-hub install confluentinc/kafka-connect-datagen:latest        --no-prompt --component-dir ${QA_PLUGIN_PATH}; \
    confluent-hub install confluentinc/kafka-connect-elasticsearch:latest  --no-prompt; \
    confluent-hub install confluentinc/kafka-connect-http:latest           --no-prompt; \
    confluent-hub install confluentinc/kafka-connect-jdbc:latest           --no-prompt; \
    confluent-hub install confluentinc/kafka-connect-s3:latest             --no-prompt; \
    confluent-hub install confluentinc/kafka-connect-s3-source:latest      --no-prompt --component-dir ${QA_PLUGIN_PATH}; \
    confluent-hub install confluentinc/kafka-connect-salesforce:latest     --no-prompt --component-dir ${QA_PLUGIN_PATH}; \
    confluent-hub install confluentinc/kafka-connect-sqs:latest            --no-prompt --component-dir ${QA_PLUGIN_PATH}; \
    confluent-hub install jcustenborder/kafka-connect-json-schema:0.2.5    --no-prompt; \
    confluent-hub install snowflakeinc/snowflake-kafka-connector:1.5.0     --no-prompt;

CMD /etc/confluent/docker/run
```

docker-compose.yml:
```
version: '3.7'
services:
  connect:
    container_name: connect
    image: "metric-kafka-connect:latest"
    env_file: docker-compose.env
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - HOST=${DOCKER_HOSTNAME}
      - KAFKA_JMX_HOSTNAME=${DOCKER_HOSTNAME}
      - CONNECT_REST_PORT=8080
      - CONNECT_REST_ADVERTISED_HOST_NAME=${DOCKER_HOSTNAME}
      - CONNECT_REST_ADVERTISED_PORT=8080
    restart: on-failure:3
```

docker-compose.env:
```
# Shared Environment Variables
CONNECT_CONFLUENT_LICENSE=*****

# https://docs.confluent.io/current/connect/userguide.html
CONNECT_SECURITY_PROTOCOL=SASL_SSL
CONNECT_ADMIN_SECURITY_PROTOCOL=SASL_SSL
CONNECT_CONSUMER_SECURITY_PROTOCOL=SASL_SSL
CONNECT_PRODUCER_SECURITY_PROTOCOL=SASL_SSL

CONNECT_SESSION_TIMEOUT_MS=30000
CONNECT_ADMIN_SESSION_TIMEOUT_MS=30000
CONNECT_CONSUMER_SESSION_TIMEOUT_MS=30000
CONNECT_PRODUCER_SESSION_TIMEOUT_MS=30000

CONNECT_SASL_MECHANISM=PLAIN
CONNECT_ADMIN_SASL_MECHANISM=PLAIN
CONNECT_CONSUMER_SASL_MECHANISM=PLAIN
CONNECT_PRODUCER_SASL_MECHANISM=PLAIN

CONNECT_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=HTTPS
CONNECT_ADMIN_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=HTTPS
CONNECT_CONSUMER_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=HTTPS
CONNECT_PRODUCER_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=HTTPS

CONNECT_COMPRESSION_TYPE=lz4
CONNECT_PRODUCER_COMPRESSION_TYPE=lz4

CONNECT_ENHANCED_AVRO_SCHEMA_SUPPORT=true

# Required for docker (https://docs.confluent.io/current/installation/docker/docs/config-reference.html#kafka-connect-configuration):
CONNECT_GROUP_ID=connect
CONNECT_CONFIG_STORAGE_TOPIC=connect-configs
CONNECT_OFFSET_STORAGE_TOPIC=connect-offsets
CONNECT_OFFSET_STORAGE_PARTITIONS=60
CONNECT_STATUS_STORAGE_TOPIC=connect-status
CONNECT_STATUS_STORAGE_PARTITIONS=60

CONNECT_KEY_CONVERTER=org.apache.kafka.connect.storage.StringConverter
CONNECT_VALUE_CONVERTER=io.confluent.connect.avro.AvroConverter
CONNECT_INTERNAL_KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
CONNECT_INTERNAL_VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
CONNECT_CONNECTOR_CLIENT_CONFIG_OVERRIDE_POLICY=All
 
KAFKA_REPLICA_FETCH_MAX_BYTES=5048576
KAFKA_PRODUCER_MAX_REQUEST_SIZE=5048576
KAFKA_CONSUMER_MAX_PARTITION_FETCH_BYTES=5048576
CONNECT_PRODUCER_MAX_REQUEST_SIZE=5048576
CONNECT_CONSUMER_MAX_PARTITION_FETCH_BYTES=5048576

CONNECT_PLUGIN_PATH=/usr/share/java

KAFKA_HEAP_OPTS=-Xms512M -Xmx2G
CONNECT_BOOTSTRAP_SERVERS=SASL_SSL://**********.us-east-1.aws.confluent.cloud:9092

CONNECT_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username="*****" password="*****";
CONNECT_ADMIN_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username="*****" password="*****";
CONNECT_CONSUMER_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username="*****" password="*****";
CONNECT_PRODUCER_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username="*****" password="*****";

CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL=http://schemaregistry.company.com
CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL=http://schemaregistry.company.com

AWS_ACCESS_KEY_ID=*****
AWS_SECRET_ACCESS_KEY=*****

CONNECT_PLUGIN_PATH=/usr/share/java,/usr/share/confluent-hub-components,/usr/share/confluent-hub-components-qa

```

**Comment by lauraureche** [comment]
I have the same issue, with `confluentinc/cp-kafka-connect:5.5.1` and `snowflakeinc/snowflake-kafka-connector:1.4.3` the AVRO Snowflake connector is working as expected, but when I try to use `confluentinc/cp-kafka-connect:6.0.0` and `snowflakeinc/snowflake-kafka-connector:1.5.0` the connector is failing with the same "Class could not be found" error.

**Comment by sfc-gh-zli** [comment]
Fix here: https://github.com/snowflakedb/snowflake-kafka-connector/pull/241

**Comment by rvertigo** [comment]
@sfc-gh-zli Any word when 1.5.1 will be out? I'd love to close this issue and the one on my end.

**Comment by rvertigo** [comment]
@sfc-gh-zli Any word yet? It's been literally months and I would really like to update to get these fixes.
```
$ confluent-hub install snowflakeinc/snowflake-kafka-connector:1.5.1

Unable to find a component 
 
Error: Component not found, specify either valid name from Confluent Hub in format: <owner>/<name>:<version:latest> or path to a local file 
```

**Comment by sfc-gh-zli** [comment]
@rvertigo We have pushed the release 1.5.1 to maven and it should appear in confluent hub shortly.

**Comment by rvertigo** [comment]
Do you have a rough estimate for "shortly"? Like, Monday?

**Comment by sfc-gh-zli** [comment]
My guess is within a week. Confluent is in charge of pushing that to Confluent cloud, so it depends on their schedule as well.

**Comment by rvertigo** [comment]
I filed a ticket with Confluent, ~2.5 hours later the component was in the Confluent Hub.

I was able to install and verify that this issue is no longer reproducing.

Thanks!
