### ISSUE TITLE
Unable to start Snowflake Connector

### ISSUE THREAD

**Issue by mdube9** [snowflakedb/snowflake-kafka-connector#286]
I'm trying to setup Kafka connector for the first time and unable to create to proceed. It fails after creating TEST_CONNECTOR

Related logs

```
[2021-04-07 21:09:25,023] INFO EnrichedConnectorConfig values:
	connector.class = com.snowflake.kafka.connector.SnowflakeSinkConnector
	header.converter = class org.apache.kafka.connect.storage.SimpleHeaderConverter
	key.converter = class org.apache.kafka.connect.storage.StringConverter
	name = TEST_CONNECTOR
	tasks.max = 1
	transforms = []
	value.converter = class com.snowflake.kafka.connector.records.SnowflakeJsonConverter
 (org.apache.kafka.connect.runtime.ConnectorConfig$EnrichedConnectorConfig:279)
[2021-04-07 21:09:25,024] INFO Creating connector TEST_CONNECTOR of type com.snowflake.kafka.connector.SnowflakeSinkConnector (org.apache.kafka.connect.runtime.Worker:202)
[2021-04-07 21:09:25,028] INFO Instantiated connector TEST_CONNECTOR with version 1.5.0 of type class com.snowflake.kafka.connector.SnowflakeSinkConnector (org.apache.kafka.connect.runtime.Worker:205)
[2021-04-07 21:09:25,029] INFO
[SF_KAFKA_CONNECTOR] Snowflake Kafka Connector Version: 1.5.0 (com.snowflake.kafka.connector.Utils:99)
[2021-04-07 21:09:25,092] WARN
[SF_KAFKA_CONNECTOR] Connector update is available, please upgrade Snowflake Kafka Connector (1.5.0 -> 1.5.2)  (com.snowflake.kafka.connector.Utils:136)
[2021-04-07 21:09:25,092] INFO
[SF_KAFKA_CONNECTOR] SnowflakeSinkConnector:start (com.snowflake.kafka.connector.SnowflakeSinkConnector:91)
[2021-04-07 21:09:25,330] INFO
[SF_KAFKA_CONNECTOR] initialized the snowflake connection (com.snowflake.kafka.connector.internal.SnowflakeConnectionServiceV1:38)
[2021-04-07 21:09:25,336] INFO Finished creating connector TEST_CONNECTOR (org.apache.kafka.connect.runtime.Worker:224)
[2021-04-07 21:09:25,337] INFO Skipping reconfiguration of connector sflksink since it is not running (org.apache.kafka.connect.runtime.standalone.StandaloneHerder:285)
[2021-04-07 21:09:25,338] ERROR Stopping after connector error (org.apache.kafka.connect.cli.ConnectStandalone:113)
java.lang.NullPointerException
	at org.apache.kafka.connect.cli.ConnectStandalone$1.onCompletion(ConnectStandalone.java:104)
	at org.apache.kafka.connect.cli.ConnectStandalone$1.onCompletion(ConnectStandalone.java:98)
	at org.apache.kafka.connect.util.ConvertingFutureCallback.onCompletion(ConvertingFutureCallback.java:44)
	at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.putConnectorConfig(StandaloneHerder.java:185)
	at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:107)
[2021-04-07 21:09:25,340] INFO Kafka Connect stopping (org.apache.kafka.connect.runtime.Connect:65)
[2021-04-07 21:09:25,341] INFO Stopping REST server (org.apache.kafka.connect.runtime.rest.RestServer:211)
[2021-04-07 21:09:25,345] INFO Stopped http_8083@2cc0fa2a{HTTP/1.1}{0.0.0.0:8083} (org.eclipse.jetty.server.ServerConnector:306)
[2021-04-07 21:09:25,354] INFO Stopped o.e.j.s.ServletContextHandler@5c83ae01{/,null,UNAVAILABLE} (org.eclipse.jetty.server.handler.ContextHandler:865)
[2021-04-07 21:09:25,360] INFO REST server stopped (org.apache.kafka.connect.runtime.rest.RestServer:222)
[2021-04-07 21:09:25,360] INFO Herder stopping (org.apache.kafka.connect.runtime.standalone.StandaloneHerder:77)
[2021-04-07 21:09:25,360] INFO Stopping connector TEST_CONNECTOR (org.apache.kafka.connect.runtime.Worker:305)
[2021-04-07 21:09:25,361] INFO
[SF_KAFKA_CONNECTOR] SnowflakeSinkConnector:stop (com.snowflake.kafka.connector.SnowflakeSinkConnector:141)
[2021-04-07 21:09:25,362] INFO Stopped connector TEST_CONNECTOR (org.apache.kafka.connect.runtime.Worker:321)
[2021-04-07 21:09:25,362] INFO Worker stopping (org.apache.kafka.connect.runtime.Worker:151)
[2021-04-07 21:09:25,365] INFO Stopped FileOffsetBackingStore (org.apache.kafka.connect.storage.FileOffsetBackingStore:67)
[2021-04-07 21:09:25,365] INFO Worker stopped (org.apache.kafka.connect.runtime.Worker:172)
[2021-04-07 21:09:25,369] INFO Herder stopped (org.apache.kafka.connect.runtime.standalone.StandaloneHerder:87)
[2021-04-07 21:09:25,371] INFO Kafka Connect stopped (org.apache.kafka.connect.runtime.Connect:70)

```

The config file 
```
name=sflksink
connector.class=com.snowflake.kafka.connector.SnowflakeSinkConnector
tasks.max=1
topics=snowflake-connect-test
buffer.count.records=10
buffer.flush.time=60
buffer.size.bytes=50
snowflake.url.name=<url>
snowflake.user.name=<user>
snowflake.database.name=<db>
snowflake.schema.name=<schema>
snowflake.private.key=<private_key>
snowflake.warehouse.name=<warehouse>
key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=com.snowflake.kafka.connector.records.SnowflakeJsonConverter
```

**Comment by sfc-gh-tzhang** [comment]
@mdube9 looks like the problem comes from Kafka Connect instead of Kafka Connector, are you able to fix this?
```
[2021-04-07 21:09:25,338] ERROR Stopping after connector error (org.apache.kafka.connect.cli.ConnectStandalone:113)
java.lang.NullPointerException
	at org.apache.kafka.connect.cli.ConnectStandalone$1.onCompletion(ConnectStandalone.java:104)
	at org.apache.kafka.connect.cli.ConnectStandalone$1.onCompletion(ConnectStandalone.java:98)
	at org.apache.kafka.connect.util.ConvertingFutureCallback.onCompletion(ConvertingFutureCallback.java:44)
	at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.putConnectorConfig(StandaloneHerder.java:185)
	at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:107)
```

**Comment by sfc-gh-tzhang** [comment]
@mdube9 I'm going to close this since no reply, feel free to reopen it if this is not resolved
