### ISSUE TITLE
OutOfMemoryError: Java heap space while running connector

### ISSUE THREAD

**Issue by saggarsunil** [snowflakedb/snowflake-kafka-connector#295]
Connector version 1.4.3

While loading data from kafka topic, we saw OOM in connector logs

```
Task Status:FAILED, Trace:org.apache.kafka.connect.errors.ConnectException: 
Exiting WorkerSinkTask due to unrecoverable exception.     
at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:567)     
at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:325)     
at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:228)     
at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:200)     
at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:184)     
at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)     
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)     
at java.util.concurrent.FutureTask.run(FutureTask.java:266)     
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)     
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)     
at java.lang.Thread.run(Thread.java:748) Caused by: java.lang.OutOfMemoryError: Java heap space     
at java.util.Arrays.copyOf(Arrays.java:3332)     
at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)     
at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)     
at java.lang.StringBuilder.append(StringBuilder.java:136)     
at com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1$ServiceContext$PartitionBuffer.insert(SnowflakeSinkServiceV1.java:803)     
at com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1$ServiceContext$PartitionBuffer.access$600(SnowflakeSinkServiceV1.java:758)     
at com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1$ServiceContext.insert(SnowflakeSinkServiceV1.java:432)     
at com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1$ServiceContext.access$300(SnowflakeSinkServiceV1.java:262)     
at com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1.insert(SnowflakeSinkServiceV1.java:103)     
at com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1.insert(SnowflakeSinkServiceV1.java:80)     
at com.snowflake.kafka.connector.SnowflakeSinkTask.put(SnowflakeSinkTask.java:225)     
at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:545)
```

We just saw it once and it worked fine after that

**Comment by sfc-gh-tzhang** [comment]
@saggarsunil please create a support case and share the full DEBUG log with us if you hit this again, it's hard to debug with the information above, thanks!
