### ISSUE TITLE
Terrible error thrown for bad `snowflake.private.key`

### ISSUE THREAD

**Issue by aidan-melen** [snowflakedb/snowflake-kafka-connector#330]
Problem Description:

When a user passes badly formatted private key. You get a non-descript `java.lang.IllegalArgumentException: Last encoded character (before the paddings if any) is a valid base 64 alphabet but not a possible value. Expected the discarded bits to be zero.` stack trace.

## Connect Config:

```
curl -i -X POST -H "Content-Type: application/json" --data '{
    "name": "kafka-connect",
    "config": {
        "buffer.count.records": 10000,
        "buffer.flush.time": 120,
        "buffer.size.bytes": 5000000,
        "config.providers": "file",
        "config.providers.file.class": "org.apache.kafka.common.config.provider.FileConfigProvider",
        "connector.class": "com.snowflake.kafka.connector.SnowflakeSinkConnector",
        "key.converter": "org.apache.kafka.connect.storage.StringConverter",
        "value.converter": "org.apache.kafka.connect.storage.StringConverter",
        "plugin.path": "/usr/share/java,/usr/share/confluent-hub-components",
        "snowflake.database.name": "DATABASE_NAME",
        "snowflake.private.key": "THIS_IS_A_FAKE_KEY", <===============
        "snowflake.schema.name": "SCHEMA_NAME",
        "snowflake.topic2table.map": "my.Topic:MY_TOPIC",
        "snowflake.url.name": "https://FAKE.snowflakecomputing.com:443",
        "snowflake.user.name": "USER_NAME",
        "tasks.max": 1,
        "topics": "my.Topic"
    }
}' http://localhost:8083/connectors
```

## Stack Trace:

```
[2021-08-16 22:58:50,562] ERROR WorkerConnector{id=kafka-connect} Error while starting connector (org.apache.kafka.connect.runtime.WorkerConnector)
java.lang.IllegalArgumentException: Last encoded character (before the paddings if any) is a valid base 64 alphabet but not a possible value. Expected the discarded bits to be zero.
	at net.snowflake.client.jdbc.internal.apache.commons.codec.binary.Base64.validateCharacter(Base64.java:803)
	at net.snowflake.client.jdbc.internal.apache.commons.codec.binary.Base64.decode(Base64.java:477)
	at net.snowflake.client.jdbc.internal.apache.commons.codec.binary.BaseNCodec.decode(BaseNCodec.java:482)
	at net.snowflake.client.jdbc.internal.apache.commons.codec.binary.BaseNCodec.decode(BaseNCodec.java:465)
	at net.snowflake.client.jdbc.internal.apache.commons.codec.binary.Base64.decodeBase64(Base64.java:699)
	at com.snowflake.kafka.connector.internal.InternalUtils.parsePrivateKey(InternalUtils.java:79)
	at com.snowflake.kafka.connector.internal.InternalUtils.createProperties(InternalUtils.java:154)
	at com.snowflake.kafka.connector.internal.SnowflakeConnectionServiceFactory$SnowflakeConnectionServiceBuilder.setProperties(SnowflakeConnectionServiceFactory.java:58)
	at com.snowflake.kafka.connector.SnowflakeSinkConnector.start(SnowflakeSinkConnector.java:96)
	at org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:185)
	at org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:210)
	at org.apache.kafka.connect.runtime.WorkerConnector.doTransitionTo(WorkerConnector.java:349)
	at org.apache.kafka.connect.runtime.WorkerConnector.doTransitionTo(WorkerConnector.java:332)
	at org.apache.kafka.connect.runtime.WorkerConnector.doRun(WorkerConnector.java:140)
	at org.apache.kafka.connect.runtime.WorkerConnector.run(WorkerConnector.java:117)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by pcb-submittable** [comment]
Agreed. I was able to set it up in Snowflake connector fine, but getting this error while trying to unit test this github package...tried every formatting of the private key I could think of but without success.

**Comment by sfc-gh-rcheng** [comment]
Closing this issue out due to age - please reopen if further discussion is needed.
