### ISSUE TITLE
SSL Connection to Schema Registry Failing

### ISSUE THREAD

**Issue by scottrpoulin** [snowflakedb/snowflake-kafka-connector#336]
Looking for recommendations on how to resolve connecting to a Schema Registry that requires SSL.

When using the standard configuration we receive the following exception
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target (com.snowflake.kafka.connector.records.SnowflakeConverter)

When we add
key.converter.schema.registry.ssl.truststore.location
key.converter.schema.registry.ssl.truststore.password
key.converter.schema.registry.ssl.keystore.location 
key.converter.schema.registry.ssl.keystore.password

value.converter.schema.registry.ssl.truststore.location
value.converter.schema.registry.ssl.truststore.password
value.converter.schema.registry.ssl.keystore.location 
value.converter.schema.registry.ssl.keystore.password

We receive the following exception at start up of the connector
com.snowflake.kafka.connector.internal.SnowflakeKafkaConnectorException: 
[SF_KAFKA_CONNECTOR] Exception: Failed to connect schema registry service
[SF_KAFKA_CONNECTOR] Error Code: 0012
[SF_KAFKA_CONNECTOR] Detail: Schema registry service is not available
[SF_KAFKA_CONNECTOR] Message: Error initializing the ssl context for RestService
[SF_KAFKA_CONNECTOR] io.confluent.kafka.schemaregistry.client.security.SslFactory.<init>(SslFactory.java:71)
[SF_KAFKA_CONNECTOR] io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.<init>(CachedSchemaRegistryClient.java:177)
[SF_KAFKA_CONNECTOR] io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.<init>(CachedSchemaRegistryClient.java:126)
[SF_KAFKA_CONNECTOR] io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.<init>(CachedSchemaRegistryClient.java:95)
[SF_KAFKA_CONNECTOR] com.snowflake.kafka.connector.records.SnowflakeAvroConverter.configure(SnowflakeAvroConverter.java:61)
[SF_KAFKA_CONNECTOR] org.apache.kafka.connect.runtime.isolation.Plugins.newConverter(Plugins.java:298)
[SF_KAFKA_CONNECTOR] org.apache.kafka.connect.runtime.Worker.startTask(Worker.java:530)
[SF_KAFKA_CONNECTOR] org.apache.kafka.connect.runtime.distributed.DistributedHerder.startTask(DistributedHerder.java:1287)
[SF_KAFKA_CONNECTOR] org.apache.kafka.connect.runtime.distributed.DistributedHerder.lambda$getTaskStartingCallable$17(DistributedHerder.java:1300)
[SF_KAFKA_CONNECTOR] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[SF_KAFKA_CONNECTOR] java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[SF_KAFKA_CONNECTOR] java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[SF_KAFKA_CONNECTOR] java.base/java.lang.Thread.run(Thread.java:829)
        at com.snowflake.kafka.connector.internal.SnowflakeErrors.getException(SnowflakeErrors.java:289)
        at com.snowflake.kafka.connector.internal.SnowflakeErrors.getException(SnowflakeErrors.java:271)
        at com.snowflake.kafka.connector.internal.SnowflakeErrors.getException(SnowflakeErrors.java:261)
        at com.snowflake.kafka.connector.records.SnowflakeAvroConverter.configure(SnowflakeAvroConverter.java:64)
        at org.apache.kafka.connect.runtime.isolation.Plugins.newConverter(Plugins.java:298)
        at org.apache.kafka.connect.runtime.Worker.startTask(Worker.java:530)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startTask(DistributedHerder.java:1287)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.lambda$getTaskStartingCallable$17(DistributedHerder.java:1300)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
        
Not sure if this is related to 
https://github.com/snowflakedb/snowflake-kafka-connector/issues/221 

Any help would be appreciated!

**Comment by scottrpoulin** [comment]
Figured this out. Either in your kafka connect cluster configuration or the connector configuration you need to add the following and have the files on your pod when it is deployed

key.converter.schema.registry.ssl.truststore.location=<location>
key.converter.schema.registry.ssl.truststore.password=<trustore-password>
key.converter.schema.registry.ssl.keystore.location=<keystore-location>
key.converter.schema.registry.ssl.keystore.password=<keystore-password>
key.converter.schema.registry.ssl.key.password=<key-password>

value.converter.schema.registry.ssl.truststore.location=<location>
value.converter.schema.registry.ssl.truststore.password=<trustore-password>
value.converter.schema.registry.ssl.keystore.location=<keystore-location>
value.converter.schema.registry.ssl.keystore.password=<keystore-password>
value.converter.schema.registry.ssl.key.password=<key-password>
