### ISSUE TITLE
ClassNotFoundException: io.confluent.common.utils.Utils

### ISSUE THREAD

**Issue by anekdoti** [snowflakedb/snowflake-kafka-connector#342]
I am trying to run a Snowflake Kafka connector instance (v.1.5.5) on Kafka Connect 2.8 using the Avro converter.
On every task, I immediately get the following exception:

```
 java.lang.NoClassDefFoundError: io/confluent/common/utils/Utils
                at io.confluent.common.config.AbstractConfig.logAll(AbstractConfig.java:171)
                at io.confluent.common.config.AbstractConfig.<init>(AbstractConfig.java:80)
                at io.confluent.kafka.serializers.AbstractKafkaSchemaSerDeConfig.<init>(AbstractKafkaSchemaSerDeConfig.java:166)
                at io.confluent.kafka.serializers.AbstractKafkaAvroSerDeConfig.<init>(AbstractKafkaAvroSerDeConfig.java:121)
                at com.snowflake.kafka.connector.records.AvroConverterConfig.<init>(AvroConverterConfig.java:24)
                at com.snowflake.kafka.connector.records.SnowflakeAvroConverter.configure(SnowflakeAvroConverter.java:50)
                at org.apache.kafka.connect.runtime.isolation.Plugins.newConverter(Plugins.java:298)
                at org.apache.kafka.connect.runtime.Worker.startTask(Worker.java:532)
                at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startTask(DistributedHerder.java:1287)
                at org.apache.kafka.connect.runtime.distributed.DistributedHerder.lambda$getTaskStartingCallable$17(DistributedHerder.java:1300)
                at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
                at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: io.confluent.common.utils.Utils
  at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
  at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:104)
  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
  ... 14 more
```

The Maven package common-utils which contains the class not found is excluded from all dependencies of the Snowflake Kafka connector. Is it expected to be already present on the Kafka Connect nodes?

**Comment by sfc-gh-japatel** [comment]
Please use the zip file directly from confluent hub, it contains few more jars on top of the snowflake kc jar. 
Also upgrade it to >= 1.6.7
