### ISSUE TITLE
Crash when trying to handle broken data

### ISSUE THREAD

**Issue by iexos** [snowflakedb/snowflake-kafka-connector#36]
After upgrading the connector 0.4.0, it is constantly crashing, probably on handling broken data (from looking at the stack trace).

The configuration includes:
```
    "errors.tolerance": "all",
    "key.converter": "org.apache.kafka.connect.storage.StringConverter",
    "value.converter": "com.snowflake.kafka.connector.records.SnowflakeJsonConverter",
```

stack trace:
```
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:560)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:321)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
	at com.snowflake.kafka.connector.records.SnowflakeRecordContent.getBrokenData(SnowflakeRecordContent.java:81)
	at com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1$ServiceContext.writeBrokenDataToTableStage(SnowflakeSinkServiceV1.java:358)
	at com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1$ServiceContext.insert(SnowflakeSinkServiceV1.java:321)
	at com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1$ServiceContext.access$100(SnowflakeSinkServiceV1.java:167)
	at com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1.insert(SnowflakeSinkServiceV1.java:78)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at com.snowflake.kafka.connector.SnowflakeSinkTask.put(SnowflakeSinkTask.java:160)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:538)
	... 10 more
```

**Comment by binglihub** [comment]
@iexos @sabarigk Thank you for reporting the error. We will fix this issue later.

**Comment by binglihub** [comment]
https://github.com/snowflakedb/snowflake-kafka-connector/commit/b4d712b9dec453faf89cc3eb2222f9f23343308b

Now, when meet a null value, connector will generate an empty JSON record "{}".
