### ISSUE TITLE
Snowflake Connector not shutting down properly

### ISSUE THREAD

**Issue by madisoncoder15** [snowflakedb/snowflake-kafka-connector#37]
After upgrading to 0.4.0, the connector seems to shut down improperly where it fails to drop the internal stage. When I shut down the connector, I get the following error message:

```
[2019-09-10 15:39:42,757] ERROR Graceful stop of task snowflake_sink-0 failed. (org.apache.kafka.connect.runtime.Worker)
[2019-09-10 15:39:43,314] ERROR [SF_KAFKA_CONNECTOR] Failed to drop empty internal stage: SNOWFLAKE_KAFKA_CONNECTOR_snowflake_sink_STAGE_Test4. It can safely be removed. Exception: java.lang.IllegalStateException: Shutdown in progress (com.snowflake.kafka.connector.SnowflakeSinkConnector)
```

When I check in Snowflake, the internal stage still appears to be there (just as the error message states). When I run the connector again with the internal stage still present, it actually deletes the stage but still throws the following error and crashes:

```
[2019-09-10 15:41:36,622] ERROR WorkerConnector{id=snowflake_sink} Error while starting connector (org.apache.kafka.connect.runtime.WorkerConnector)
com.snowflake.kafka.connector.internal.SnowflakeKafkaConnectorException:
[SF_KAFKA_CONNECTOR] Exception: Connector stopped due to invalid configuration
[SF_KAFKA_CONNECTOR] Error Code: 5006
[SF_KAFKA_CONNECTOR] Detail: Exception while creating or validating table, stage, or pipe.
[SF_KAFKA_CONNECTOR] Message:
[SF_KAFKA_CONNECTOR] [SF_KAFKA_CONNECTOR] Exception: Incompatible stage
[SF_KAFKA_CONNECTOR] [SF_KAFKA_CONNECTOR] Error Code: 5004
[SF_KAFKA_CONNECTOR] [SF_KAFKA_CONNECTOR] Detail: Stage contains files that were not created by the Snowflake Kafka Connector. The stage needs a careful cleanup.
[SF_KAFKA_CONNECTOR] [SF_KAFKA_CONNECTOR] Message: Stage name: SNOWFLAKE_KAFKA_CONNECTOR_snowflake_sink_STAGE_Test4
[SF_KAFKA_CONNECTOR] com.snowflake.kafka.connector.internal.SnowflakeErrors.getException(SnowflakeErrors.java:347)
[SF_KAFKA_CONNECTOR] com.snowflake.kafka.connector.SnowflakeSinkConnector.start(SnowflakeSinkConnector.java:217)
[SF_KAFKA_CONNECTOR] org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:111)
[SF_KAFKA_CONNECTOR] org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:136)
[SF_KAFKA_CONNECTOR] org.apache.kafka.connect.runtime.WorkerConnector.transitionTo(WorkerConnector.java:196)
[SF_KAFKA_CONNECTOR] org.apache.kafka.connect.runtime.Worker.startConnector(Worker.java:231)
[SF_KAFKA_CONNECTOR] org.apache.kafka.connect.runtime.standalone.StandaloneHerder.startConnector(StandaloneHerder.java:289)
[SF_KAFKA_CONNECTOR] org.apache.kafka.connect.runtime.standalone.StandaloneHerder.putConnectorConfig(StandaloneHerder.java:205)
[SF_KAFKA_CONNECTOR] org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:113)
        at com.snowflake.kafka.connector.internal.SnowflakeErrors.getException(SnowflakeErrors.java:347)
        at com.snowflake.kafka.connector.internal.SnowflakeErrors.getException(SnowflakeErrors.java:323)
        at com.snowflake.kafka.connector.SnowflakeSinkConnector.start(SnowflakeSinkConnector.java:231)
        at org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:111)
        at org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:136)
        at org.apache.kafka.connect.runtime.WorkerConnector.transitionTo(WorkerConnector.java:196)
        at org.apache.kafka.connect.runtime.Worker.startConnector(Worker.java:231)
        at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.startConnector(StandaloneHerder.java:289)
        at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.putConnectorConfig(StandaloneHerder.java:205)
        at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:113)
```

When I shut down the connector and restart it once more (after getting this error), it works and I can continue sending messages as usual. I'm curious as to why the internal stage isn't being properly dropped when I stop the connector.

**Comment by iexos** [comment]
We are running into the same problem. Regardless if the connector was shut down properly, it should recover automatically.

**Comment by binglihub** [comment]
In next release, connector will not drop stage and pipe anymore because if always timeout on terminating. Connector will keep such SF object for recovery. Our official document will provide more detail about this change later.
