### ISSUE TITLE
Duplicate keys when using multiple Options with ProtobufConverter 

### ISSUE THREAD

**Issue by x5y** [snowflakedb/snowflake-kafka-connector#424]
When using the ProtobufConverter to deserialise a Protobuf schema with multiple file-level options of the same type, but different sub-fields, an `IllegalStateException: Duplicate key` exception is thrown.

For example, a schema that looks like this:
```protobuf
option (my_option).foo = "1";
option (my_option).bar = "2";
```
will generate an error like:
```
org.apache.kafka.connect.errors.DataException: Failed to deserialize data for topic TOPIC to Protobuf: 
	at io.confluent.connect.protobuf.ProtobufConverter.toConnectData(ProtobufConverter.java:130)
	at org.apache.kafka.connect.storage.Converter.toConnectData(Converter.java:87)
	...
org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:200)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:142)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertAndTransformRecord(WorkerSinkTask.java:519)
        ...
Caused by: org.apache.kafka.common.errors.SerializationException: Error deserializing Protobuf message for id 100095
	at io.confluent.kafka.serializers.protobuf.AbstractKafkaProtobufDeserializer.deserialize(AbstractKafkaProtobufDeserializer.java:176)
	...
Caused by: java.lang.IllegalStateException: Duplicate key my_option (attempted merging values OptionElement(name=my_option, kind=OPTION, value=OptionElement(name=foo, kind=STRING, value=1, isParenthesized=false), isParenthesized=true) and OptionElement(name=my_option, kind=OPTION, value=OptionElement(name=bar, kind=STRING, value=2, isParenthesized=false), isParenthesized=true))
	at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:133)
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180)
	...
```
This appears to be [a bug within the Confluent schemaregistry library](https://github.com/confluentinc/schema-registry/pull/2155), which has been fixed in a later version (7.0.2/7.1.0) than what the connector currently depends on ([6.2.0](https://github.com/snowflakedb/snowflake-kafka-connector/blob/master/pom.xml#L362)).

What is the process for getting this dependency bumped to a later version?

**Comment by sfc-gh-rcheng** [comment]
Closing this issue out due to age - please reopen if further discussion is needed.
