### ISSUE TITLE
Tasks in snowflake connector get stuck in a deadlock and stop processing data

### ISSUE THREAD

**Issue by ddasarathan** [snowflakedb/snowflake-kafka-connector#426]
SnowflakeSink connector uses the snowflake-ingest-sdk to ingest data into Snowflake.

When investigating logs on this library, we saw the log for `Sending Request UUID` gets printed before making the request to Snowflake, but the log `Attempting to unmarshall insert response` which indicates the Request completed does now come. 

A thread dump of the task shows that the Http client execute method is stuck in a deadlock.

```
java.lang.Thread.State: WAITING (parking)
    at jdk.internal.misc.Unsafe.park(java.base@16.0.2/Native Method)
    - parking to wait for  <0x00000005c6907e50> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
    at java.util.concurrent.locks.LockSupport.park(java.base@16.0.2/LockSupport.java:341)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(java.base@16.0.2/AbstractQueuedSynchronizer.java:505)
    at java.util.concurrent.ForkJoinPool.managedBlock(java.base@16.0.2/ForkJoinPool.java:3137)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(java.base@16.0.2/AbstractQueuedSynchronizer.java:1614)
    at net.snowflake.ingest.internal.apache.http.pool.AbstractConnPool.getPoolEntryBlocking(AbstractConnPool.java:393)
    at net.snowflake.ingest.internal.apache.http.pool.AbstractConnPool.access$300(AbstractConnPool.java:70)
    at net.snowflake.ingest.internal.apache.http.pool.AbstractConnPool$2.get(AbstractConnPool.java:253)
    - locked <0x00000005e54aaeb8> (a net.snowflake.ingest.internal.apache.http.pool.AbstractConnPool$2)
    at net.snowflake.ingest.internal.apache.http.pool.AbstractConnPool$2.get(AbstractConnPool.java:198)
    at net.snowflake.ingest.internal.apache.http.impl.conn.PoolingHttpClientConnectionManager.leaseConnection(PoolingHttpClientConnectionManager.java:306)
    at net.snowflake.ingest.internal.apache.http.impl.conn.PoolingHttpClientConnectionManager$1.get(PoolingHttpClientConnectionManager.java:282)
    at net.snowflake.ingest.internal.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:190)
    at net.snowflake.ingest.internal.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
    at net.snowflake.ingest.internal.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
    at net.snowflake.ingest.internal.apache.http.impl.execchain.ServiceUnavailableRetryExec.execute(ServiceUnavailableRetryExec.java:85)
    at net.snowflake.ingest.internal.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
    at net.snowflake.ingest.internal.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
    at net.snowflake.ingest.internal.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
    at net.snowflake.ingest.internal.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
    at net.snowflake.ingest.internal.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
    at net.snowflake.ingest.SimpleIngestManager.getHistory(SimpleIngestManager.java:590)
    at com.snowflake.kafka.connector.internal.SnowflakeIngestionServiceV1.lambda$readIngestReport$2(SnowflakeIngestionServiceV1.java:127)
    at com.snowflake.kafka.connector.internal.SnowflakeIngestionServiceV1$$Lambda$1299/0x0000000805fe7138.apply(Unknown Source)
    at com.snowflake.kafka.connector.internal.InternalUtils.backoffAndRetry(InternalUtils.java:283)
    at com.snowflake.kafka.connector.internal.SnowflakeIngestionServiceV1.readIngestReport(SnowflakeIngestionServiceV1.java:124)
    at com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1$ServiceContext.checkStatus(SnowflakeSinkServiceV1.java:788)
    at com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1$ServiceContext.lambda$startCleaner$0(SnowflakeSinkServiceV1.java:478)
    at com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1$ServiceContext$$Lambda$1269/0x0000000805f232f8.run(Unknown Source)
    at java.util.concurrent.Executors$RunnableAdapter.call(java.base@16.0.2/Executors.java:515)
    at java.util.concurrent.FutureTask.run(java.base@16.0.2/FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@16.0.2/ThreadPoolExecutor.java:1130)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@16.0.2/ThreadPoolExecutor.java:630)
    at java.lang.Thread.run(java.base@16.0.2/Thread.java:831)
```

At this time restarting, resuming, or pausing the connector is not an option. The only workaround is to restart the worker process/ pod

A recommended fix can be found in https://programmer.ink/think/troubleshooting-of-apache-httpclient-connection-pool-leakage.html and the officual documentation for Apache HttpClient suggests to close the entity object in https://hc.apache.org/httpcomponents-client-5.1.x/quickstart.html

**Comment by sfc-gh-tzhang** [comment]
This is fixed now, closing
