### ISSUE TITLE
Log name of the config parameter along with "Invalid input connector configuration"

### ISSUE THREAD

**Issue by dlg99** [snowflakedb/snowflake-kafka-connector#442]
Now I have to debug through the connector to understand what it didn't like:

```
com.snowflake.kafka.connector.internal.SnowflakeKafkaConnectorException:
[SF_KAFKA_CONNECTOR] Exception: Invalid input connector configuration
[SF_KAFKA_CONNECTOR] Error Code: 0001
[SF_KAFKA_CONNECTOR] Detail: input kafka connector configuration is null, missing required values, or wrong input value
	at com.snowflake.kafka.connector.internal.SnowflakeErrors.getException(SnowflakeErrors.java:289) ~[?:?]
	at com.snowflake.kafka.connector.internal.SnowflakeErrors.getException(SnowflakeErrors.java:256) ~[?:?]
	at com.snowflake.kafka.connector.Utils.validateConfig(Utils.java:469) ~[?:?]
	at com.snowflake.kafka.connector.SnowflakeSinkConnector.start(SnowflakeSinkConnector.java:87) ~[?:?]
```

**Comment by sfc-gh-rcheng** [comment]
Requested change released in [1.9.2](https://github.com/snowflakedb/snowflake-kafka-connector/releases/tag/v1.9.2). Thanks for opening this issue
