### ISSUE TITLE
Help on SNOWPIPE_STREAMING ingestion method

### ISSUE THREAD

**Issue by alex-magno** [snowflakedb/snowflake-kafka-connector#520]
Hello all! I'm currently running some tests using the `SNOWPIPE_STREAMING` ingestion method - I'm specifically interested in the `schematization` feature recently released.

However, I'm facing a connector task problem when creating the connector:
```
org.apache.kafka.connect.errors.ConnectException: net.snowflake.ingest.utils.SFException: Client configure request failed: HTTP Status: 400 ErrorBody: {
  "status_code" : 1,
  "message" : "The given request has an invalid format."
}.
	at com.snowflake.kafka.connector.internal.streaming.SnowflakeSinkServiceV2.initStreamingClient(SnowflakeSinkServiceV2.java:485)
	at com.snowflake.kafka.connector.internal.streaming.SnowflakeSinkServiceV2.<init>(SnowflakeSinkServiceV2.java:138)
	at com.snowflake.kafka.connector.internal.SnowflakeSinkServiceFactory$SnowflakeSinkServiceBuilder.<init>(SnowflakeSinkServiceFactory.java:50)
	at com.snowflake.kafka.connector.internal.SnowflakeSinkServiceFactory$SnowflakeSinkServiceBuilder.<init>(SnowflakeSinkServiceFactory.java:40)
	at com.snowflake.kafka.connector.internal.SnowflakeSinkServiceFactory.builder(SnowflakeSinkServiceFactory.java:26)
	at com.snowflake.kafka.connector.SnowflakeSinkTask.start(SnowflakeSinkTask.java:240)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:312)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:186)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:243)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: net.snowflake.ingest.utils.SFException: Client configure request failed: HTTP Status: 400 ErrorBody: {
  "status_code" : 1,
  "message" : "The given request has an invalid format."
}.
	at net.snowflake.ingest.streaming.internal.StreamingIngestStage.makeClientConfigureCall(StreamingIngestStage.java:337)
	at net.snowflake.ingest.streaming.internal.StreamingIngestStage.refreshSnowflakeMetadata(StreamingIngestStage.java:224)
	at net.snowflake.ingest.streaming.internal.StreamingIngestStage.refreshSnowflakeMetadata(StreamingIngestStage.java:200)
	at net.snowflake.ingest.streaming.internal.StreamingIngestStage.<init>(StreamingIngestStage.java:103)
	at net.snowflake.ingest.streaming.internal.FlushService.<init>(FlushService.java:173)
	at net.snowflake.ingest.streaming.internal.SnowflakeStreamingIngestClientInternal.<init>(SnowflakeStreamingIngestClientInternal.java:193)
	at net.snowflake.ingest.streaming.internal.SnowflakeStreamingIngestClientInternal.<init>(SnowflakeStreamingIngestClientInternal.java:216)
	at net.snowflake.ingest.streaming.SnowflakeStreamingIngestClientFactory$Builder.build(SnowflakeStreamingIngestClientFactory.java:52)
	at com.snowflake.kafka.connector.internal.streaming.SnowflakeSinkServiceV2.initStreamingClient(SnowflakeSinkServiceV2.java:480)
	... 13 more
Caused by: 
HTTP Status: 400
{
  "status_code" : 1,
  "message" : "The given request has an invalid format."
}
	at net.snowflake.ingest.connection.ServiceResponseHandler.handleExceptionalStatus(ServiceResponseHandler.java:277)
	at net.snowflake.ingest.connection.ServiceResponseHandler.unmarshallStreamingIngestResponse(ServiceResponseHandler.java:236)
	at net.snowflake.ingest.streaming.internal.StreamingIngestUtils.executeWithRetries(StreamingIngestUtils.java:102)
	at net.snowflake.ingest.streaming.internal.StreamingIngestStage.makeClientConfigureCall(StreamingIngestStage.java:320)
	... 21 more
```

Additional log lines that can be helpful:
```
INFO  Creating a RequestBuilder with arguments : Account : ****, User : ****, Scheme : https, Host : ****.eu-west-1.snowflakecomputing.com, Port : 443, userAgentSuffix: null (net.snowflake.ingest.connection.RequestBuilder)
```
```
ERROR Exceptional Status Code from STREAMING_CLIENT_CONFIGURE: 400, requestId: (net.snowflake.ingest.connection.ServiceResponseHandler)
```

The connector configs that I'm using are identical to this one, in the test section: https://github.com/snowflakedb/snowflake-kafka-connector/blob/master/test/rest_request_template/travis_correct_schema_evolution_avro_sr.json

As I'm getting a 400, I imagine that for some reason the request is being malformed. By digging a little bit in the code I noticed that the `RequestBuilder` constructor for streaming ingestion hardcodes the `userAgentSuffix` to `null`, here: https://github.com/snowflakedb/snowflake-ingest-java/blob/f5aa42bfe9c4273c0c58d15eadad0aac2a1164c2/src/main/java/net/snowflake/ingest/connection/RequestBuilder.java#L224-L240

That explains the `null` value in the logs above. If it is a required parameter to be on request headers, that may explain the 400 code?

It is worth to mention that I'm able to run the connector on the `SNOWPIPE` ingestion method, without schematization. So this excludes any problems related to networking, RBAC or private key issues with my setup. When I change to `SNOWPIPE_STREAMING` and enable `schematization`, I start getting this error.

I appreciate any help! Thanks 😄

**Comment by rwilson-r7** [comment]
Hitting the same and curious of any guidance here too

**Comment by sfc-gh-tzhang** [comment]
hi, `SNOWPIPE_STREAMING` (as well as schematization) is still a Private Preview feature and needs to be enabled on the account in order to use it, please contact Snowflake Sales/Support if you want to participate in the preview, thanks!
