### ISSUE TITLE
Production ready status?

### ISSUE THREAD

**Issue by arkady-emelyanov** [snowflakedb/snowflake-kafka-connector#54]
Hey! Thanks for supporting kafka-connect platform.

Just wondering, is there any version that I can deploy to production?
After quick evaluation, v0.4.0 fails at some point with non-recoverable error (`failed to drop stage`).

I've tried to use v0.5.0, but, got a `NullPointerException`, was not able to solve problem.
We are using topic2table mapping, so, according to latest changes - it seems there was a bug introduced.

So, going back to original question: is there any version (maybe v0.5.1?) that can be considered stable to be used in production?

**Comment by sabarigk** [comment]
We just tool the 0.5.0 upgrade and seeing a null pointer error. I believe this is the same error mentioned above. This is the stack trace.
java.lang.NullPointerException
        at com.snowflake.kafka.connector.SnowflakeSinkTask.lambda$preCommit$1(SnowflakeSinkTask.java:189)
        at java.util.HashMap.forEach(HashMap.java:1288)
        at com.snowflake.kafka.connector.SnowflakeSinkTask.preCommit(SnowflakeSinkTask.java:186)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.commitOffsets(WorkerSinkTask.java:378)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.closePartitions(WorkerSinkTask.java:590)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:196)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by arkady-emelyanov** [comment]
@sabarigk yep, that was our case indeed both on v0.5.0 tag and for master branch:
```java.lang.NullPointerException
at com.snowflake.kafka.connector.SnowflakeSinkTask.lambda$preCommit$1(SnowflakeSinkTask.java:189)
```
