### ISSUE TITLE
document how to run connector with java 17 

### ISSUE THREAD

**Issue by acristu** [snowflakedb/snowflake-kafka-connector#542]
Recommended java version for confluent 7.3.0 is Java 17 (see
https://docs.confluent.io/platform/current/installation/versions-interoperability.html):

> Java 17 is the recommended version in this version of Confluent Platform. Java 11 and Java 8 are also supported.

First issue from apache arrow:

```
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:611)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:333)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:234)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:203)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:189)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:244)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.apache.kafka.connect.errors.DataException: Error inserting Records using Streaming API
	at com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel.handleInsertRowsFailures(TopicPartitionChannel.java:748)
	at com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel.insertBufferedRecords(TopicPartitionChannel.java:521)
	at com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel.insertBufferedRecordsIfFlushTimeThresholdReached(TopicPartitionChannel.java:492)
	at com.snowflake.kafka.connector.internal.streaming.SnowflakeSinkServiceV2.insert(SnowflakeSinkServiceV2.java:214)
	at com.snowflake.kafka.connector.SnowflakeSinkTask.put(SnowflakeSinkTask.java:328)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:581)
	... 10 more
Caused by: net.snowflake.ingest.utils.SFException: Ingest client internal error: null.
	at net.snowflake.ingest.streaming.internal.AbstractRowBuffer.insertRows(AbstractRowBuffer.java:298)
	at net.snowflake.ingest.streaming.internal.SnowflakeStreamingIngestChannelInternal.insertRows(SnowflakeStreamingIngestChannelInternal.java:345)
	at net.snowflake.ingest.streaming.internal.SnowflakeStreamingIngestChannelInternal.insertRow(SnowflakeStreamingIngestChannelInternal.java:318)
	at com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel$InsertRowsApiResponseSupplier.get(TopicPartitionChannel.java:636)
	at com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel$InsertRowsApiResponseSupplier.get(TopicPartitionChannel.java:588)
	at dev.failsafe.Functions.lambda$toCtxSupplier$11(Functions.java:243)
	at dev.failsafe.Functions.lambda$get$0(Functions.java:46)
	at dev.failsafe.internal.FallbackExecutor.lambda$apply$0(FallbackExecutor.java:51)
	at dev.failsafe.SyncExecutionImpl.executeSync(SyncExecutionImpl.java:182)
	at dev.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:438)
	at dev.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:115)
	at com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel.insertRowsWithFallback(TopicPartitionChannel.java:582)
	at com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel.insertBufferedRecords(TopicPartitionChannel.java:511)
	... 14 more
Caused by: java.lang.ExceptionInInitializerError
	at net.snowflake.ingest.internal.apache.arrow.memory.ArrowBuf.setZero(ArrowBuf.java:1175)
	at net.snowflake.ingest.internal.apache.arrow.vector.complex.StructVector.reallocValidityBuffer(StructVector.java:481)
	at net.snowflake.ingest.internal.apache.arrow.vector.complex.StructVector.setIndexDefined(StructVector.java:581)
	at net.snowflake.ingest.streaming.internal.ArrowRowBuffer.convertRowToArrow(ArrowRowBuffer.java:569)
	at net.snowflake.ingest.streaming.internal.ArrowRowBuffer.addRow(ArrowRowBuffer.java:412)
	at net.snowflake.ingest.streaming.internal.AbstractRowBuffer.insertRows(AbstractRowBuffer.java:290)
	... 26 more
Caused by: java.lang.RuntimeException: Failed to initialize MemoryUtil. Was Java started with `--add-opens=java.base/java.nio=ALL-UNNAMED`? (See https://arrow.apache.org/docs/java/install.html)
	at net.snowflake.ingest.internal.apache.arrow.memory.util.MemoryUtil.<clinit>(MemoryUtil.java:138)
	... 32 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field long java.nio.Buffer.address accessible: module java.base does not "opens java.nio" to unnamed module @7bd804ed
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at net.snowflake.ingest.internal.apache.arrow.memory.util.MemoryUtil.<clinit>(MemoryUtil.java:84)
	... 32 more
```

Solution described here https://arrow.apache.org/docs/java/install.html , add `--add-opens=java.base/java.nio=ALL-UNNAMED`.

Second issue with snowflake jdbc:
```
Executing stage 'TASK_PUT' with class 'org.apache.kafka.connect.sink.SinkTask'. (org.apache.kafka.connect.runtime.errors.LogReporter:66)
Feb 10 21:37:20 prod-kafka-connect-03 connect-distributed[3378985]: net.snowflake.ingest.utils.SFException: Ingest client internal error: superclass access check failed: class net.snowflake.client.jdbc.internal.snowflake.common.util.TimeUtil$CCompatibleTimeZone (in unnamed module @0x29c76d75) cannot access class sun.util.calendar.ZoneInfo (in module java.base) because module java.base does not export sun.util.calendar to unnamed module @0x29c76d75.
```

Solution is to add `-–add-opens=java.base/sun.util.calendar=ALL-UNNAMED` option.

**Comment by sfc-gh-tzhang** [comment]
The latest release should work without the option, please give it a try!
