### ISSUE TITLE
Exception: Failed to get streaming ingest client after upgrade to 1.9.0

### ISSUE THREAD

**Issue by JonathonO** [snowflakedb/snowflake-kafka-connector#558]
@sfc-gh-japatel as requested, new issue ticket.

After upgrade from 1.8.3 to 1.9.0, an existing Snowflake Sink fails to start. Connector and Task restarts don't resolve the issue and throw the same exception.

We've checked and confirmed there are no older jars on the classpath.

Rolling back to 1.8.3 fixed the issue. Same connector config for 1.8.3 and 1.9.0. No changes.

```
at java.base/java.lang.Thread.run(Thread.java:833)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:256)
at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:201)
at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:204)
at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:235)
at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:329)
at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:473)
at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1220)
at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1240)
at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1276)
at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:552)
at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureActiveGroup(AbstractCoordinator.java:385)
at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.joinGroupIfNeeded(AbstractCoordinator.java:474)
at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.onJoinComplete(ConsumerCoordinator.java:466)
at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.onJoinComplete(ConsumerCoordinator.java:466)
at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.invokePartitionsAssigned(ConsumerCoordinator.java:317)
at org.apache.kafka.connect.runtime.WorkerSinkTask$HandleRebalance.onPartitionsAssigned(WorkerSinkTask.java:740)
at org.apache.kafka.connect.runtime.WorkerSinkTask.access$1200(WorkerSinkTask.java:73)
at org.apache.kafka.connect.runtime.WorkerSinkTask.openPartitions(WorkerSinkTask.java:644)
at com.snowflake.kafka.connector.SnowflakeSinkTask.open(SnowflakeSinkTask.java:286)
at java.base/java.lang.Iterable.forEach(Iterable.java:75)
at com.snowflake.kafka.connector.SnowflakeSinkTask.lambda$open$2(SnowflakeSinkTask.java:287)
at com.snowflake.kafka.connector.internal.streaming.SnowflakeSinkServiceV2.startTask(SnowflakeSinkServiceV2.java:144)
at com.snowflake.kafka.connector.internal.streaming.SnowflakeSinkServiceV2.createStreamingChannelForTopicPartition(SnowflakeSinkServiceV2.java:158)
at com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel.<init>(TopicPartitionChannel.java:207)
at com.snowflake.kafka.connector.internal.ingestsdk.StreamingClientManager.getValidClient(StreamingClientManager.java:165)
at com.snowflake.kafka.connector.internal.SnowflakeErrors.getException(SnowflakeErrors.java:295)
at com.snowflake.kafka.connector.internal.SnowflakeErrors.getException(SnowflakeErrors.java:327)
Message: call the manager to create the clients
Detail: The client must be initialized
Error Code: 3009
[2023-02-28 16:44:14,990] com.snowflake.kafka.connector.internal.SnowflakeKafkaConnectorException: [SF_KAFKA_CONNECTOR] Exception: Failed to get streaming ingest client
[2023-02-28 16:44:14,990] ERROR [destination_f35b|task-0] WorkerSinkTask{id=destination_f35b-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:208)
[2023-02-28 16:44:14,990] INFO [destination_f35b|task-0] [SF_KAFKA_CONNECTOR] Closing partitionChannel:null, partition:source_3ed9.audit.AuditLogs, topic:0 (com.snowflake.kafka.connector.internal.streaming.SnowflakeSinkServiceV2:107)
[2023-02-28 16:44:14,990] INFO [destination_f35b|task-0] [SF_KAFKA_CONNECTOR] Closing partitionChannel:null, partition:source_3ed9.audit.AuditFields, topic:9 (com.snowflake.kafka.connector.internal.streaming.SnowflakeSinkServiceV2:107)
[2023-02-28 16:44:14,990] INFO [destination_f35b|task-0] [SF_KAFKA_CONNECTOR] Closing partitionChannel:null, partition:source_3ed9.audit.AuditLogs, topic:1 (com.snowflake.kafka.connector.internal.streaming.SnowflakeSinkServiceV2:107)
[2023-02-28 16:44:14,990] INFO [destination_f35b|task-0] [SF_KAFKA_CONNECTOR] Closing partitionChannel:null, partition:source_3ed9.audit.AuditFields, topic:8 (com.snowflake.kafka.connector.internal.streaming.SnowflakeSinkServiceV2:107)
[2023-02-28 16:44:14,990] INFO [destination_f35b|task-0] [SF_KAFKA_CONNECTOR] Closing partitionChannel:null, partition:source_3ed9.audit.AuditLogs, topic:4 (com.snowflake.kafka.connector.internal.streaming.SnowflakeSinkServiceV2:107)
[2023-02-28 16:44:14,990] INFO [destination_f35b|task-0] [SF_KAFKA_CONNECTOR] Closing partitionChannel:null, partition:source_3ed9.audit.AuditLogs, topic:5 (com.snowflake.kafka.connector.internal.streaming.SnowflakeSinkServiceV2:107)
[2023-02-28 16:44:14,990] INFO [destination_f35b|task-0] [SF_KAFKA_CONNECTOR] Closing partitionChannel:null, partition:source_3ed9.audit.AuditLogs, topic:2 (com.snowflake.kafka.connector.internal.streaming.SnowflakeSinkServiceV2:107)
[2023-02-28 16:44:14,990] INFO [destination_f35b|task-0] [SF_KAFKA_CONNECTOR] Closing partitionChannel:null, partition:source_3ed9.audit.AuditLogs, topic:3 (com.snowflake.kafka.connector.internal.streaming.SnowflakeSinkServiceV2:107)
[2023-02-28 16:44:14,990] INFO [destination_f35b|task-0] [SF_KAFKA_CONNECTOR] Closing partitionChannel:null, partition:source_3ed9.audit.AuditFields, topic:1 (com.snowflake.kafka.connector.internal.streaming.SnowflakeSinkServiceV2:107)
[2023-02-28 16:44:14,990] INFO [destination_f35b|task-0] [SF_KAFKA_CONNECTOR] Closing partitionChannel:null, partition:source_3ed9.audit.AuditFields, topic:0 (com.snowflake.kafka.connector.internal.streaming.SnowflakeSinkServiceV2:107)
[2023-02-28 16:44:14,990] INFO [destination_f35b|task-0] [SF_KAFKA_CONNECTOR] Closing partitionChannel:null, partition:source_3ed9.audit.AuditFields, topic:3 (com.snowflake.kafka.connector.internal.streaming.SnowflakeSinkServiceV2:107)
[2023-02-28 16:44:14,990] INFO [destination_f35b|task-0] [SF_KAFKA_CONNECTOR] Closing partitionChannel:null, partition:source_3ed9.audit.AuditFields, topic:2 (com.snowflake.kafka.connector.internal.streaming.SnowflakeSinkServiceV2:107)
[2023-02-28 16:44:14,990] INFO [destination_f35b|task-0] [SF_KAFKA_CONNECTOR] Closing partitionChannel:null, partition:source_3ed9.audit.AuditFields, topic:5 (com.snowflake.kafka.connector.internal.streaming.SnowflakeSinkServiceV2:107)
[2023-02-28 16:44:14,990] INFO [destination_f35b|task-0] [SF_KAFKA_CONNECTOR] Closing partitionChannel:null, partition:source_3ed9.audit.AuditFields, topic:4 (com.snowflake.kafka.connector.internal.streaming.SnowflakeSinkServiceV2:107)
[2023-02-28 16:44:14,990] INFO [destination_f35b|task-0] [SF_KAFKA_CONNECTOR] Closing partitionChannel:null, partition:source_3ed9.audit.AuditFields, topic:7 (com.snowflake.kafka.connector.internal.streaming.SnowflakeSinkServiceV2:107)
[2023-02-28 16:44:14,990] INFO [destination_f35b|task-0] [SF_KAFKA_CONNECTOR] Closing partitionChannel:null, partition:source_3ed9.audit.AuditFields, topic:6 (com.snowflake.kafka.connector.internal.streaming.SnowflakeSinkServiceV2:107)
[2023-02-28 16:44:14,990] INFO [destination_f35b|task-0] [SF_KAFKA_CONNECTOR] Closing partitionChannel:null, partition:source_3ed9.audit.AuditLogs, topic:8 (com.snowflake.kafka.connector.internal.streaming.SnowflakeSinkServiceV2:107)
[2023-02-28 16:44:14,990] INFO [destination_f35b|task-0] [SF_KAFKA_CONNECTOR] Closing partitionChannel:null, partition:source_3ed9.audit.AuditLogs, topic:9 (com.snowflake.kafka.connector.internal.streaming.SnowflakeSinkServiceV2:107)
[2023-02-28 16:44:14,990] INFO [destination_f35b|task-0] [SF_KAFKA_CONNECTOR] Closing partitionChannel:null, partition:source_3ed9.audit.AuditLogs, topic:6 (com.snowflake.kafka.connector.internal.streaming.SnowflakeSinkServiceV2:107)
[2023-02-28 16:44:14,990] INFO [destination_f35b|task-0] [SF_KAFKA_CONNECTOR] Closing partitionChannel:null, partition:source_3ed9.audit.AuditLogs, topic:7 (com.snowflake.kafka.connector.internal.streaming.SnowflakeSinkServiceV2:107)
[2023-02-28 16:44:14,989] WARN [destination_f35b|task-0] [SF_KAFKA_CONNECTOR] [SfTask[ID:0.1, #-1]] no partition is assigned (com.snowflake.kafka.connector.SnowflakeSinkTask:143)
[2023-02-28 16:44:14,856] INFO [destination_f35b|task-0] Given logger tag set to: 'SfTask[ID:0.1, #-1]' (com.snowflake.kafka.connector.SnowflakeSinkTask:91)
"[2023-02-28 16:44:11,549] INFO [destination_f35b|worker] [SF_INGEST] Client created, name=KC_CLIENT_destination_f35b_1744944012_3, account=*******-********. isTestMode=false, parameters=ParameterProvider{parameterMap={streaming_ingest_client_sdk_insert_throttle_threshold_in_percentage=10, enable_snowpipe_streaming_jmx_metrics=false, blob_format_version=THREE, max_memory_limit_in_bytes=-1, blob_upload_max_retry_count=24, io_time_cpu_ratio=2, streaming_ingest_client_sdk_buffer_flush_interval_in_millis=1000, enable_parquet_internal_buffering=false, streaming_ingest_client_sdk_buffer_flush_check_interval_in_millis=100, streaming_ingest_client_sdk_insert_throttle_interval_in_millis=1000}} (net.snowflake.ingest.streaming.internal.SnowflakeStreamingIngestClientInternal:58)
"[2023-02-28 16:44:11,549] INFO [destination_f35b|worker] [SF_INGEST] Create 12 threads for build/upload blobs for client=KC_CLIENT_destination_f35b_1744944012_3, total available processors=4 (net.snowflake.ingest.streaming.internal.FlushService:58)
[2023-02-28 16:44:11,843] INFO [destination_f35b|task-0] [SF_KAFKA_CONNECTOR] com.snowflake.kafka.connector.internal.SnowflakeSinkService created (com.snowflake.kafka.connector.internal.SnowflakeSinkServiceFactory$SnowflakeSinkServiceBuilder:107)
[2023-02-28 16:44:11,843] INFO [destination_f35b|task-0] [SF_KAFKA_CONNECTOR] Config Delivery Guarantee type exactly_once. (com.snowflake.kafka.connector.internal.SnowflakeSinkServiceFactory$SnowflakeSinkServiceBuilder:107)
[2023-02-28 16:44:11,843] INFO [destination_f35b|task-0] [SF_KAFKA_CONNECTOR] Config JMX value true. (true = Enabled, false = Disabled) (com.snowflake.kafka.connector.internal.SnowflakeSinkServiceFactory$SnowflakeSinkServiceBuilder:107)
[2023-02-28 16:44:11,843] INFO [destination_f35b|task-0] [SF_KAFKA_CONNECTOR] Config Behavior on null value is ignore (com.snowflake.kafka.connector.internal.SnowflakeSinkServiceFactory$SnowflakeSinkServiceBuilder:107)
[2023-02-28 16:44:11,843] INFO [destination_f35b|task-0] [SF_KAFKA_CONNECTOR] metadata config map is {createtimeFlag: true, topicFlag: true, offsetAndPartitionFlag: true, allFlag: true} (com.snowflake.kafka.connector.internal.SnowflakeSinkServiceFactory$SnowflakeSinkServiceBuilder:107)
[2023-02-28 16:44:11,843] INFO [destination_f35b|task-0] [SF_KAFKA_CONNECTOR] set topic 2 table map
[2023-02-28 16:44:11,843] INFO [destination_f35b|task-0] [SF_KAFKA_CONNECTOR] flush time is limited to 120 (com.snowflake.kafka.connector.internal.SnowflakeSinkServiceFactory$SnowflakeSinkServiceBuilder:107)
[2023-02-28 16:44:11,843] INFO [destination_f35b|task-0] [SF_KAFKA_CONNECTOR] set flush time to 120 seconds (com.snowflake.kafka.connector.internal.streaming.SnowflakeSinkServiceV2:107)
[2023-02-28 16:44:11,843] INFO [destination_f35b|task-0] [SF_KAFKA_CONNECTOR] record number is limited to 10000 (com.snowflake.kafka.connector.internal.SnowflakeSinkServiceFactory$SnowflakeSinkServiceBuilder:107)
[2023-02-28 16:44:11,843] INFO [destination_f35b|task-0] [SF_KAFKA_CONNECTOR] Set number of records for buffer threshold to 10000 (com.snowflake.kafka.connector.internal.streaming.SnowflakeSinkServiceV2:107)
[2023-02-28 16:44:11,843] INFO [destination_f35b|task-0] [SF_KAFKA_CONNECTOR] file size is limited to 5000000 (com.snowflake.kafka.connector.internal.SnowflakeSinkServiceFactory$SnowflakeSinkServiceBuilder:107)
[2023-02-28 16:44:11,843] INFO [destination_f35b|task-0] [SF_KAFKA_CONNECTOR] set buffer size limitation to 5000000 bytes (com.snowflake.kafka.connector.internal.streaming.SnowflakeSinkServiceV2:107)
[2023-02-28 16:44:11,843] INFO [destination_f35b|task-0] [SF_KAFKA_CONNECTOR] com.snowflake.kafka.connector.internal.streaming.SnowflakeSinkServiceV2 created (com.snowflake.kafka.connector.internal.SnowflakeSinkServiceFactory$SnowflakeSinkServiceBuilder:107)
[2023-02-28 16:44:11,843] INFO [destination_f35b|task-0] [SF_KAFKA_CONNECTOR] Created loggerHandler for class: 'com.snowflake.kafka.connector.records.RecordService' without a Kafka Connect global instance id. (com.snowflake.kafka.connector.internal.LoggerHandler:64)
[2023-02-28 16:44:11,843] INFO [destination_f35b|task-0] [SF_KAFKA_CONNECTOR] Created loggerHandler for class: 'com.snowflake.kafka.connector.internal.SnowflakeSinkServiceFactory$SnowflakeSinkServiceBuilder' without a Kafka Connect global instance id. (com.snowflake.kafka.connector.internal.LoggerHandler:64)
[2023-02-28 16:44:11,843] INFO [destination_f35b|task-0] [SF_KAFKA_CONNECTOR] initialized the snowflake connection (com.snowflake.kafka.connector.internal.SnowflakeConnectionServiceV1:107)
[2023-02-28 16:44:11,843] INFO [destination_f35b|task-0] [SF_KAFKA_CONNECTOR] Created loggerHandler for class: 'com.snowflake.kafka.connector.internal.telemetry.SnowflakeTelemetryServiceV1' without a Kafka Connect global instance id. (com.snowflake.kafka.connector.internal.LoggerHandler:64)
[2023-02-28 16:44:11,843] INFO [destination_f35b|task-0] [SF_KAFKA_CONNECTOR] Created loggerHandler for class: 'com.snowflake.kafka.connector.internal.telemetry.SnowflakeTelemetryServiceFactory$SnowflakeTelemetryServiceBuilder' without a Kafka Connect global instance id. (com.snowflake.kafka.connector.internal.LoggerHandler:64)
[2023-02-28 16:44:11,843] INFO [destination_f35b|task-0] [SF_KAFKA_CONNECTOR] Created loggerHandler for class: 'com.snowflake.kafka.connector.internal.SnowflakeInternalStage' without a Kafka Connect global instance id. (com.snowflake.kafka.connector.internal.LoggerHandler:64)
[2023-02-28 16:44:11,594] INFO [destination_f35b|task-0] [SF_KAFKA_CONNECTOR] Establishing a JDBC connection with url:jdbc:snowflake://*******-********.snowflakecomputing.com:443 (com.snowflake.kafka.connector.internal.SnowflakeConnectionServiceV1:107)
[2023-02-28 16:44:11,594] INFO [destination_f35b|task-0] [SF_KAFKA_CONNECTOR] Created loggerHandler for class: 'com.snowflake.kafka.connector.internal.SnowflakeConnectionServiceV1' without a Kafka Connect global instance id. (com.snowflake.kafka.connector.internal.LoggerHandler:64)
[2023-02-28 16:44:11,584] INFO [destination_f35b|task-0] [SF_KAFKA_CONNECTOR] Created loggerHandler for class: 'com.snowflake.kafka.connector.internal.SnowflakeURL' without a Kafka Connect global instance id. (com.snowflake.kafka.connector.internal.LoggerHandler:64)
[2023-02-28 16:44:11,584] INFO [destination_f35b|task-0] [SF_KAFKA_CONNECTOR] Created loggerHandler for class: 'com.snowflake.kafka.connector.internal.SnowflakeConnectionServiceFactory$SnowflakeConnectionServiceBuilder' without a Kafka Connect global instance id. (com.snowflake.kafka.connector.internal.LoggerHandler:64)
[2023-02-28 16:44:11,584] INFO [destination_f35b|task-0] Given logger tag set to: 'SfTask[ID:0.0, #-1]' (com.snowflake.kafka.connector.SnowflakeSinkTask:91)
[2023-02-28 16:44:11,584] INFO [destination_f35b|task-0] [SF_KAFKA_CONNECTOR] Defining SnowflakeSinkTask instance tag to SfTask[ID:{taskId}.{taskOpenCount}, #{totalTaskCreationCount}], where taskId is pulled from the config, taskOpenCount is the number of times this task has been opened and totalTaskCreationCount is the total number of tasks created during this run of Snowflake Kafka Connector (com.snowflake.kafka.connector.SnowflakeSinkTask:107)
...
[2023-02-28 16:44:11,564] INFO [destination_f35b|task-0] [SF_KAFKA_CONNECTOR] Created loggerHandler for class: 'com.snowflake.kafka.connector.SnowflakeSinkTask' without a Kafka Connect global instance id. (com.snowflake.kafka.connector.internal.LoggerHandler:64)
[2023-02-28 16:44:11,154] INFO [destination_f35b|worker] Creating a RequestBuilder with arguments : Account : *******-********, User : **************, Scheme : https, Host : *******-********.snowflakecomputing.com, Port : 443, userAgentSuffix: null (net.snowflake.ingest.connection.RequestBuilder:290)
[2023-02-28 16:44:11,154] INFO [destination_f35b|worker] Created new JWT (net.snowflake.ingest.connection.SecurityManager:191)
[2023-02-28 16:44:11,152] INFO [destination_f35b|worker] Creating Token with issuer *******-********.**************.SHA256:********************************* (net.snowflake.ingest.connection.SecurityManager:164)
[2023-02-28 16:44:11,152] INFO [destination_f35b|worker] Creating Token with subject *******-********.************** (net.snowflake.ingest.connection.SecurityManager:159)
[2023-02-28 16:44:11,147] INFO [destination_f35b|worker] [SF_KAFKA_CONNECTOR] [KC:1744944012] Creating Streaming Client: KC_CLIENT_destination_f35b_1744944012_3 (com.snowflake.kafka.connector.internal.ingestsdk.KcStreamingIngestClient:107)
[2023-02-28 16:44:11,147] INFO [destination_f35b|worker] [SF_KAFKA_CONNECTOR] Created loggerHandler for class: 'com.snowflake.kafka.connector.internal.ingestsdk.KcStreamingIngestClient' with Kafka Connect global instance id: '1744944012' (com.snowflake.kafka.connector.internal.LoggerHandler:64)
[2023-02-28 16:44:11,146] INFO [destination_f35b|worker] [SF_KAFKA_CONNECTOR] [KC:1744944012] Creating 1 clients for 1 tasks with max 1 tasks per client using Optional.empty file format (com.snowflake.kafka.connector.internal.ingestsdk.StreamingClientManager:107)
[2023-02-28 16:44:11,145] INFO [destination_f35b|worker] [SF_KAFKA_CONNECTOR] [KC:1744944012] initialized the snowflake connection (com.snowflake.kafka.connector.internal.SnowflakeConnectionServiceV1:107)
[2023-02-28 16:44:11,145] INFO [destination_f35b|worker] [SF_KAFKA_CONNECTOR] Created loggerHandler for class: 'com.snowflake.kafka.connector.internal.telemetry.SnowflakeTelemetryServiceV1' with Kafka Connect global instance id: '1744944012' (com.snowflake.kafka.connector.internal.LoggerHandler:64)
[2023-02-28 16:44:11,145] INFO [destination_f35b|worker] [SF_KAFKA_CONNECTOR] Created loggerHandler for class: 'com.snowflake.kafka.connector.internal.telemetry.SnowflakeTelemetryServiceFactory$SnowflakeTelemetryServiceBuilder' with Kafka Connect global instance id: '1744944012' (com.snowflake.kafka.connector.internal.LoggerHandler:64)
[2023-02-28 16:44:11,145] INFO [destination_f35b|worker] [SF_KAFKA_CONNECTOR] Created loggerHandler for class: 'com.snowflake.kafka.connector.internal.SnowflakeInternalStage' with Kafka Connect global instance id: '1744944012' (com.snowflake.kafka.connector.internal.LoggerHandler:64)
[2023-02-28 16:44:11,024] INFO [destination_f35b|worker] [SF_KAFKA_CONNECTOR] [KC:1744944012] Establishing a JDBC connection with url:jdbc:snowflake://*******-********.snowflakecomputing.com:443 (com.snowflake.kafka.connector.internal.SnowflakeConnectionServiceV1:107)
[2023-02-28 16:44:11,024] INFO [destination_f35b|worker] [SF_KAFKA_CONNECTOR] Created loggerHandler for class: 'com.snowflake.kafka.connector.internal.SnowflakeConnectionServiceV1' with Kafka Connect global instance id: '1744944012' (com.snowflake.kafka.connector.internal.LoggerHandler:64)
[2023-02-28 16:44:11,017] INFO [destination_f35b|worker] [SF_KAFKA_CONNECTOR] Created loggerHandler for class: 'com.snowflake.kafka.connector.internal.SnowflakeURL' with Kafka Connect global instance id: '1744944012' (com.snowflake.kafka.connector.internal.LoggerHandler:64)
[2023-02-28 16:44:11,017] INFO [destination_f35b|worker] [SF_KAFKA_CONNECTOR] Created loggerHandler for class: 'com.snowflake.kafka.connector.internal.SnowflakeConnectionServiceFactory$SnowflakeConnectionServiceBuilder' with Kafka Connect global instance id: '1744944012' (com.snowflake.kafka.connector.internal.LoggerHandler:64)
[2023-02-28 16:44:11,017] INFO [destination_f35b|worker] [SF_KAFKA_CONNECTOR] [KC:1744944012] buffer.flush.time set to default 120 seconds (com.snowflake.kafka.connector.SnowflakeSinkConnectorConfig:107)
[2023-02-28 16:44:11,017] INFO [destination_f35b|worker] [SF_KAFKA_CONNECTOR] [KC:1744944012] buffer.size.bytes set to default 5000000 seconds (com.snowflake.kafka.connector.SnowflakeSinkConnectorConfig:107)
[2023-02-28 16:44:11,017] INFO [destination_f35b|worker] [SF_KAFKA_CONNECTOR] [KC:1744944012] buffer.count.records set to default 10000 seconds (com.snowflake.kafka.connector.SnowflakeSinkConnectorConfig:107)
[2023-02-28 16:44:11,017] INFO [destination_f35b|worker] Set Kafka Connect global instance id tag for logging: '1744944012' (com.snowflake.kafka.connector.internal.LoggerHandler:43)
[2023-02-28 16:44:11,017] INFO [destination_f35b|worker] [SF_KAFKA_CONNECTOR] [KC:1972531304] SnowflakeSinkConnector:start (com.snowflake.kafka.connector.SnowflakeSinkConnector:107)
[2023-02-28 16:44:10,382] INFO [destination_f35b|worker] [SF_KAFKA_CONNECTOR] [KC:1972531304] Current Snowflake Kafka Connector Version: 1.9.0 (com.snowflake.kafka.connector.Utils:107)
[2023-02-28 16:44:10,382] INFO [destination_f35b|worker] [SF_KAFKA_CONNECTOR] [KC:1972531304] Setting task creation count to 0 for logging (com.snowflake.kafka.connector.SnowflakeSinkTask_STATIC:107)
[2023-02-28 16:44:10,379] INFO [destination_f35b|worker] [SF_KAFKA_CONNECTOR] [KC:1972531304] SnowflakeSinkConnector:stop (com.snowflake.kafka.connector.SnowflakeSinkConnector:107)
[2023-02-28 16:44:10,309] INFO [destination_f35b|worker] type=TIMER, name=latency.upload, count=0, min=0.0, max=0.0, mean=0.0, stddev=0.0, p50=0.0, p75=0.0, p95=0.0, p98=0.0, p99=0.0, p999=0.0, m1_rate=0.0, m5_rate=0.0, m15_rate=0.0, mean_rate=0.0, rate_unit=events/second, duration_unit=milliseconds (net.snowflake.ingest.streaming.internal.SnowflakeStreamingIngestClientInternal:95)
[2023-02-28 16:44:10,309] INFO [destination_f35b|worker] type=TIMER, name=latency.register, count=0, min=0.0, max=0.0, mean=0.0, stddev=0.0, p50=0.0, p75=0.0, p95=0.0, p98=0.0, p99=0.0, p999=0.0, m1_rate=0.0, m5_rate=0.0, m15_rate=0.0, mean_rate=0.0, rate_unit=events/second, duration_unit=milliseconds (net.snowflake.ingest.streaming.internal.SnowflakeStreamingIngestClientInternal:95)
[2023-02-28 16:44:10,309] INFO [destination_f35b|worker] type=TIMER, name=latency.flush, count=0, min=0.0, max=0.0, mean=0.0, stddev=0.0, p50=0.0, p75=0.0, p95=0.0, p98=0.0, p99=0.0, p999=0.0, m1_rate=0.0, m5_rate=0.0, m15_rate=0.0, mean_rate=0.0, rate_unit=events/second, duration_unit=milliseconds (net.snowflake.ingest.streaming.internal.SnowflakeStreamingIngestClientInternal:95)
[2023-02-28 16:44:10,309] INFO [destination_f35b|worker] type=TIMER, name=latency.build, count=0, min=0.0, max=0.0, mean=0.0, stddev=0.0, p50=0.0, p75=0.0, p95=0.0, p98=0.0, p99=0.0, p999=0.0, m1_rate=0.0, m5_rate=0.0, m15_rate=0.0, mean_rate=0.0, rate_unit=events/second, duration_unit=milliseconds (net.snowflake.ingest.streaming.internal.SnowflakeStreamingIngestClientInternal:95)
[2023-02-28 16:44:10,309] INFO [destination_f35b|worker] type=METER, name=throughput.upload, count=0, m1_rate=0.0, m5_rate=0.0, m15_rate=0.0, mean_rate=0.0, rate_unit=events/second (net.snowflake.ingest.streaming.internal.SnowflakeStreamingIngestClientInternal:95)
[2023-02-28 16:44:10,309] INFO [destination_f35b|worker] type=METER, name=throughput.input, count=0, m1_rate=0.0, m5_rate=0.0, m15_rate=0.0, mean_rate=0.0, rate_unit=events/second (net.snowflake.ingest.streaming.internal.SnowflakeStreamingIngestClientInternal:95)
[2023-02-28 16:44:10,309] INFO [destination_f35b|worker] type=HISTOGRAM, name=cpu.usage.histogram, count=8604, min=0, max=53, mean=2.743655375059742, stddev=6.054357036059675, p50=2.0, p75=2.0, p95=12.0, p98=25.0, p99=30.0, p999=53.0 (net.snowflake.ingest.streaming.internal.SnowflakeStreamingIngestClientInternal:95)
[2023-02-28 16:44:10,308] INFO [destination_f35b|worker] type=HISTOGRAM, name=blob.size.histogram, count=0, min=0, max=0, mean=0.0, stddev=0.0, p50=0.0, p75=0.0, p95=0.0, p98=0.0, p99=0.0, p999=0.0 (net.snowflake.ingest.streaming.internal.SnowflakeStreamingIngestClientInternal:95)
[2023-02-28 16:44:10,308] INFO [destination_f35b|worker] type=HISTOGRAM, name=blob.row.count.histogram, count=0, min=0, max=0, mean=0.0, stddev=0.0, p50=0.0, p75=0.0, p95=0.0, p98=0.0, p99=0.0, p999=0.0 (net.snowflake.ingest.streaming.internal.SnowflakeStreamingIngestClientInternal:95)
[2023-02-28 16:44:10,307] INFO [destination_f35b|worker] [SF_KAFKA_CONNECTOR] [KC:1972531304] Closing Streaming Client:KC_CLIENT_destination_f35b_1972531304_2 (com.snowflake.kafka.connector.internal.ingestsdk.KcStreamingIngestClient:107)
[2023-02-28 16:44:10,307] INFO [destination_f35b|worker] [SF_KAFKA_CONNECTOR] [KC:1972531304] Closing all clients (com.snowflake.kafka.connector.internal.ingestsdk.StreamingClientManager:107)
[2023-02-28 16:44:10,307] INFO [destination_f35b|worker] [SF_KAFKA_CONNECTOR] [KC:1972531304] Setting task creation count to -1 for logging (com.snowflake.kafka.connector.SnowflakeSinkTask_STATIC:107)
[2023-02-28 16:44:10,299] INFO [SF_KAFKA_CONNECTOR] [KC:1972531304] Validated config with no error (com.snowflake.kafka.connector.SnowflakeSinkConnector:107)
[2023-02-28 16:44:10,299] INFO [SF_KAFKA_CONNECTOR] [KC:1972531304] schema *********** exists (com.snowflake.kafka.connector.internal.SnowflakeConnectionServiceV1:107)
[2023-02-28 16:44:10,234] INFO [SF_KAFKA_CONNECTOR] [KC:1972531304] database *********** exists (com.snowflake.kafka.connector.internal.SnowflakeConnectionServiceV1:107)
[2023-02-28 16:44:10,171] INFO [SF_KAFKA_CONNECTOR] [KC:1972531304] initialized the snowflake connection (com.snowflake.kafka.connector.internal.SnowflakeConnectionServiceV1:107)
[2023-02-28 16:44:10,171] INFO [SF_KAFKA_CONNECTOR] Created loggerHandler for class: 'com.snowflake.kafka.connector.internal.telemetry.SnowflakeTelemetryServiceV1' with Kafka Connect global instance id: '1972531304' (com.snowflake.kafka.connector.internal.LoggerHandler:64)
[2023-02-28 16:44:10,171] INFO [SF_KAFKA_CONNECTOR] Created loggerHandler for class: 'com.snowflake.kafka.connector.internal.telemetry.SnowflakeTelemetryServiceFactory$SnowflakeTelemetryServiceBuilder' with Kafka Connect global instance id: '1972531304' (com.snowflake.kafka.connector.internal.LoggerHandler:64)
[2023-02-28 16:44:10,171] INFO [SF_KAFKA_CONNECTOR] Created loggerHandler for class: 'com.snowflake.kafka.connector.internal.SnowflakeInternalStage' with Kafka Connect global instance id: '1972531304' (com.snowflake.kafka.connector.internal.LoggerHandler:64)
[2023-02-28 16:44:09,932] INFO [SF_KAFKA_CONNECTOR] [KC:1972531304] Establishing a JDBC connection with url:jdbc:snowflake://*******-********.snowflakecomputing.com:443 (com.snowflake.kafka.connector.internal.SnowflakeConnectionServiceV1:107)
[2023-02-28 16:44:09,932] INFO [SF_KAFKA_CONNECTOR] Created loggerHandler for class: 'com.snowflake.kafka.connector.internal.SnowflakeConnectionServiceV1' with Kafka Connect global instance id: '1972531304' (com.snowflake.kafka.connector.internal.LoggerHandler:64)
[2023-02-28 16:44:09,925] INFO [SF_KAFKA_CONNECTOR] Created loggerHandler for class: 'com.snowflake.kafka.connector.internal.SnowflakeURL' with Kafka Connect global instance id: '1972531304' (com.snowflake.kafka.connector.internal.LoggerHandler:64)
[2023-02-28 16:44:09,925] INFO [SF_KAFKA_CONNECTOR] Created loggerHandler for class: 'com.snowflake.kafka.connector.internal.SnowflakeConnectionServiceFactory$SnowflakeConnectionServiceBuilder' with Kafka Connect global instance id: '1972531304' (com.snowflake.kafka.connector.internal.LoggerHandler:64)
```

**Comment by sfc-gh-japatel** [comment]
#555 should fix this too

**Comment by sfc-gh-japatel** [comment]
Hi, 1.9.1 is released, can you try and lets us know?

**Comment by JonathonO** [comment]
@sfc-gh-japatel Yes, of course! Deploying today and will monitor.

**Comment by JonathonO** [comment]
@sfc-gh-japatel Seems around 3am~ GMT this morning, 500 status codes being thrown constantly across 2 Snowflake Sinks for 2 separate Snowflake orgs and accounts. Data's not being ingested. Service outage on Snowflake side?

```
[2023-03-03 08:47:10,614] INFO [destination_63ea97792253adec948911fa|task-0] Sleep time in millisecond: 3000, retryCount: 5, total retry duration: 13s / 120s (net.snowflake.ingest.utils.HttpUtil:238)
[2023-03-03 08:46:31,368] INFO In retryRequest for service unavailability with statusCode:500 and uri:/v1/streaming/channels/status/ (net.snowflake.ingest.utils.HttpUtil:234)
```
