### ISSUE TITLE
Commit offset error

### ISSUE THREAD

**Issue by vertigokidd** [snowflakedb/snowflake-kafka-connector#59]
I'm running into an issue when trying to initialize the connector to read from a Kafka topic (running on 2.3.0). This is Stack trace below:

```
[SF_KAFKA_CONNECTOR] Creating new table OS_KAFKA_TEST. (com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1) [task-thread-KAFKA_SF_TEST-0]
2019-10-16 18:05:14,984 WARN WorkerSinkTask{id=KAFKA_SF_TEST-0} Offset commit failed during close (org.apache.kafka.connect.runtime.WorkerSinkTask) [task-thread-KAFKA_SF_TEST-0]
2019-10-16 18:05:14,984 ERROR WorkerSinkTask{id=KAFKA_SF_TEST-0} Commit of offsets threw an unexpected exception for sequence number 1: null (org.apache.kafka.connect.runtime.WorkerSinkTask) [task-thread-KAFKA_SF_TEST-0]
java.lang.NullPointerException
	at com.snowflake.kafka.connector.SnowflakeSinkTask.lambda$preCommit$1(SnowflakeSinkTask.java:186)
	at java.util.HashMap.forEach(HashMap.java:1289)
	at com.snowflake.kafka.connector.SnowflakeSinkTask.preCommit(SnowflakeSinkTask.java:183)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.commitOffsets(WorkerSinkTask.java:378)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.closePartitions(WorkerSinkTask.java:590)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:196)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-10-16 18:05:14,984 ERROR WorkerSinkTask{id=KAFKA_SF_TEST-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask) [task-thread-KAFKA_SF_TEST-0]
java.lang.NullPointerException
	at com.snowflake.kafka.connector.SnowflakeSinkTask.close(SnowflakeSinkTask.java:153)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.commitOffsets(WorkerSinkTask.java:396)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.closePartitions(WorkerSinkTask.java:590)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:196)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-10-16 18:05:14,984 ERROR WorkerSinkTask{id=KAFKA_SF_TEST-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask) [task-thread-KAFKA_SF_TEST-0]
```

**Comment by binglihub** [comment]
Could you provide the full log, or a scenario to reproduce this issue? Thanks

**Comment by vertigokidd** [comment]
@binglihub Here is the scenario:
- Using Strimzi operator, deploy a Kafka cluster to an Openshift environment.
- Create a Kafka topic called `test-topic` and publish messages to it using a Python script.
- Deploy a Kafka Connect container with the snowflake-kafka-connector installed.
- Create a connector posting a configuration to the Kafka Connect API.

Here is more of the log as well:
```
[SF_KAFKA_CONNECTOR] initialized the snowflake connection (com.snowflake.kafka.connector.internal.SnowflakeConnectionServiceV1) [task-thread-KAFKA_SF_TEST-0]
2019-10-16 19:57:24,895 INFO WorkerSinkTask{id=KAFKA_SF_TEST-0} Sink task finished initialization and start (org.apache.kafka.connect.runtime.WorkerSinkTask) [task-thread-KAFKA_SF_TEST-0]
2019-10-16 19:57:24,901 INFO 
[SF_KAFKA_CONNECTOR] initialized the snowflake connection (com.snowflake.kafka.connector.internal.SnowflakeConnectionServiceV1) [pool-5-thread-1]
2019-10-16 19:57:24,954 INFO [Consumer clientId=connector-consumer-KAFKA_SF_TEST-0, groupId=connect-KAFKA_SF_TEST] Cluster ID: zl4gR1QORzi3O99qtLFXEA (org.apache.kafka.clients.Metadata) [task-thread-KAFKA_SF_TEST-0]
2019-10-16 19:57:24,955 INFO [Consumer clientId=connector-consumer-KAFKA_SF_TEST-0, groupId=connect-KAFKA_SF_TEST] Discovered group coordinator gk-cluster-kafka-1.gk-cluster-kafka-brokers.sandbox-sol-arch.svc.cluster.local:9093 (id: 2147483646 rack: null) (org.apache.kafka.clients.consumer.internals.AbstractCoordinator) [task-thread-KAFKA_SF_TEST-0]
2019-10-16 19:57:24,958 INFO [Consumer clientId=connector-consumer-KAFKA_SF_TEST-0, groupId=connect-KAFKA_SF_TEST] Revoking previously assigned partitions [] (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator) [task-thread-KAFKA_SF_TEST-0]
2019-10-16 19:57:24,958 INFO [Consumer clientId=connector-consumer-KAFKA_SF_TEST-0, groupId=connect-KAFKA_SF_TEST] (Re-)joining group (org.apache.kafka.clients.consumer.internals.AbstractCoordinator) [task-thread-KAFKA_SF_TEST-0]
2019-10-16 19:57:24,973 INFO Finished creating connector KAFKA_SF_TEST (org.apache.kafka.connect.runtime.Worker) [pool-5-thread-1]
2019-10-16 19:57:24,974 INFO SinkConnectorConfig values: 
	config.action.reload = restart
	connector.class = com.snowflake.kafka.connector.SnowflakeSinkConnector
	errors.deadletterqueue.context.headers.enable = false
	errors.deadletterqueue.topic.name = 
	errors.deadletterqueue.topic.replication.factor = 3
	errors.log.enable = false
	errors.log.include.messages = false
	errors.retry.delay.max.ms = 60000
	errors.retry.timeout = 0
	errors.tolerance = none
	header.converter = null
	key.converter = class org.apache.kafka.connect.storage.StringConverter
	name = KAFKA_SF_TEST
	tasks.max = 1
	topics = [test-topic]
	topics.regex = 
	transforms = []
	value.converter = class com.snowflake.kafka.connector.records.SnowflakeJsonConverter
 (org.apache.kafka.connect.runtime.SinkConnectorConfig) [pool-5-thread-1]
2019-10-16 19:57:24,975 INFO EnrichedConnectorConfig values: 
	config.action.reload = restart
	connector.class = com.snowflake.kafka.connector.SnowflakeSinkConnector
	errors.deadletterqueue.context.headers.enable = false
	errors.deadletterqueue.topic.name = 
	errors.deadletterqueue.topic.replication.factor = 3
	errors.log.enable = false
	errors.log.include.messages = false
	errors.retry.delay.max.ms = 60000
	errors.retry.timeout = 0
	errors.tolerance = none
	header.converter = null
	key.converter = class org.apache.kafka.connect.storage.StringConverter
	name = KAFKA_SF_TEST
	tasks.max = 1
	topics = [test-topic]
	topics.regex = 
	transforms = []
	value.converter = class com.snowflake.kafka.connector.records.SnowflakeJsonConverter
 (org.apache.kafka.connect.runtime.ConnectorConfig$EnrichedConnectorConfig) [pool-5-thread-1]
2019-10-16 19:57:24,975 INFO [Worker clientId=connect-1, groupId=connect-cluster] Finished starting connectors and tasks (org.apache.kafka.connect.runtime.distributed.DistributedHerder) [DistributedHerder-connect-1]
2019-10-16 19:57:24,984 INFO [Consumer clientId=connector-consumer-KAFKA_SF_TEST-0, groupId=connect-KAFKA_SF_TEST] (Re-)joining group (org.apache.kafka.clients.consumer.internals.AbstractCoordinator) [task-thread-KAFKA_SF_TEST-0]
2019-10-16 19:57:28,000 INFO [Consumer clientId=connector-consumer-KAFKA_SF_TEST-0, groupId=connect-KAFKA_SF_TEST] Successfully joined group with generation 1 (org.apache.kafka.clients.consumer.internals.AbstractCoordinator) [task-thread-KAFKA_SF_TEST-0]
2019-10-16 19:57:28,002 INFO [Consumer clientId=connector-consumer-KAFKA_SF_TEST-0, groupId=connect-KAFKA_SF_TEST] Setting newly assigned partitions: test-topic-0 (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator) [task-thread-KAFKA_SF_TEST-0]
2019-10-16 19:57:28,005 INFO [Consumer clientId=connector-consumer-KAFKA_SF_TEST-0, groupId=connect-KAFKA_SF_TEST] Found no committed offset for partition test-topic-0 (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator) [task-thread-KAFKA_SF_TEST-0]
2019-10-16 19:57:28,032 INFO [Consumer clientId=connector-consumer-KAFKA_SF_TEST-0, groupId=connect-KAFKA_SF_TEST] Resetting offset for partition test-topic-0 to offset 0. (org.apache.kafka.clients.consumer.internals.SubscriptionState) [task-thread-KAFKA_SF_TEST-0]
2019-10-16 19:57:28,034 INFO 
[SF_KAFKA_CONNECTOR] SnowflakeSinkTask:open, TopicPartitions: [test-topic-0] (com.snowflake.kafka.connector.SnowflakeSinkTask) [task-thread-KAFKA_SF_TEST-0]
2019-10-16 19:57:28,039 INFO 
[SF_KAFKA_CONNECTOR] com.snowflake.kafka.connector.internal.SnowflakeSinkServiceFactory$SnowflakeSinkServiceBuilder created (com.snowflake.kafka.connector.internal.SnowflakeSinkServiceFactory$SnowflakeSinkServiceBuilder) [task-thread-KAFKA_SF_TEST-0]
2019-10-16 19:57:28,040 INFO 
[SF_KAFKA_CONNECTOR] set file size limitation to 65536 bytes (com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1) [task-thread-KAFKA_SF_TEST-0]
2019-10-16 19:57:28,040 INFO 
[SF_KAFKA_CONNECTOR] file size is limited to 65536 (com.snowflake.kafka.connector.internal.SnowflakeSinkServiceFactory$SnowflakeSinkServiceBuilder) [task-thread-KAFKA_SF_TEST-0]
2019-10-16 19:57:28,040 INFO 
[SF_KAFKA_CONNECTOR] set number of record limitation to 100 (com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1) [task-thread-KAFKA_SF_TEST-0]
2019-10-16 19:57:28,040 INFO 
[SF_KAFKA_CONNECTOR] record number is limited to 100 (com.snowflake.kafka.connector.internal.SnowflakeSinkServiceFactory$SnowflakeSinkServiceBuilder) [task-thread-KAFKA_SF_TEST-0]
2019-10-16 19:57:28,040 INFO 
[SF_KAFKA_CONNECTOR] set flush time to 60 seconds (com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1) [task-thread-KAFKA_SF_TEST-0]
2019-10-16 19:57:28,040 INFO 
[SF_KAFKA_CONNECTOR] flush time is limited to 60 (com.snowflake.kafka.connector.internal.SnowflakeSinkServiceFactory$SnowflakeSinkServiceBuilder) [task-thread-KAFKA_SF_TEST-0]
[task-thread-KAFKA_SF_TEST-0] WARN net.snowflake.ingest.connection.RequestBuilder - Could not read version info: java.nio.file.FileSystemNotFoundException
[task-thread-KAFKA_SF_TEST-0] INFO net.snowflake.ingest.connection.SecurityManager - Creating Token with subject XXXX.OS_KAFKA_DEMO
[task-thread-KAFKA_SF_TEST-0] INFO net.snowflake.ingest.connection.SecurityManager - Creating Token with issuer XXXX.OS_KAFKA_DEMO.SHA256:pOz0vxRXta3OXLyIKLc0RrM6KyHhxlDJc+z4nKCYrJQ=
[task-thread-KAFKA_SF_TEST-0] INFO net.snowflake.ingest.connection.SecurityManager - Created new JWT  - XXXX
[task-thread-KAFKA_SF_TEST-0] INFO net.snowflake.ingest.connection.RequestBuilder - Creating a RequestBuilder with arguments : Account : XXXX, User : OS_KAFKA_DEMO, Scheme : https, Host : xxxx.us-east-1.snowflakecomputing.com, Port : 443
2019-10-16 19:57:28,324 INFO 
[SF_KAFKA_CONNECTOR] initialized the pipe connector for pipe EXAMPLE_DB_PROD.PUBLIC.SNOWFLAKE_KAFKA_CONNECTOR_KAFKA_SF_TEST_PIPE_OS_KAFKA_TEST_0 (com.snowflake.kafka.connector.internal.SnowflakeIngestionServiceV1) [task-thread-KAFKA_SF_TEST-0]
2019-10-16 19:57:28,853 INFO 
[SF_KAFKA_CONNECTOR] Creating new table OS_KAFKA_TEST. (com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1) [task-thread-KAFKA_SF_TEST-0]
2019-10-16 19:57:29,636 WARN WorkerSinkTask{id=KAFKA_SF_TEST-0} Offset commit failed during close (org.apache.kafka.connect.runtime.WorkerSinkTask) [task-thread-KAFKA_SF_TEST-0]
2019-10-16 19:57:29,637 ERROR WorkerSinkTask{id=KAFKA_SF_TEST-0} Commit of offsets threw an unexpected exception for sequence number 1: null (org.apache.kafka.connect.runtime.WorkerSinkTask) [task-thread-KAFKA_SF_TEST-0]
java.lang.NullPointerException
	at com.snowflake.kafka.connector.SnowflakeSinkTask.lambda$preCommit$1(SnowflakeSinkTask.java:186)
	at java.util.HashMap.forEach(HashMap.java:1289)
	at com.snowflake.kafka.connector.SnowflakeSinkTask.preCommit(SnowflakeSinkTask.java:183)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.commitOffsets(WorkerSinkTask.java:378)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.closePartitions(WorkerSinkTask.java:590)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:196)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-10-16 19:57:29,638 ERROR WorkerSinkTask{id=KAFKA_SF_TEST-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask) [task-thread-KAFKA_SF_TEST-0]
java.lang.NullPointerException
	at com.snowflake.kafka.connector.SnowflakeSinkTask.close(SnowflakeSinkTask.java:153)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.commitOffsets(WorkerSinkTask.java:396)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.closePartitions(WorkerSinkTask.java:590)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:196)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-10-16 19:57:29,638 ERROR WorkerSinkTask{id=KAFKA_SF_TEST-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask) [task-thread-KAFKA_SF_TEST-0]
```

**Comment by binglihub** [comment]
@vertigokidd could you try v0.5.2 to see if the issue fixed? thanks

**Comment by vertigokidd** [comment]
@binglihub Thanks for making the adjustment. I get a new error now:

`
2019-10-25 15:06:04,646 WARN WorkerSinkTask{id=KAFKA_SF_TEST-0} Offset commit failed during close (org.apache.kafka.connect.runtime.WorkerSinkTask) [task-thread-KAFKA_SF_TEST-0]
2019-10-25 15:06:04,647 ERROR WorkerSinkTask{id=KAFKA_SF_TEST-0} Commit of offsets threw an unexpected exception for sequence number 1: null (org.apache.kafka.connect.runtime.WorkerSinkTask) [task-thread-KAFKA_SF_TEST-0]
com.snowflake.kafka.connector.internal.SnowflakeKafkaConnectorException: 
[SF_KAFKA_CONNECTOR] Exception: Failed to put records
[SF_KAFKA_CONNECTOR] Error Code: 5014
[SF_KAFKA_CONNECTOR] Detail: SinkTask hasn't been initialized before calling PUT function
	at com.snowflake.kafka.connector.internal.SnowflakeErrors.getException(SnowflakeErrors.java:362)
	at com.snowflake.kafka.connector.internal.SnowflakeErrors.getException(SnowflakeErrors.java:321)
	at com.snowflake.kafka.connector.SnowflakeSinkTask.getSink(SnowflakeSinkTask.java:94)
	at com.snowflake.kafka.connector.SnowflakeSinkTask.lambda$preCommit$3(SnowflakeSinkTask.java:216)
	at java.util.HashMap.forEach(HashMap.java:1289)
	at com.snowflake.kafka.connector.SnowflakeSinkTask.preCommit(SnowflakeSinkTask.java:213)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.commitOffsets(WorkerSinkTask.java:378)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.closePartitions(WorkerSinkTask.java:590)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:196)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by vertigokidd** [comment]
Based on the new code and error handling you've written, I believe this might be a networking issue on my end. I'll close this for now and re-open if I discover otherwise. Thank you @binglihub

**Comment by xiekevin** [comment]
@vertigokidd Did you figure out the issue here? I'm running into the same error right now
