### ISSUE TITLE
Error message should be more specific

### ISSUE THREAD

**Issue by rmoff** [snowflakedb/snowflake-kafka-connector#61]
`Snowflake Kafka Connector Version: 0.5.1`

When running the connector I get the following error. It would be really useful if the connector could throw specific details about which configuration it is expecting / missing values / incorrect value. As it is the user just has to guess :) 

```
[SF_KAFKA_CONNECTOR] Exception: Invalid input connector configuration
[SF_KAFKA_CONNECTOR] Error Code: 0001
[SF_KAFKA_CONNECTOR] Detail: input kafka connector configuration is null, missing required values, or wrong input value
  at com.snowflake.kafka.connector.internal.SnowflakeErrors.getException(SnowflakeErrors.java:347)
  at com.snowflake.kafka.connector.internal.SnowflakeErrors.getException(SnowflakeErrors.java:306)
  at com.snowflake.kafka.connector.Utils.validateConfig(Utils.java:400)
  at com.snowflake.kafka.connector.SnowflakeSinkConnector.start(SnowflakeSinkConnector.java:131)
  at org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:111)
  at org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:136)
  at org.apache.kafka.connect.runtime.WorkerConnector.transitionTo(WorkerConnector.java:196)
  at org.apache.kafka.connect.runtime.Worker.startConnector(Worker.java:252)
  at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startConnector(DistributedHerder.java:1079)
  at org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1300(DistributedHerder.java:117)
  at org.apache.kafka.connect.runtime.distributed.DistributedHerder$15.call(DistributedHerder.java:1095)
  at org.apache.kafka.connect.runtime.distributed.DistributedHerder$15.call(DistributedHerder.java:1091)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)
```

**Comment by rmoff** [comment]
I realised that the actual error is further up in the log: 

```
[SF_KAFKA_CONNECTOR] name is empty or invalid. It should match Snowflake object identifier syntax. Please see the documentation. (com.snowflake.kafka.connector.Utils:246)
```

Since my connector is called `sink-snowflake-01` this doesn't match the [validation check](https://github.com/snowflakedb/snowflake-kafka-connector/blob/1d4469ea4fd2a8f16f7b935a9f62f7362b2f605d/src/main/java/com/snowflake/kafka/connector/Utils.java#L218) and errors. 

I'd still suggest that this error is made clearer to end users.
