### ISSUE TITLE
java.lang.NoClassDefFoundError: org/bouncycastle/jce/provider/BouncyCastleProvider

### ISSUE THREAD

**Issue by rmoff** [snowflakedb/snowflake-kafka-connector#63]
Install connector plugin

```
confluent-hub install --no-prompt snowflakeinc/snowflake-kafka-connector:0.5.1 
```

Create connector

```
curl -i -X PUT -H  "Content-Type:application/json" \
    http://localhost:8083/connectors/test/config \
    -d '{
        "connector.class":"com.snowflake.kafka.connector.SnowflakeSinkConnector",
        "tasks.max":1,
        "topics":"mysql-01-asgard.demo.transactions",
        "snowflake.topic2table.map": "mysql-01-asgard.demo.transactions:TRANSACTIONS",
        "snowflake.url.name":"asdf.us-east-1.snowflakecomputing.com",
        "snowflake.user.name":"kafka",
        "snowflake.user.role":"SYSADMIN",
        "snowflake.private.key":"xxx",
        "snowflake.database.name":"DEMO_DB",
        "snowflake.schema.name":"PUBLIC",
        "key.converter":"org.apache.kafka.connect.storage.StringConverter",
        "value.converter":"com.snowflake.kafka.connector.records.SnowflakeAvroConverter",
        "value.converter.schema.registry.url":"https://${CCLOUD_SCHEMA_REGISTRY_URL}",
        "value.converter.basic.auth.credentials.source":"USER_INFO", "value.converter.basic.auth.user.info":"${CCLOUD_SCHEMA_REGISTRY_API_KEY}:${CCLOUD_SCHEMA_REGISTRY_API_SECRET}",
        "offset.flush.interval.ms":"60000",
    "offset.flush.timeout.ms":"10000",
    "buffer.count.records":"100",
    "buffer.size.bytes":"65536"
     }'
```

Fails: 

```
[2019-10-17 08:05:39,689] INFO [test|worker] Creating connector test of type com.snowflake.kafka.connector.SnowflakeSinkConnector (org.apache.kafka.connect.runtime.Worker:246)
[2019-10-17 08:05:39,696] INFO [test|worker] Instantiated connector test with version 0.5.1 of type class com.snowflake.kafka.connector.SnowflakeSinkConnector (org.apache.kafka.connect.runtime.Worker:249)
[2019-10-17 08:05:39,700] INFO [test|worker]
[SF_KAFKA_CONNECTOR] Snowflake Kafka Connector Version: 0.5.1 (com.snowflake.kafka.connector.Utils:80)
[2019-10-17 08:05:39,759] INFO [test|worker]
[SF_KAFKA_CONNECTOR] SnowflakeSinkConnector:start (com.snowflake.kafka.connector.SnowflakeSinkConnector:87)
[2019-10-17 08:05:39,759] INFO [test|worker]
[SF_KAFKA_CONNECTOR] buffer.flush.time set to default 30 seconds (com.snowflake.kafka.connector.SnowflakeSinkConnector:126)
[2019-10-17 08:05:39,764] ERROR [test|worker] WorkerConnector{id=test} Error while starting connector (org.apache.kafka.connect.runtime.WorkerConnector:119)
java.lang.NoClassDefFoundError: org/bouncycastle/jce/provider/BouncyCastleProvider
  at com.snowflake.kafka.connector.internal.SnowflakeConnectionServiceFactory$SnowflakeConnectionServiceBuilder.setProperties(SnowflakeConnectionServiceFactory.java:40)
  at com.snowflake.kafka.connector.SnowflakeSinkConnector.start(SnowflakeSinkConnector.java:137)
  at org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:111)
  at org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:136)
  at org.apache.kafka.connect.runtime.WorkerConnector.transitionTo(WorkerConnector.java:196)
  at org.apache.kafka.connect.runtime.Worker.startConnector(Worker.java:252)
  at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startConnector(DistributedHerder.java:1079)
  at org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1300(DistributedHerder.java:117)
  at org.apache.kafka.connect.runtime.distributed.DistributedHerder$15.call(DistributedHerder.java:1095)
  at org.apache.kafka.connect.runtime.distributed.DistributedHerder$15.call(DistributedHerder.java:1091)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.bouncycastle.jce.provider.BouncyCastleProvider
  at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:104)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  ... 14 more
```

**Comment by binglihub** [comment]
What is your confluent package version?

**Comment by rmoff** [comment]
@binglihub I'm using the Docker images, tried with both `5.4.0-beta1` and `5.3.1`./

**Comment by tarys** [comment]
I do have same problem.

**Comment by ivanyu** [comment]
I made a PR regarding this, but wont-fix https://github.com/snowflakedb/snowflake-kafka-connector/pull/51

**Comment by binglihub** [comment]
https://github.com/snowflakedb/snowflake-kafka-connector/commit/6761699ea5f2c3023ca282d8d0a34cd5e7578795

**Comment by binglihub** [comment]
@ivanyu Now, we are changed and will fix it in next release.

**Comment by rmoff** [comment]
thanks @binglihub - do you know when the new release will be on Confluent Hub?

**Comment by sunilkhaire82** [comment]
I am facing the same issue. Is there any fix available yet ?

**Comment by sfc-gh-japatel** [comment]
Might be too late but here is the doc: https://docs.snowflake.com/en/user-guide/kafka-connector-install.html#download-the-kafka-connector-files
Need to install two more jars where the Kafka connector jar is present.

**Comment by Real-dev-byte** [comment]
@sfc-gh-japatel Please check my Dockerfile. Am i downloading the bouncy jars in right path? Please check this

FROM confluentinc/cp-kafka-connect:5.3.1
# Create plugin directory
RUN mkdir -p /usr/share/java/plugins
RUN mkdir -p /usr/share/java/kafka-connect-jdbc
# Add Snowflake connector4 jar
RUN curl -sSL "https://repo1.maven.org/maven2/com/snowflake/snowflake-kafka-connector/0.5.0/snowflake-kafka-connector-0.5.0.jar" -o /usr/share/java/plugins/snowflake-kafka-connector-0.5.0.jar
# Add Snowflake JDBC connector jar
RUN curl -sSL "https://repo1.maven.org/maven2/net/snowflake/snowflake-jdbc/3.9.2/snowflake-jdbc-3.9.2.jar" -o /usr/share/java/kafka-connect-jdbc/snowflake-jdbc-connector-3.9.2.jar
# Install the below jars
RUN curl -sSL "https://repo1.maven.org/maven2/org/bouncycastle/bc-fips/1.0.1/bc-fips-1.0.1.jar" -o /usr/share/java/plugins/bc-fips-1.0.1.jar
RUN curl -sSL "https://repo1.maven.org/maven2/org/bouncycastle/bcpkix-fips/1.0.3/bcpkix-fips-1.0.3.jar" -o /usr/share/java/plugins/bcpkix-fips-1.0.3.jar
# copy the properties file
# COPY datagen-users.json /tmp/
COPY snowflake-connector-kafkapoc.json /tmp
# datagen config
ENV CONNECT_PLUGIN_PATH="/usr/share/java,/usr/share/confluent-hub-components"
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-datagen:0.1.0
