### ISSUE TITLE
Sink-connector - parsing fails for some valid json payload. Error Code: 5012 

### ISSUE THREAD

**Issue by nkkrishnakfk** [snowflakedb/snowflake-kafka-connector#641]
Example: 
Parsing passes for the below payload:
```
{
    "Date": "2022-12-06T00:00:00.000Z",
    "count": "0",
    "ID": "5f7340a1-3e53-417f-8176-b974e2ca57ac",
    "entityNumber": "1232123123"
}

```

Parsing FAILS for the below payload and stops the sink-connector -
```
{
    "Date": "2022-12-06T00:00:00.000Z",
    "count": "0",
    "ID": "5f7340a1-3e53-417f-8176-b974e2ca57ac",
    "entityNumber": "FT109918"
}
```
log below says in place of "FT109918" it was expecting ('true', 'false' or 'null') 

Parsing passes for the below payload - 
```
[SF_KAFKA_CONNECTOR] SnowflakeSinkTask[ID:1]:put 300 records (com.snowflake.kafka.connector.SnowflakeSinkTask)
[2023-05-26 17:12:13,437] INFO
[SF_KAFKA_CONNECTOR] SnowflakeSinkTask[ID:1]:put 119 records (com.snowflake.kafka.connector.SnowflakeSinkTask)
[2023-05-26 17:12:13,453] ERROR
[SF_KAFKA_CONNECTOR] Failed to parse JSON record
**[SF_KAFKA_CONNECTOR] net.snowflake.client.jdbc.internal.fasterxml.jackson.core.JsonParseException: Unrecognized token 'FT109918': was expecting ('true', 'false' or 'null')
[SF_KAFKA_CONNECTOR]  at [Source: (byte[])"FT109918"; line: 1, column: 17] (com.snowflake.kafka.connector.records.SnowflakeConverter)
[2023-05-26 17:12:13,455] INFO
[SF_KAFKA_CONNECTOR] SnowflakeSinkTask[ID:1]:put 300 records (com.snowflake.kafka.connector.SnowflakeSinkTask)
[2023-05-26 17:12:13,458] ERROR WorkerSinkTask{id=prod-export-order-1} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. Error:
[SF_KAFKA_CONNECTOR] Exception: Data is broken
[SF_KAFKA_CONNECTOR] Error Code: 5012
[SF_KAFKA_CONNECTOR] Detail: Failed to access record data because it is broken (org.apache.kafka.connect.runtime.WorkerSinkTask)
com.snowflake.kafka.connector.internal.SnowflakeKafkaConnectorException:
[SF_KAFKA_CONNECTOR] Exception: Data is broken
[SF_KAFKA_CONNECTOR] Error Code: 5012
[SF_KAFKA_CONNECTOR] Detail: Failed to access record data because it is broken
	at com.snowflake.kafka.connector.internal.SnowflakeErrors.getException(SnowflakeErrors.java:362)
	at com.snowflake.kafka.connector.internal.SnowflakeErrors.getException(SnowflakeErrors.java:321)**
	at com.snowflake.kafka.connector.records.SnowflakeRecordContent.getData(SnowflakeRecordContent.java:111)
	at com.snowflake.kafka.connector.records.RecordService.putKey(RecordService.java:170)
	at com.snowflake.kafka.connector.records.RecordService.processRecord(RecordService.java:126)
	at com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1$ServiceContext$PartitionBuffer.insert(SnowflakeSinkServiceV1.java:862)
	at com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1$ServiceContext$PartitionBuffer.access$400(SnowflakeSinkServiceV1.java:823)
	at com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1$ServiceContext.insert(SnowflakeSinkServiceV1.java:417)
	at com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1$ServiceContext.access$100(SnowflakeSinkServiceV1.java:240)
	at com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1.insert(SnowflakeSinkServiceV1.java:89)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at com.snowflake.kafka.connector.SnowflakeSinkTask.put(SnowflakeSinkTask.java:208)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:581)
```

Connector config: 
key.converter: "com.snowflake.kafka.connector.records.SnowflakeJsonConverter"
value.converter: "com.snowflake.kafka.connector.records.SnowflakeJsonConverter"
key.converter.schemas.enable: "false"
value.converter.schemas.enable: "false"

Producer Serialiser for reference:
key serialiser :: org.apache.kafka.common.serialization.StringSerializer
value serialiser:: org.springframework.kafka.support.serializer.JsonSerializer

**Comment by nkkrishnakfk** [comment]
Its fixed- 
key convertor was wrong and was not in sync with producer.
Changing the value of key convertor in connector config as below fixed - 
`  key.converter: "org.apache.kafka.connect.storage.StringConverter"
`
