### ISSUE TITLE
[streaming] unrecoverable exception when column addition on destination table

### ISSUE THREAD

**Issue by BDeus** [snowflakedb/snowflake-kafka-connector#642]
Related to my question [here](https://github.com/snowflakedb/snowflake-ingest-java/issues/511)

### Context:
Usage of a Kafka connector with options:
```
"snowflake.enable.schematization": "TRUE", 
"snowflake.ingestion.method": "SNOWPIPE_STREAMING",
"errors.log.enable":"TRUE",
"errors.retry.timeout": -1,
```

Everything run smoothly except when i try to change the destination table structure (adding or remove a nullable column).
When the ALTER TABLE finish the connector tasks failed with this exception

```
ERROR [test-snowflake3|task-0] WorkerSinkTask{id=test-snowflake3-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:210)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:618)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:336)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
        at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:181)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.apache.kafka.connect.errors.DataException: Error inserting Records using Streaming API
        at com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel.handleInsertRowsFailures(TopicPartitionChannel.java:744)
        at com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel.insertBufferedRecords(TopicPartitionChannel.java:517)
        at com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel.insertBufferedRecordsIfFlushTimeThresholdReached(TopicPartitionChannel.java:488)
        at com.snowflake.kafka.connector.internal.streaming.SnowflakeSinkServiceV2.insert(SnowflakeSinkServiceV2.java:213)
        at com.snowflake.kafka.connector.SnowflakeSinkTask.put(SnowflakeSinkTask.java:328)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:587)
        ... 11 more
Caused by: net.snowflake.ingest.utils.SFException: Ingest client internal error: null.
        at net.snowflake.ingest.streaming.internal.AbstractRowBuffer.insertRows(AbstractRowBuffer.java:319)
        at net.snowflake.ingest.streaming.internal.ParquetRowBuffer.insertRows(ParquetRowBuffer.java:39)
        at net.snowflake.ingest.streaming.internal.SnowflakeStreamingIngestChannelInternal.insertRows(SnowflakeStreamingIngestChannelInternal.java:365)
        at com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel$InsertRowsApiResponseSupplier.get(TopicPartitionChannel.java:624)
        at com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel$InsertRowsApiResponseSupplier.get(TopicPartitionChannel.java:584)
        at dev.failsafe.Functions.lambda$toCtxSupplier$11(Functions.java:243)
        at dev.failsafe.Functions.lambda$get$0(Functions.java:46)
        at dev.failsafe.internal.FallbackExecutor.lambda$apply$0(FallbackExecutor.java:51)
        at dev.failsafe.SyncExecutionImpl.executeSync(SyncExecutionImpl.java:182)
        at dev.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:438)
        at dev.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:115)
        at com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel.insertRowsWithFallback(TopicPartitionChannel.java:578)
        at com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel.insertBufferedRecords(TopicPartitionChannel.java:507)
        ... 15 more
Caused by: java.lang.NullPointerException
```

### Question:
Is it possible to handle this error as a recoverable exception and recreate a channel internally ?

**Comment by sfc-gh-tzhang** [comment]
Which version of KC are you using? I'm not able to repro this locally, could you share a more detailed reproing step or send us the full log? Thanks!

**Comment by BDeus** [comment]
Hi,
i'm using Kafka Connect 3.4.0 with Snowflake Connector 1.9.1
The error seems to be a race condition because i can reproduce it randomly.
I also have a `"buffer.flush.time":"1"`. It think the error is more likely to happen when flush is frequent

here is the log that i get when error throw:
```
[2023-06-27 10:54:06,106] INFO [test-snowflake3|task-0] [SF_INGEST] Register blob request preparing for blob=[2023/6/27/8/54/rwwm25_p5GXb5s0BBRozffQaO0lohAEv5uxxTdfhgIA4YnGao9kCC_1011_251_39.bdec], client=KC_CLIENT_test_snowflake3_1773562684_0, executionCount=0 (net.snowflake.ingest.streaming.internal.SnowflakeStreamingIngestClientInternal:58)
[2023-06-27 10:54:06,321] INFO [test-snowflake3|task-0] [SF_INGEST] Register blob request returned for blob=[2023/6/27/8/54/rwwm25_p5GXb5s0BBRozffQaO0lohAEv5uxxTdfhgIA4YnGao9kCC_1011_251_39.bdec], client=KC_CLIENT_test_snowflake3_1773562684_0, executionCount=0 (net.snowflake.ingest.streaming.internal.SnowflakeStreamingIngestClientInternal:58)
[2023-06-27 10:54:06,322] WARN [test-snowflake3|task-0] [SF_INGEST] Channel has been invalidated because of failure response, name=CONNECTOR_0, channel_sequencer=23, status_code=32, executionCount=0 (net.snowflake.ingest.streaming.internal.SnowflakeStreamingIngestClientInternal:45)
[2023-06-27 10:54:06,322] WARN [test-snowflake3|task-0] Unexpected error happens during insertRows: {} (net.snowflake.ingest.streaming.internal.AbstractRowBuffer:76)
java.lang.NullPointerException
[2023-06-27 10:54:06,322] INFO [test-snowflake3|task-0] [SF_INGEST] Trying to close ParquetRowBuffer for channel=DBTEST.PUBLIC.TABLE.CONNECTOR_0 from function=invalidate, allocatedBeforeRelease=0, allocatedAfterRelease=0 (net.snowflake.ingest.streaming.internal.AbstractRowBuffer:58)
[2023-06-27 10:54:06,323] WARN [test-snowflake3|task-0] Channel is invalidated, name=DBTEST.PUBLIC.TABLE.CONNECTOR_0, channel sequencer=23, row sequencer=3, message=invalidate with matched sequencer (net.snowflake.ingest.streaming.internal.SnowflakeStreamingIngestChannelInternal:76)
[2023-06-27 10:54:06,323] INFO [test-snowflake3|task-0] [SF_KAFKA_CONNECTOR] [KC:2004410987] Successfully called insertRows for channel:DBTEST.PUBLIC.TABLE.CONNECTOR_0, buffer:StreamingBuffer{numOfRecords=11, bufferSizeBytes=144953, firstOffset=39842351, lastOffset=39842361}, insertResponseHasErrors:true (com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel:107)
[2023-06-27 10:54:06,324] ERROR [test-snowflake3|task-0] [SF_KAFKA_CONNECTOR] [KC:2004410987] Insert Row Error message (com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel:155)
[2023-06-27 10:54:06,324] ERROR [test-snowflake3|task-0] [SF_KAFKA_CONNECTOR] [KC:2004410987] Insert Row Error message (com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel:155)
[2023-06-27 10:54:06,324] ERROR [test-snowflake3|task-0] [SF_KAFKA_CONNECTOR] [KC:2004410987] Insert Row Error message (com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel:155)
[2023-06-27 10:54:06,325] ERROR [test-snowflake3|task-0] WorkerSinkTask{id=test-snowflake3-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. Error: Error inserting Records using Streaming API (org.apache.kafka.connect.runtime.WorkerSinkTask:616)
org.apache.kafka.connect.errors.DataException: Error inserting Records using Streaming API
        at com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel.handleInsertRowsFailures(TopicPartitionChannel.java:744)
        at com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel.insertBufferedRecords(TopicPartitionChannel.java:517)
        at com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel.insertBufferedRecordsIfFlushTimeThresholdReached(TopicPartitionChannel.java:488)
        at com.snowflake.kafka.connector.internal.streaming.SnowflakeSinkServiceV2.insert(SnowflakeSinkServiceV2.java:213)
        at com.snowflake.kafka.connector.SnowflakeSinkTask.put(SnowflakeSinkTask.java:328)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:587)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:336)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
        at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:181)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: net.snowflake.ingest.utils.SFException: Ingest client internal error: null.
        at net.snowflake.ingest.streaming.internal.AbstractRowBuffer.insertRows(AbstractRowBuffer.java:319)
        at net.snowflake.ingest.streaming.internal.ParquetRowBuffer.insertRows(ParquetRowBuffer.java:39)
        at net.snowflake.ingest.streaming.internal.SnowflakeStreamingIngestChannelInternal.insertRows(SnowflakeStreamingIngestChannelInternal.java:365)
        at com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel$InsertRowsApiResponseSupplier.get(TopicPartitionChannel.java:624)
        at com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel$InsertRowsApiResponseSupplier.get(TopicPartitionChannel.java:584)
        at dev.failsafe.Functions.lambda$toCtxSupplier$11(Functions.java:243)
        at dev.failsafe.Functions.lambda$get$0(Functions.java:46)
        at dev.failsafe.internal.FallbackExecutor.lambda$apply$0(FallbackExecutor.java:51)
        at dev.failsafe.SyncExecutionImpl.executeSync(SyncExecutionImpl.java:182)
        at dev.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:438)
        at dev.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:115)
        at com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel.insertRowsWithFallback(TopicPartitionChannel.java:578)
        at com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel.insertBufferedRecords(TopicPartitionChannel.java:507)
        ... 15 more
Caused by: java.lang.NullPointerException
[2023-06-27 10:54:06,328] INFO [test-snowflake3|task-0] [SF_INGEST] Trying to close ParquetRowBuffer for channel=DBTEST.PUBLIC.TABLE.CONNECTOR_0 from function=checkValidation, allocatedBeforeRelease=0, allocatedAfterRelease=0 (net.snowflake.ingest.streaming.internal.AbstractRowBuffer:58)
[2023-06-27 10:54:07,335] WARN [test-snowflake3|task-0] [SF_KAFKA_CONNECTOR] [KC:2004410987] [OFFSET_TOKEN_RETRY_POLICY] retry for getLatestCommittedOffsetToken. Retry no:1, message:Channel DBTEST.PUBLIC.TABLE.CONNECTOR_0 is invalid and might contain uncommitted rows, please consider reopening the channel to restart. (com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel:143)
[2023-06-27 10:54:07,335] INFO [test-snowflake3|task-0] [SF_INGEST] Trying to close ParquetRowBuffer for channel=DBTEST.PUBLIC.TABLE.CONNECTOR_0 from function=checkValidation, allocatedBeforeRelease=0, allocatedAfterRelease=0 (net.snowflake.ingest.streaming.internal.AbstractRowBuffer:58)
[2023-06-27 10:54:08,344] WARN [test-snowflake3|task-0] [SF_KAFKA_CONNECTOR] [KC:2004410987] [OFFSET_TOKEN_RETRY_POLICY] retry for getLatestCommittedOffsetToken. Retry no:2, message:Channel DBTEST.PUBLIC.TABLE.CONNECTOR_0 is invalid and might contain uncommitted rows, please consider reopening the channel to restart. (com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel:143)
[2023-06-27 10:54:08,345] INFO [test-snowflake3|task-0] [SF_INGEST] Trying to close ParquetRowBuffer for channel=DBTEST.PUBLIC.TABLE.CONNECTOR_0 from function=checkValidation, allocatedBeforeRelease=0, allocatedAfterRelease=0 (net.snowflake.ingest.streaming.internal.AbstractRowBuffer:58)
[2023-06-27 10:54:08,345] WARN [test-snowflake3|task-0] [SF_KAFKA_CONNECTOR] [KC:2004410987] [GET_OFFSET_TOKEN_FALLBACK] Re-opening channel:DBTEST.PUBLIC.TABLE.CONNECTOR_0 (com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel:143)
[2023-06-27 10:54:08,346] INFO [test-snowflake3|task-0] [SF_KAFKA_CONNECTOR] [KC:2004410987] Opening a channel with name:CONNECTOR_0 for table name:TABLE (com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel:107)
[2023-06-27 10:54:08,504] INFO [test-snowflake3|task-0] [SF_INGEST] Open channel request succeeded, channel=CONNECTOR_0, table=DBTEST.PUBLIC.TABLE, clientSequencer=24, rowSequencer=0, client=KC_CLIENT_test_snowflake3_1773562684_0 (net.snowflake.ingest.streaming.internal.SnowflakeStreamingIngestClientInternal:58)
[2023-06-27 10:54:08,504] INFO [test-snowflake3|task-0] [SF_INGEST] Channel=CONNECTOR_0 created for table=TABLE (net.snowflake.ingest.streaming.internal.SnowflakeStreamingIngestChannelInternal:58)
[2023-06-27 10:54:08,506] WARN [test-snowflake3|task-0] [SF_KAFKA_CONNECTOR] [KC:2004410987] [GET_OFFSET_TOKEN_FALLBACK] Fetching offsetToken after re-opening the channel:DBTEST.PUBLIC.TABLE.CONNECTOR_0 (com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel:143)
[2023-06-27 10:54:08,626] INFO [test-snowflake3|task-0] [SF_KAFKA_CONNECTOR] [KC:2004410987] Fetched offsetToken:39842338 for channelName:DBTEST.PUBLIC.TABLE.CONNECTOR_0 (com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel:107)
[2023-06-27 10:54:08,627] WARN [test-snowflake3|task-0] [SF_KAFKA_CONNECTOR] [KC:2004410987] [RESET_PARTITION] Emptying current buffer:StreamingBuffer{numOfRecords=0, bufferSizeBytes=0, firstOffset=-1, lastOffset=-1} for Channel:DBTEST.PUBLIC.TABLE.CONNECTOR_0 due to reset of offsets in kafka (com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel:143)
[2023-06-27 10:54:08,627] WARN [test-snowflake3|task-0] [SF_KAFKA_CONNECTOR] [KC:2004410987] [GET_OFFSET_TOKEN_FALLBACK] Channel:DBTEST.PUBLIC.TABLE.CONNECTOR_0, OffsetRecoveredFromSnowflake:39842338, Reset kafka offset to:39842339 (com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel:143)
[2023-06-27 10:54:08,627] INFO [test-snowflake3|task-0] [SF_INGEST] Channel is marked as closed, name=DBTEST.PUBLIC.TABLE.CONNECTOR_0, channel sequencer=24, row sequencer=0 (net.snowflake.ingest.streaming.internal.SnowflakeStreamingIngestChannelInternal:58)
[2023-06-27 10:54:08,718] INFO [SF_INGEST] Get channel status name=CONNECTOR_0, status=0, clientSequencer=24, rowSequencer=0, offsetToken=39842338, persistedRowSequencer=0, persistedOffsetToken=39842338 (net.snowflake.ingest.streaming.internal.SnowflakeStreamingIngestClientInternal:58)
[2023-06-27 10:54:08,719] INFO [SF_INGEST] Trying to close ParquetRowBuffer for channel=DBTEST.PUBLIC.TABLE.CONNECTOR_0 from function=close, allocatedBeforeRelease=0, allocatedAfterRelease=0 (net.snowflake.ingest.streaming.internal.AbstractRowBuffer:58)
[2023-06-27 10:54:08,719] INFO [test-snowflake3|task-0] [SF_KAFKA_CONNECTOR] [KC:2004410987] Closing partitionChannel:DBTEST.PUBLIC.TABLE.CONNECTOR_0, partition:CONNECTOR, topic:0 (com.snowflake.kafka.connector.internal.streaming.SnowflakeSinkServiceV2:107)
[2023-06-27 10:54:08,794] ERROR [test-snowflake3|task-0] WorkerSinkTask{id=test-snowflake3-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:210)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:618)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:336)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
        at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:181)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.apache.kafka.connect.errors.DataException: Error inserting Records using Streaming API
        at com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel.handleInsertRowsFailures(TopicPartitionChannel.java:744)
        at com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel.insertBufferedRecords(TopicPartitionChannel.java:517)
        at com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel.insertBufferedRecordsIfFlushTimeThresholdReached(TopicPartitionChannel.java:488)
        at com.snowflake.kafka.connector.internal.streaming.SnowflakeSinkServiceV2.insert(SnowflakeSinkServiceV2.java:213)
        at com.snowflake.kafka.connector.SnowflakeSinkTask.put(SnowflakeSinkTask.java:328)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:587)
        ... 11 more
Caused by: net.snowflake.ingest.utils.SFException: Ingest client internal error: null.
        at net.snowflake.ingest.streaming.internal.AbstractRowBuffer.insertRows(AbstractRowBuffer.java:319)
        at net.snowflake.ingest.streaming.internal.ParquetRowBuffer.insertRows(ParquetRowBuffer.java:39)
        at net.snowflake.ingest.streaming.internal.SnowflakeStreamingIngestChannelInternal.insertRows(SnowflakeStreamingIngestChannelInternal.java:365)
        at com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel$InsertRowsApiResponseSupplier.get(TopicPartitionChannel.java:624)
        at com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel$InsertRowsApiResponseSupplier.get(TopicPartitionChannel.java:584)
        at dev.failsafe.Functions.lambda$toCtxSupplier$11(Functions.java:243)
        at dev.failsafe.Functions.lambda$get$0(Functions.java:46)
        at dev.failsafe.internal.FallbackExecutor.lambda$apply$0(FallbackExecutor.java:51)
        at dev.failsafe.SyncExecutionImpl.executeSync(SyncExecutionImpl.java:182)
        at dev.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:438)
        at dev.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:115)
        at com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel.insertRowsWithFallback(TopicPartitionChannel.java:578)
        at com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel.insertBufferedRecords(TopicPartitionChannel.java:507)
        ... 15 more
Caused by: java.lang.NullPointerException
```

**Comment by BDeus** [comment]
Hi,
i upgrade to connector 1.9.4 and i cannot reproduce the issue
instead i have a WARN log like this
```
[2023-07-24 15:43:25,770] WARN [test-snowflake3|task-0] [SF_INGEST] Channel has been invalidated because of failure response, name=xxxx, channel_sequencer=29, status_code=32,  message=The SDK generated a malformed request. Please contact Snowflake support for further  assistance, executionCount=0 (net.snowflake.ingest.streaming.internal.SnowflakeStreamingIngestClientInternal:45)
[2023-07-24 15:43:25,772] WARN [test-snowflake3|task-0] Channel is invalidated, name=xxxxx, channel sequencer=29, row sequencer=5, message=invalidate with matched sequencer (net.snowflake.ingest.streaming.internal.SnowflakeStreamingIngestChannelInternal:82)
[2023-07-24 15:43:26,155] WARN [test-snowflake3|task-0] [SF_KAFKA_CONNECTOR] Failed Attempt to invoke the insertRows API for buffer:StreamingBuffer{numOfRecords=11, bufferSizeBytes=143815, firstOffset=55712467, lastOffset=55712477} (com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel:82)
[2023-07-24 15:43:26,156] WARN [test-snowflake3|task-0] [SF_KAFKA_CONNECTOR] [INSERT_ROWS_FALLBACK] Re-opening channel:xxxxxx (com.snowflake.kafka.connector.internal.streaming.TopicPartitionChannel:82)
```

I do not know if this has been fix with the upgrade of the Connector or the Ingest SDK.
