### ISSUE TITLE
v0.5.1 does not work in Distributed Connector mode

### ISSUE THREAD

**Issue by tarys** [snowflakedb/snowflake-kafka-connector#65]
[2019-10-21 11:54:21,875] ERROR WorkerSinkTask{id=MY_TOPIC-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. (org.apache.kafka.connect.runtime.WorkerSinkTask)
java.lang.NullPointerException
        at com.snowflake.kafka.connector.SnowflakeSinkTask.put(SnowflakeSinkTask.java:165)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:538)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:321)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by sdomeshok** [comment]
Seeing this same error in standalone mode.

**Comment by binglihub** [comment]
@tarys could you try v0.5.2 to see if the issue fixed? thanks
