### ISSUE TITLE
Snowflake connector 0.5.0 and 0.5.1 both throwing NPE

### ISSUE THREAD

**Issue by sdomeshok** [snowflakedb/snowflake-kafka-connector#70]
Stacktrace:
```
[SF_KAFKA_CONNECTOR] SnowflakeSinkTask:start (com.snowflake.kafka.connector.SnowflakeSinkTask:78)
[2019-10-22 12:07:31,561] INFO
[SF_KAFKA_CONNECTOR] initialized the snowflake connection (com.snowflake.kafka.connector.internal.SnowflakeConnectionServiceV1:38)
[2019-10-22 12:07:31,562] INFO WorkerSinkTask{id=kafkaingest-0} Sink task finished initialization and start (org.apache.kafka.connect.runtime.WorkerSinkTask:303)
[2019-10-22 12:07:31,836] INFO Cluster ID: npJAAcx-SjyK242XsgS1MQ (org.apache.kafka.clients.Metadata:285)
[2019-10-22 12:07:31,838] INFO [Consumer clientId=consumer-2, groupId=connect-kafkaingest] Discovered group coordinator 10.225.171.232:9093 (id: 2147483646 rack: null) (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:654)
[2019-10-22 12:07:31,851] INFO [Consumer clientId=consumer-2, groupId=connect-kafkaingest] Revoking previously assigned partitions [] (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:458)
[2019-10-22 12:07:31,855] INFO [Consumer clientId=consumer-2, groupId=connect-kafkaingest] (Re-)joining group (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:486)
[2019-10-22 12:07:32,485] ERROR WorkerSinkTask{id=kafkaingest-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. (org.apache.kafka.connect.runtime.WorkerSinkTask:585)
java.lang.NullPointerException
	at com.snowflake.kafka.connector.SnowflakeSinkTask.put(SnowflakeSinkTask.java:168)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:565)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:323)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:226)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:194)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
[2019-10-22 12:07:32,487] ERROR WorkerSinkTask{id=kafkaingest-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:177)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:587)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:323)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:226)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:194)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
	at com.snowflake.kafka.connector.SnowflakeSinkTask.put(SnowflakeSinkTask.java:168)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:565)
	... 10 more
[2019-10-22 12:07:32,489] ERROR WorkerSinkTask{id=kafkaingest-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:178)
[2019-10-22 12:07:32,489] INFO
[SF_KAFKA_CONNECTOR] SnowflakeSinkTask:stop (com.snowflake.kafka.connector.SnowflakeSinkTask:112)
```

Configuration:
```
name=kafkaingest
connector.class=com.snowflake.kafka.connector.SnowflakeSinkConnector
tasks.max=1
topics=barTopic
buffer.count.records=100
buffer.flush.time=60
buffer.size.bytes=65536
snowflake.url.name=xxx.ap-southeast-2.snowflakecomputing.com
snowflake.user.name=kafka_ingest
snowflake.private.key=xxx
snowflake.private.key.passphrase=xxx
snowflake.database.name=xxx
snowflake.schema.name=xxx
key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=com.snowflake.kafka.connector.records.SnowflakeJsonConverter
```

**Comment by sdomeshok** [comment]
Fixed by 0.5.2
