### ISSUE TITLE
0.5.2: private key does not validate

### ISSUE THREAD

**Issue by sdomeshok** [snowflakedb/snowflake-kafka-connector#71]
Logs are as follows:
```
[SF_KAFKA_CONNECTOR] Exception: Invalid encrypted private key or passphrase
[SF_KAFKA_CONNECTOR] Error Code: 0018
[SF_KAFKA_CONNECTOR] Detail: failed to decrypt private key
[SF_KAFKA_CONNECTOR] Message: Cannot find any provider supporting 1.2.840.113549.1.5.13
[SF_KAFKA_CONNECTOR] java.base/javax.crypto.Cipher.getInstance(Cipher.java:565)
[SF_KAFKA_CONNECTOR] com.snowflake.kafka.connector.internal.InternalUtils.parseEncryptedPrivateKey(InternalUtils.java:96)
[SF_KAFKA_CONNECTOR] com.snowflake.kafka.connector.internal.InternalUtils.createProperties(InternalUtils.java:197)
[SF_KAFKA_CONNECTOR] com.snowflake.kafka.connector.internal.SnowflakeConnectionServiceFactory$SnowflakeConnectionServiceBuilder.setProperties(SnowflakeConnectionServiceFactory.java:40)
[SF_KAFKA_CONNECTOR] com.snowflake.kafka.connector.SnowflakeSinkConnector.start(SnowflakeSinkConnector.java:137)
[SF_KAFKA_CONNECTOR] org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:111)
[SF_KAFKA_CONNECTOR] org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:136)
[SF_KAFKA_CONNECTOR] org.apache.kafka.connect.runtime.WorkerConnector.transitionTo(WorkerConnector.java:195)
[SF_KAFKA_CONNECTOR] org.apache.kafka.connect.runtime.Worker.startConnector(Worker.java:253)
[SF_KAFKA_CONNECTOR] org.apache.kafka.connect.runtime.standalone.StandaloneHerder.startConnector(StandaloneHerder.java:289)
[SF_KAFKA_CONNECTOR] org.apache.kafka.connect.runtime.standalone.StandaloneHerder.putConnectorConfig(StandaloneHerder.java:205)
[SF_KAFKA_CONNECTOR] org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:109)
	at com.snowflake.kafka.connector.internal.SnowflakeErrors.getException(SnowflakeErrors.java:367)
	at com.snowflake.kafka.connector.internal.SnowflakeErrors.getException(SnowflakeErrors.java:343)
	at com.snowflake.kafka.connector.internal.SnowflakeErrors.getException(SnowflakeErrors.java:330)
	at com.snowflake.kafka.connector.internal.InternalUtils.parseEncryptedPrivateKey(InternalUtils.java:109)
	at com.snowflake.kafka.connector.internal.InternalUtils.createProperties(InternalUtils.java:197)
	at com.snowflake.kafka.connector.internal.SnowflakeConnectionServiceFactory$SnowflakeConnectionServiceBuilder.setProperties(SnowflakeConnectionServiceFactory.java:40)
	at com.snowflake.kafka.connector.SnowflakeSinkConnector.start(SnowflakeSinkConnector.java:137)
	at org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:111)
	at org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:136)
	at org.apache.kafka.connect.runtime.WorkerConnector.transitionTo(WorkerConnector.java:195)
	at org.apache.kafka.connect.runtime.Worker.startConnector(Worker.java:253)
	at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.startConnector(StandaloneHerder.java:289)
	at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.putConnectorConfig(StandaloneHerder.java:205)
	at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:109)
```

I believe this is related to this commit which removed the `BouncyCastle` crypto provider which is suggested by https://stackoverflow.com/questions/46767281/reading-pkcs8-in-pem-format-cannot-find-provider/46770084#46770084

https://github.com/snowflakedb/snowflake-kafka-connector/commit/6761699ea5f2c3023ca282d8d0a34cd5e7578795

**Comment by binglihub** [comment]
Could you try to encrypt your RSA private key with this command?
```
openssl pkcs8 -topk8 -inform PEM -v1 PBE-MD5-DES -in <input_rsa_key_name> -out <encrypted_key_name>
```

**Comment by sdomeshok** [comment]
@binglihub That yields the same error 🤷‍♂

**Comment by binglihub** [comment]
@sdomeshok what is your java version?

**Comment by xiekevin** [comment]
I am also facing this issue, I've temporarily reverted to using an unencrypted key

**Comment by binglihub** [comment]
Please checkout connector v0.5.4 from Maven or Confluent Hub.
Now, we only support encryption algorithm in FIPS 140-2.
You can find an instruction from our official doc
https://docs.snowflake.net/manuals/user-guide/kafka-connector-install.html#using-key-pair-authentication

Note: if you download connector from Maven and want to use encrypted RSA private Key, you have to manually install bouncy castle fips distribution jar file. 
https://docs.snowflake.net/manuals/user-guide/kafka-connector-install.html#download-the-kafka-connector-jar-files

If you download connector from Confluent Hub, no additional dependency required.
