### ISSUE TITLE
WorkerSincTask Error 5014

### ISSUE THREAD

**Issue by xiekevin** [snowflakedb/snowflake-kafka-connector#77]
```[kafkaconnect-9e4947f-2]2019-10-29T18:57:52.282205[kafka-connect][2019-10-29 18:57:52,281] WARN WorkerSinkTask{id=SnowflakeSink-0} Offset commit failed during close (org.apache.kafka.connect.runtime.WorkerSinkTask:381)
[kafkaconnect-9e4947f-2]2019-10-29T18:57:52.282205[kafka-connect][2019-10-29 18:57:52,281] ERROR WorkerSinkTask{id=SnowflakeSink-0} Commit of offsets threw an unexpected exception for sequence number 1: null (org.apache.kafka.connect.runtime.WorkerSinkTask:259)
[kafkaconnect-9e4947f-2]2019-10-29T18:57:52.282205[kafka-connect]com.snowflake.kafka.connector.internal.SnowflakeKafkaConnectorException:
[kafkaconnect-9e4947f-2]2019-10-29T18:57:52.282205[kafka-connect][SF_KAFKA_CONNECTOR] Exception: Failed to put records
[kafkaconnect-9e4947f-2]2019-10-29T18:57:52.282205[kafka-connect][SF_KAFKA_CONNECTOR] Error Code: 5014
[kafkaconnect-9e4947f-2]2019-10-29T18:57:52.282205[kafka-connect][SF_KAFKA_CONNECTOR] Detail: SinkTask hasn't been initialized before calling PUT function```
```
 Can anyone help me identify the root cause of this error?

**Comment by binglihub** [comment]
could you try to remove the snowpipe generated by connector and restart the connector?

**Comment by binglihub** [comment]
or, just restart connector again

**Comment by xiekevin** [comment]
Ah thanks for the help @binglihub. I've tried restarting the connector many times, I'm using it as part of a managed service for Kafka Connect (Aiven) so the amount of things I can change is fairly limited.

**Comment by binglihub** [comment]
Let me test it. it could be a server side issue.

**Comment by binglihub** [comment]
It is because of STOP function in SinkTask Timeout.
Fixed in https://github.com/snowflakedb/snowflake-kafka-connector/commit/855018684dab74b20cd907402d4bea1b5e0fcf89

**Comment by xiekevin** [comment]
@binglihub thanks for looking into it! do you know when this change / version 0.5.4 will be released?

**Comment by binglihub** [comment]
@xiekevin it is available on Maven and Confluent Hub now

**Comment by ashinohara** [comment]
I have the most recent connector version `0.5.5` and I am still receiving a similar error when running the kafka connector:

```
[2019-11-19 12:50:59,491] ERROR WorkerSinkTask{id=Snowflake-7} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. (org.apache.kafka.connect.runtime.WorkerSinkTask:558)
com.snowflake.kafka.connector.internal.SnowflakeKafkaConnectorException:
[SF_KAFKA_CONNECTOR] Exception: Failed to put records
[SF_KAFKA_CONNECTOR] Error Code: 5014
[SF_KAFKA_CONNECTOR] Detail: SinkTask hasn't been initialized before calling PUT function
	at com.snowflake.kafka.connector.internal.SnowflakeErrors.getException(SnowflakeErrors.java:362)
	at com.snowflake.kafka.connector.internal.SnowflakeErrors.getException(SnowflakeErrors.java:321)
	at com.snowflake.kafka.connector.SnowflakeSinkTask.getSink(SnowflakeSinkTask.java:94)
	at com.snowflake.kafka.connector.SnowflakeSinkTask.put(SnowflakeSinkTask.java:195)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:538)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:321)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by xiekevin** [comment]
I have seen that intermittently but I suspect it’s related to OOM issues. I upgraded the box the connect cluster is on currently to 32GB and it’s had no issues since after restarting it. Perhaps try that?
