### ISSUE TITLE
Task crashes when using Avro message format

### ISSUE THREAD

**Issue by meinac** [snowflakedb/snowflake-kafka-connector#81]
Hi, I am using the sink connector version 0.5.4 and everything is working as expected if I use JSON as the message format but when I switch to Avro, then task crashes.

Here is the Debezium source configuration;

```json
{
  "name": "debezium_test_source",
  "config": {
    "tasks.max": "1",
    "connector.class": "io.debezium.connector.postgresql.PostgresConnector",
    "key.converter": "io.confluent.connect.avro.AvroConverter",
    "value.converter": "io.confluent.connect.avro.AvroConverter",
    "key.converter.schema.registry.url": "http://schema-registry:8081",
    "value.converter.schema.registry.url": "http://schema-registry:8081",
    "transforms": "unwrap",
    "transforms.unwrap.type": "io.debezium.transforms.ExtractNewRecordState",
    "transforms.unwrap.delete.handling.mode": "rewrite",
    "slot.name": "test_slot",
    "plugin.name": "wal2json",
    "database.server.name": "test_database",
    "database.dbname": "test_database",
    "database.hostname": "db-host-name",
    "database.port": "5432",
    "database.user": "db-user",
    "database.password": "db-password",
    "schema.whitelist": "public",
    "table.whitelist": "public.test_table"
  }
}
```

and here is the snowflake sink configuration;

```json
{
  "name": "snowflake_test_sink",
  "config": {
    "tasks.max": "1",
    "connector.class": "com.snowflake.kafka.connector.SnowflakeSinkConnector",
    "key.converter": "com.snowflake.kafka.connector.records.SnowflakeAvroConverter",
    "value.converter": "com.snowflake.kafka.connector.records.SnowflakeAvroConverter",
    "key.converter.schema.registry.url": "http://schema-registry:8081",
    "value.converter.schema.registry.url": "http://schema-registry:8081",
    "topics": "test_database.public.test_table",
    "snowflake.url.name": "....",
    "snowflake.user.name": "....",
    "snowflake.private.key": "....",
    "snowflake.private.key.passphrase": "....",
    "snowflake.database.name": "....",
    "snowflake.schema.name": "...."
  }
}
```

and finally here is the log;

```
[SF_KAFKA_CONNECTOR] SnowflakeSinkTask:close (com.snowflake.kafka.connector.SnowflakeSinkTask)
[2019-11-06 22:53:24,636] ERROR WorkerSinkTask{id=snowflake_test_sink-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
java.lang.NullPointerException
 at com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1$ServiceContext.stopCleaner(SnowflakeSinkServiceV1.java:266)
 at com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1$ServiceContext.close(SnowflakeSinkServiceV1.java:649)
 at com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1$ServiceContext.access$1500(SnowflakeSinkServiceV1.java:172)
 at com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1.lambda$close$0(SnowflakeSinkServiceV1.java:91)
 at java.util.HashMap.forEach(HashMap.java:1289)
 at com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1.close(SnowflakeSinkServiceV1.java:90)
 at com.snowflake.kafka.connector.SnowflakeSinkTask.close(SnowflakeSinkTask.java:183)
 at org.apache.kafka.connect.runtime.WorkerSinkTask.commitOffsets(WorkerSinkTask.java:396)
 at org.apache.kafka.connect.runtime.WorkerSinkTask.closePartitions(WorkerSinkTask.java:590)
 at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:196)
 at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
 at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 at java.lang.Thread.run(Thread.java:748)
[2019-11-06 22:53:24,638] ERROR WorkerSinkTask{id=snowflake_test_sink-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask)
[2019-11-06 22:53:24,639] INFO
[SF_KAFKA_CONNECTOR] SnowflakeSinkTask:stop (com.snowflake.kafka.connector.SnowflakeSinkTask)
```

**Comment by binglihub** [comment]
This issue fixed in 0.5.5.
Please checkout connector 0.5.5 from Maven
https://mvnrepository.com/artifact/com.snowflake/snowflake-kafka-connector

We also published on confluent hub, but need a few hours to update.

**Comment by meinac** [comment]
Thanks for the quick response. Seems like new version has solved the problem but introduced another one. I compiled the version locally and it has some missing jar files in target. `bc-fips-1.0.1.jar` and `bcpkx-fips-1.0.3.jar`. I copied those from the old version and seems like it's working as expected. Sorry for the noise if it was user problem, I've not been working with Java for long time.

**Comment by binglihub** [comment]
@meinac Since bc-fips has jar file checksum validation, we can't include these two jar files in our connector jar file. That means user has to provide these two jar files beside our connector jar file. If you download from Confluent hub, the artifact on confluent hub includes all required jar files because it is a zip file. However, you download from Maven, you have to manually install these two jar files when using encrypted rsa private key because the artifact on Maven is one jar file.
