### ISSUE TITLE
Error Code: 2001  Failed to Prepare SQL Statement

### ISSUE THREAD

**Issue by xiekevin** [snowflakedb/snowflake-kafka-connector#82]
I'm encountering an error when trying to sinc:
```
[SF_KAFKA_CONNECTOR] Exception: Failed to prepare SQL statement
[SF_KAFKA_CONNECTOR] Error Code: 2001
[SF_KAFKA_CONNECTOR] Detail: SQL Exception, reported by Snowflake JDBC
[SF_KAFKA_CONNECTOR] Message: Cannot perform CREATE TABLE. This session does not have a current database. Call 'USE DATABASE', or use a qualified name.
```

My configuration is as follows:

```
{
    "name": "SnowflakeSink",
    "connector.class": "com.snowflake.kafka.connector.SnowflakeSinkConnector",
    "tasks.max": "1",
    "key.converter": "org.apache.kafka.connect.storage.StringConverter",
    "value.converter": "com.snowflake.kafka.connector.records.SnowflakeAvroConverter",
    "value.converter.schema.registry.url": "SCHEMA_URL,
    "value.converter.basic.auth.credentials.source": "USER_INFO",
    "value.converter.basic.auth.user.info": "SHEMA_USER:SCHEMA_PASS",
    "topics.regex": ".*AVRO.*",
    "errors.retry.timeout": "1000",
    "errors.retry.delay.max.ms": "3000",
    "errors.log.enable": "true",
    "errors.log.include.messages": "true",
    "snowflake.url.name": "XXX.snowflakecomputing.com",
    "snowflake.user.name": "YYY",
    "snowflake.private.key": "ZZZ",
    "snowflake.database.name": "KAFKA_EVENTS",
    "snowflake.schema.name": "PUBLIC",
    "buffer.count.records": "50000",
    "buffer.size.bytes": "20000000",
    "buffer.flush.time": "180"
}
```

I've verified that the database KAFKA_EVENTS has a schema named PUBLIC. Any help here?

**Comment by xiekevin** [comment]
I changed the owner of the DB to PUBLIC as well from SYSADMIN and that solved the issue. There is a new issue however which is:

```
java.lang.NoClassDefFoundError: Could not initialize class org.apache.avro.generic.GenericData
	at org.apache.avro.generic.GenericDatumReader.<init>(GenericDatumReader.java:57)
	at com.snowflake.kafka.connector.records.SnowflakeAvroConverter.parseAvroWithSchema(SnowflakeAvroConverter.java:128)
	at com.snowflake.kafka.connector.records.SnowflakeAvroConverter.toConnectData(SnowflakeAvroConverter.java:110)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.lambda$convertAndTransformRecord$1(WorkerSinkTask.java:487)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:128)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:162)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:104)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertAndTransformRecord(WorkerSinkTask.java:487)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:464)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:320)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by binglihub** [comment]
this issue fixed in 0.5.5.
please check out it from Maven
https://mvnrepository.com/artifact/com.snowflake/snowflake-kafka-connector

We also published it on Confluent Hub, but still need more time for website updating.

**Comment by xiekevin** [comment]
Hi @binglihub, I'm currently using v0.5.5 and see the error above

**Comment by binglihub** [comment]
@xiekevin I double checked the jar file on Maven, it already contains Avro lib. 
However, if you still have this issue, you can install avro lib by this command
```bash
confluent-hub install confluentinc/kafka-connect-avro-converter:5.3.1
```

**Comment by xiekevin** [comment]
OK it works now, sorry about that! Thank you!
