### ISSUE TITLE
errors.tolerance: String must be one of: none, all

### ISSUE THREAD

**Issue by hongbo-miao** [snowflakedb/snowflake-kafka-connector#821]
I am using snowflake-kafka-connector 2.2.1

I got error:

```shell
[Worker-0c2c38e8b0d20ac2e] [2024-04-15 05:37:38,280] ERROR [DevelopmentMySinkConnector|worker] Failed to start connector DevelopmentMySinkConnector (org.apache.kafka.connect.runtime.Worker:288)
[Worker-0c2c38e8b0d20ac2e] org.apache.kafka.common.config.ConfigException: Invalid value ALL for configuration errors.tolerance: String must be one of: none, all
[Worker-0c2c38e8b0d20ac2e] 	at org.apache.kafka.common.config.ConfigDef$ValidString.ensureValid(ConfigDef.java:942)
[Worker-0c2c38e8b0d20ac2e] 	at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:484)
[Worker-0c2c38e8b0d20ac2e] 	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:468)
[Worker-0c2c38e8b0d20ac2e] 	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:108)
[Worker-0c2c38e8b0d20ac2e] 	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:129)
[Worker-0c2c38e8b0d20ac2e] 	at org.apache.kafka.connect.runtime.ConnectorConfig.<init>(ConnectorConfig.java:231)
[Worker-0c2c38e8b0d20ac2e] 	at org.apache.kafka.connect.runtime.SinkConnectorConfig.<init>(SinkConnectorConfig.java:84)
[Worker-0c2c38e8b0d20ac2e] 	at org.apache.kafka.connect.runtime.Worker.startConnector(Worker.java:277)
[Worker-0c2c38e8b0d20ac2e] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startConnector(DistributedHerder.java:1370)
[Worker-0c2c38e8b0d20ac2e] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1400(DistributedHerder.java:130)
[Worker-0c2c38e8b0d20ac2e] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$8.call(DistributedHerder.java:1022)
[Worker-0c2c38e8b0d20ac2e] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$8.call(DistributedHerder.java:1008)
[Worker-0c2c38e8b0d20ac2e] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.tick(DistributedHerder.java:399)
[Worker-0c2c38e8b0d20ac2e] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:317)
[Worker-0c2c38e8b0d20ac2e] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[Worker-0c2c38e8b0d20ac2e] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[Worker-0c2c38e8b0d20ac2e] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[Worker-0c2c38e8b0d20ac2e] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[Worker-0c2c38e8b0d20ac2e] 	at java.base/java.lang.Thread.run(Thread.java:829)
[Worker-0c2c38e8b0d20ac2e] [2024-04-15 05:37:38,286] ERROR Uncaught exception in REST call to /connectors/DevelopmentMySinkConnector/restart 
```

It would be great to update [the document](https://docs.snowflake.com/en/user-guide/data-load-snowpipe-streaming-kafka#error-handling-and-dlq-properties) to lowercase, thanks! ☺️

![image](https://github.com/snowflakedb/snowflake-kafka-connector/assets/3375461/2a199ca3-280f-4a50-837c-3524eddae608)

**Comment by sfc-gh-gjachimko** [comment]
Thank you for your remark. We will look into that!

**Comment by sfc-gh-gjachimko** [comment]
I did check the code base - there is case insensitive comparison of the configuration values, so any lower/upper case letter combination of allowed values works fine in our test scenarios. Is there a chance you are using some specific locale settings in your environment? The only case where this could potentially fail is user provided value conversion to lowercase.

**Comment by hongbo-miao** [comment]
Hi @sfc-gh-gjachimko I passed in through Terraform at https://github.com/Hongbo-Miao/hongbomiao.com/blob/06a7796cf01a9cd56d177a3edb23e0986bd7857e/cloud-infrastructure/terraform/modules/aws/hm_amazon_msk_connector/main.tf#L56-L56

**Comment by sfc-gh-gjachimko** [comment]
@hongbo-miao i've double checked this at our side - it seems to be case insensitive - https://github.com/snowflakedb/snowflake-kafka-connector/blob/2b66a638924076858a6b1112c94027a56f590c18/src/test/java/com/snowflake/kafka/connector/ConnectorConfigTest.java 
can you confirm it is still an issue for you?

**Comment by hongbo-miao** [comment]
> @hongbo-miao i've double checked this at our side - it seems to be case insensitive - https://github.com/snowflakedb/snowflake-kafka-connector/blob/2b66a638924076858a6b1112c94027a56f590c18/src/test/java/com/snowflake/kafka/connector/ConnectorConfigTest.java can you confirm it is still an issue for you?

Thanks @sfc-gh-gjachimko ! The link you posted does not point to specific line. If you could locate specific line throw this 
error in my fist post, specific this one

> org.apache.kafka.common.config.ConfigException: Invalid value ALL for configuration errors.tolerance: String must be one of: none, all

> ERROR Uncaught exception in REST call to /connectors/DevelopmentMySinkConnector/restart 

it may help.

Terraform is case-sensitive.

**Comment by hongbo-miao** [comment]
I saw there is a new v2.2.2 connector published, I will give it a try and report back soon, thanks!

**Comment by hongbo-miao** [comment]
Hi @sfc-gh-gjachimko


This time, tested on latest MSK 3.7.x.
I can confirm the issue still exists on snowflake-kafka-connector v2.2.2, here is

<details>
  <summary>full log</summary>
  
  ```shell
[Worker-0dc0c6953e0bf5966] [2024-07-10 20:18:39,928] INFO [DevelopmentTrackerKafkaSinkConnector|worker] Stopping connector DevelopmentTrackerKafkaSinkConnector (org.apache.kafka.connect.runtime.Worker:387)
[Worker-0dc0c6953e0bf5966] [2024-07-10 20:18:39,929] WARN [DevelopmentTrackerKafkaSinkConnector|worker] Ignoring stop request for unowned connector DevelopmentTrackerKafkaSinkConnector (org.apache.kafka.connect.runtime.Worker:390)
[Worker-0dc0c6953e0bf5966] [2024-07-10 20:18:39,929] WARN [DevelopmentTrackerKafkaSinkConnector|worker] Ignoring await stop request for non-present connector DevelopmentTrackerKafkaSinkConnector (org.apache.kafka.connect.runtime.Worker:415)
[Worker-0dc0c6953e0bf5966] [2024-07-10 20:18:39,930] INFO [Worker clientId=connect-1, groupId=__amazon_msk_connect_cluster_DevelopmentTrackerKafkaSinkConnector_56e622b8-1b4f-4b2b-9416-4d3c691010fc-4] Starting connector DevelopmentTrackerKafkaSinkConnector (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1340)
[Worker-0dc0c6953e0bf5966] [2024-07-10 20:18:39,930] INFO [DevelopmentTrackerKafkaSinkConnector|worker] Creating connector DevelopmentTrackerKafkaSinkConnector of type com.snowflake.kafka.connector.SnowflakeSinkConnector (org.apache.kafka.connect.runtime.Worker:274)
[Worker-0dc0c6953e0bf5966] [2024-07-10 20:18:39,931] ERROR [DevelopmentTrackerKafkaSinkConnector|worker] Failed to start connector DevelopmentTrackerKafkaSinkConnector (org.apache.kafka.connect.runtime.Worker:288)
[Worker-0dc0c6953e0bf5966] org.apache.kafka.common.config.ConfigException: Invalid value ALL for configuration errors.tolerance: String must be one of: none, all
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.common.config.ConfigDef$ValidString.ensureValid(ConfigDef.java:942)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:484)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:468)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:108)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:129)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.ConnectorConfig.<init>(ConnectorConfig.java:231)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.SinkConnectorConfig.<init>(SinkConnectorConfig.java:84)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.Worker.startConnector(Worker.java:277)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startConnector(DistributedHerder.java:1370)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1400(DistributedHerder.java:130)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$8.call(DistributedHerder.java:1022)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$8.call(DistributedHerder.java:1008)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.tick(DistributedHerder.java:399)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:317)
[Worker-0dc0c6953e0bf5966] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[Worker-0dc0c6953e0bf5966] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[Worker-0dc0c6953e0bf5966] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[Worker-0dc0c6953e0bf5966] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[Worker-0dc0c6953e0bf5966] 	at java.base/java.lang.Thread.run(Thread.java:829)
[Worker-0dc0c6953e0bf5966] [2024-07-10 20:18:39,934] ERROR Uncaught exception in REST call to /connectors/DevelopmentTrackerKafkaSinkConnector/restart (org.apache.kafka.connect.runtime.rest.errors.ConnectExceptionMapper:61)
[Worker-0dc0c6953e0bf5966] org.apache.kafka.connect.errors.ConnectException: Failed to start connector: DevelopmentTrackerKafkaSinkConnector
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.lambda$startConnector$6(DistributedHerder.java:1346)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.Worker.startConnector(Worker.java:294)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startConnector(DistributedHerder.java:1370)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1400(DistributedHerder.java:130)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$8.call(DistributedHerder.java:1022)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$8.call(DistributedHerder.java:1008)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.tick(DistributedHerder.java:399)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:317)
[Worker-0dc0c6953e0bf5966] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[Worker-0dc0c6953e0bf5966] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[Worker-0dc0c6953e0bf5966] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[Worker-0dc0c6953e0bf5966] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[Worker-0dc0c6953e0bf5966] 	at java.base/java.lang.Thread.run(Thread.java:829)
[Worker-0dc0c6953e0bf5966] [2024-07-10 20:18:50,266] INFO [DevelopmentTrackerKafkaSinkConnector|worker] Stopping connector DevelopmentTrackerKafkaSinkConnector (org.apache.kafka.connect.runtime.Worker:387)
[Worker-0dc0c6953e0bf5966] [2024-07-10 20:18:50,266] WARN [DevelopmentTrackerKafkaSinkConnector|worker] Ignoring stop request for unowned connector DevelopmentTrackerKafkaSinkConnector (org.apache.kafka.connect.runtime.Worker:390)
[Worker-0dc0c6953e0bf5966] [2024-07-10 20:18:50,267] WARN [DevelopmentTrackerKafkaSinkConnector|worker] Ignoring await stop request for non-present connector DevelopmentTrackerKafkaSinkConnector (org.apache.kafka.connect.runtime.Worker:415)
[Worker-0dc0c6953e0bf5966] [2024-07-10 20:18:50,267] INFO [Worker clientId=connect-1, groupId=__amazon_msk_connect_cluster_DevelopmentTrackerKafkaSinkConnector_56e622b8-1b4f-4b2b-9416-4d3c691010fc-4] Starting connector DevelopmentTrackerKafkaSinkConnector (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1340)
[Worker-0dc0c6953e0bf5966] [2024-07-10 20:18:50,267] INFO [DevelopmentTrackerKafkaSinkConnector|worker] Creating connector DevelopmentTrackerKafkaSinkConnector of type com.snowflake.kafka.connector.SnowflakeSinkConnector (org.apache.kafka.connect.runtime.Worker:274)
[Worker-0dc0c6953e0bf5966] [2024-07-10 20:18:50,268] ERROR [DevelopmentTrackerKafkaSinkConnector|worker] Failed to start connector DevelopmentTrackerKafkaSinkConnector (org.apache.kafka.connect.runtime.Worker:288)
[Worker-0dc0c6953e0bf5966] org.apache.kafka.common.config.ConfigException: Invalid value ALL for configuration errors.tolerance: String must be one of: none, all
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.common.config.ConfigDef$ValidString.ensureValid(ConfigDef.java:942)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:484)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:468)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:108)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:129)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.ConnectorConfig.<init>(ConnectorConfig.java:231)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.SinkConnectorConfig.<init>(SinkConnectorConfig.java:84)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.Worker.startConnector(Worker.java:277)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startConnector(DistributedHerder.java:1370)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1400(DistributedHerder.java:130)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$8.call(DistributedHerder.java:1022)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$8.call(DistributedHerder.java:1008)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.tick(DistributedHerder.java:399)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:317)
[Worker-0dc0c6953e0bf5966] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[Worker-0dc0c6953e0bf5966] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[Worker-0dc0c6953e0bf5966] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[Worker-0dc0c6953e0bf5966] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[Worker-0dc0c6953e0bf5966] 	at java.base/java.lang.Thread.run(Thread.java:829)
[Worker-0dc0c6953e0bf5966] [2024-07-10 20:18:50,270] ERROR Uncaught exception in REST call to /connectors/DevelopmentTrackerKafkaSinkConnector/restart (org.apache.kafka.connect.runtime.rest.errors.ConnectExceptionMapper:61)
[Worker-0dc0c6953e0bf5966] org.apache.kafka.connect.errors.ConnectException: Failed to start connector: DevelopmentTrackerKafkaSinkConnector
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.lambda$startConnector$6(DistributedHerder.java:1346)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.Worker.startConnector(Worker.java:294)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startConnector(DistributedHerder.java:1370)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1400(DistributedHerder.java:130)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$8.call(DistributedHerder.java:1022)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$8.call(DistributedHerder.java:1008)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.tick(DistributedHerder.java:399)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:317)
[Worker-0dc0c6953e0bf5966] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[Worker-0dc0c6953e0bf5966] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[Worker-0dc0c6953e0bf5966] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[Worker-0dc0c6953e0bf5966] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[Worker-0dc0c6953e0bf5966] 	at java.base/java.lang.Thread.run(Thread.java:829)
[Worker-0dc0c6953e0bf5966] [2024-07-10 20:19:05,630] INFO [DevelopmentTrackerKafkaSinkConnector|worker] Stopping connector DevelopmentTrackerKafkaSinkConnector (org.apache.kafka.connect.runtime.Worker:387)
[Worker-0dc0c6953e0bf5966] [2024-07-10 20:19:05,630] WARN [DevelopmentTrackerKafkaSinkConnector|worker] Ignoring stop request for unowned connector DevelopmentTrackerKafkaSinkConnector (org.apache.kafka.connect.runtime.Worker:390)
[Worker-0dc0c6953e0bf5966] [2024-07-10 20:19:05,631] WARN [DevelopmentTrackerKafkaSinkConnector|worker] Ignoring await stop request for non-present connector DevelopmentTrackerKafkaSinkConnector (org.apache.kafka.connect.runtime.Worker:415)
[Worker-0dc0c6953e0bf5966] [2024-07-10 20:19:05,631] INFO [Worker clientId=connect-1, groupId=__amazon_msk_connect_cluster_DevelopmentTrackerKafkaSinkConnector_56e622b8-1b4f-4b2b-9416-4d3c691010fc-4] Starting connector DevelopmentTrackerKafkaSinkConnector (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1340)
[Worker-0dc0c6953e0bf5966] [2024-07-10 20:19:05,632] INFO [DevelopmentTrackerKafkaSinkConnector|worker] Creating connector DevelopmentTrackerKafkaSinkConnector of type com.snowflake.kafka.connector.SnowflakeSinkConnector (org.apache.kafka.connect.runtime.Worker:274)
[Worker-0dc0c6953e0bf5966] [2024-07-10 20:19:05,632] ERROR [DevelopmentTrackerKafkaSinkConnector|worker] Failed to start connector DevelopmentTrackerKafkaSinkConnector (org.apache.kafka.connect.runtime.Worker:288)
[Worker-0dc0c6953e0bf5966] org.apache.kafka.common.config.ConfigException: Invalid value ALL for configuration errors.tolerance: String must be one of: none, all
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.common.config.ConfigDef$ValidString.ensureValid(ConfigDef.java:942)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:484)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:468)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:108)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:129)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.ConnectorConfig.<init>(ConnectorConfig.java:231)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.SinkConnectorConfig.<init>(SinkConnectorConfig.java:84)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.Worker.startConnector(Worker.java:277)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startConnector(DistributedHerder.java:1370)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1400(DistributedHerder.java:130)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$8.call(DistributedHerder.java:1022)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$8.call(DistributedHerder.java:1008)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.tick(DistributedHerder.java:399)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:317)
[Worker-0dc0c6953e0bf5966] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[Worker-0dc0c6953e0bf5966] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[Worker-0dc0c6953e0bf5966] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[Worker-0dc0c6953e0bf5966] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[Worker-0dc0c6953e0bf5966] 	at java.base/java.lang.Thread.run(Thread.java:829)
[Worker-0dc0c6953e0bf5966] [2024-07-10 20:19:05,635] ERROR Uncaught exception in REST call to /connectors/DevelopmentTrackerKafkaSinkConnector/restart (org.apache.kafka.connect.runtime.rest.errors.ConnectExceptionMapper:61)
[Worker-0dc0c6953e0bf5966] org.apache.kafka.connect.errors.ConnectException: Failed to start connector: DevelopmentTrackerKafkaSinkConnector
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.lambda$startConnector$6(DistributedHerder.java:1346)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.Worker.startConnector(Worker.java:294)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startConnector(DistributedHerder.java:1370)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1400(DistributedHerder.java:130)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$8.call(DistributedHerder.java:1022)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$8.call(DistributedHerder.java:1008)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.tick(DistributedHerder.java:399)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:317)
[Worker-0dc0c6953e0bf5966] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[Worker-0dc0c6953e0bf5966] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[Worker-0dc0c6953e0bf5966] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[Worker-0dc0c6953e0bf5966] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[Worker-0dc0c6953e0bf5966] 	at java.base/java.lang.Thread.run(Thread.java:829)
[Worker-0dc0c6953e0bf5966] [2024-07-10 20:19:28,061] INFO [DevelopmentTrackerKafkaSinkConnector|worker] Stopping connector DevelopmentTrackerKafkaSinkConnector (org.apache.kafka.connect.runtime.Worker:387)
[Worker-0dc0c6953e0bf5966] [2024-07-10 20:19:28,061] WARN [DevelopmentTrackerKafkaSinkConnector|worker] Ignoring stop request for unowned connector DevelopmentTrackerKafkaSinkConnector (org.apache.kafka.connect.runtime.Worker:390)
[Worker-0dc0c6953e0bf5966] [2024-07-10 20:19:28,061] WARN [DevelopmentTrackerKafkaSinkConnector|worker] Ignoring await stop request for non-present connector DevelopmentTrackerKafkaSinkConnector (org.apache.kafka.connect.runtime.Worker:415)
[Worker-0dc0c6953e0bf5966] [2024-07-10 20:19:28,061] INFO [Worker clientId=connect-1, groupId=__amazon_msk_connect_cluster_DevelopmentTrackerKafkaSinkConnector_56e622b8-1b4f-4b2b-9416-4d3c691010fc-4] Starting connector DevelopmentTrackerKafkaSinkConnector (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1340)
[Worker-0dc0c6953e0bf5966] [2024-07-10 20:19:28,062] INFO [DevelopmentTrackerKafkaSinkConnector|worker] Creating connector DevelopmentTrackerKafkaSinkConnector of type com.snowflake.kafka.connector.SnowflakeSinkConnector (org.apache.kafka.connect.runtime.Worker:274)
[Worker-0dc0c6953e0bf5966] [2024-07-10 20:19:28,063] ERROR [DevelopmentTrackerKafkaSinkConnector|worker] Failed to start connector DevelopmentTrackerKafkaSinkConnector (org.apache.kafka.connect.runtime.Worker:288)
[Worker-0dc0c6953e0bf5966] org.apache.kafka.common.config.ConfigException: Invalid value ALL for configuration errors.tolerance: String must be one of: none, all
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.common.config.ConfigDef$ValidString.ensureValid(ConfigDef.java:942)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:484)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:468)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:108)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:129)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.ConnectorConfig.<init>(ConnectorConfig.java:231)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.SinkConnectorConfig.<init>(SinkConnectorConfig.java:84)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.Worker.startConnector(Worker.java:277)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startConnector(DistributedHerder.java:1370)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1400(DistributedHerder.java:130)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$8.call(DistributedHerder.java:1022)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$8.call(DistributedHerder.java:1008)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.tick(DistributedHerder.java:399)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:317)
[Worker-0dc0c6953e0bf5966] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[Worker-0dc0c6953e0bf5966] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[Worker-0dc0c6953e0bf5966] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[Worker-0dc0c6953e0bf5966] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[Worker-0dc0c6953e0bf5966] 	at java.base/java.lang.Thread.run(Thread.java:829)
[Worker-0dc0c6953e0bf5966] [2024-07-10 20:19:28,064] ERROR Uncaught exception in REST call to /connectors/DevelopmentTrackerKafkaSinkConnector/restart (org.apache.kafka.connect.runtime.rest.errors.ConnectExceptionMapper:61)
[Worker-0dc0c6953e0bf5966] org.apache.kafka.connect.errors.ConnectException: Failed to start connector: DevelopmentTrackerKafkaSinkConnector
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.lambda$startConnector$6(DistributedHerder.java:1346)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.Worker.startConnector(Worker.java:294)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startConnector(DistributedHerder.java:1370)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1400(DistributedHerder.java:130)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$8.call(DistributedHerder.java:1022)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$8.call(DistributedHerder.java:1008)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.tick(DistributedHerder.java:399)
[Worker-0dc0c6953e0bf5966] 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:317)
[Worker-0dc0c6953e0bf5966] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[Worker-0dc0c6953e0bf5966] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[Worker-0dc0c6953e0bf5966] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[Worker-0dc0c6953e0bf5966] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[Worker-0dc0c6953e0bf5966] 	at java.base/java.lang.Thread.run(Thread.java:829)
  ```
</details>
