### ISSUE TITLE
java.lang.NoSuchMethodError: 'org.codehaus.jackson.JsonNode org.apache.avro.Schema$Field.defaultValue()'

### ISSUE THREAD

**Issue by jfinzel** [snowflakedb/snowflake-kafka-connector#88]
I am using the Snowflake sink connector with Avro serialization.  When registering the connector, the user is successfully connecting to Snowflake however I am then hitting the following error at the bottom of this log:
```
2020-01-08 16:29:38,614 INFO   ||
[SF_KAFKA_CONNECTOR] pipe: SNOWFLAKE_KAFKA_CONNECTOR_snowflake_test_PIPE_customers_0 - service started   [com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1]
2020-01-08 16:29:38,616 INFO   ||
[SF_KAFKA_CONNECTOR] create new task in com.snowflake.kafka.connector.internal.SnowflakeSinkService - table: customers, topic: foo_debezium.debezium.customers, partition: 0   [com.snowflake.kafka.connector.internal.SnowflakeSinkServiceFactory$SnowflakeSinkServiceBuilder]
2020-01-08 16:29:38,618 INFO   ||
[SF_KAFKA_CONNECTOR] com.snowflake.kafka.connector.internal.SnowflakeSinkService created   [com.snowflake.kafka.connector.internal.SnowflakeSinkServiceFactory$SnowflakeSinkServiceBuilder]
2020-01-08 16:29:38,881 INFO   ||
[SF_KAFKA_CONNECTOR] SnowflakeSinkTask:close   [com.snowflake.kafka.connector.SnowflakeSinkTask]
2020-01-08 16:29:38,883 INFO   ||
[SF_KAFKA_CONNECTOR] pipe SNOWFLAKE_KAFKA_CONNECTOR_snowflake_test_PIPE_customers_0: cleaner terminated   [com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1]
2020-01-08 16:29:38,884 INFO   ||
[SF_KAFKA_CONNECTOR] pipe SNOWFLAKE_KAFKA_CONNECTOR_snowflake_test_PIPE_customers_0: flusher terminated   [com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1]
2020-01-08 16:29:38,885 INFO   ||
[SF_KAFKA_CONNECTOR] IngestService Closed   [com.snowflake.kafka.connector.internal.SnowflakeIngestionServiceV1]
2020-01-08 16:29:38,971 INFO   ||
[SF_KAFKA_CONNECTOR] pipe SNOWFLAKE_KAFKA_CONNECTOR_snowflake_test_PIPE_customers_0: service closed   [com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1]
2020-01-08 16:29:38,972 ERROR  ||  WorkerSinkTask{id=snowflake_test-0} Task threw an uncaught and unrecoverable exception   [org.apache.kafka.connect.runtime.WorkerTask]
java.lang.NoSuchMethodError: 'org.codehaus.jackson.JsonNode org.apache.avro.Schema$Field.defaultValue()'
        at io.confluent.connect.avro.AvroData.toConnectSchema(AvroData.java:1652)
        at io.confluent.connect.avro.AvroData.toConnectSchema(AvroData.java:1511)
        at io.confluent.connect.avro.AvroData.toConnectData(AvroData.java:1220)
        at io.confluent.connect.avro.AvroConverter.toConnectData(AvroConverter.java:100)
        at org.apache.kafka.connect.storage.Converter.toConnectData(Converter.java:86)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.lambda$convertAndTransformRecord$1(WorkerSinkTask.java:485)
        at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:128)
        at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:162)
        at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:104)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.convertAndTransformRecord(WorkerSinkTask.java:485)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:465)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:321)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
2020-01-08 16:29:38,973 ERROR  ||  WorkerSinkTask{id=snowflake_test-0} Task is being killed and will not recover until manually restarted   [org.apache.kafka.connect.runtime.WorkerTask]
```

Here is my config file:
```json
{
    "name": "snowflake_test",
    "config": {
        "connector.class": "com.snowflake.kafka.connector.SnowflakeSinkConnector",
        "topics": "foo_debezium.debezium.customers",
	"snowflake.topic2table.map": "foo_debezium.debezium.customers:customers",
	"snowflake.url.name": "https://foo.snowflakecomputing.com:443",
	"snowflake.user.name": "debezium",
	"snowflake.private.key": "....",
	"snowflake.private.key.passphrase": "....",
        "snowflake.database.name": "debezium_dev",
        "snowflake.schema.name": "debezium",
        "key.converter": "io.confluent.connect.avro.AvroConverter",
        "value.converter": "com.snowflake.kafka.connector.records.SnowflakeAvroConverter",
	"key.converter.schema.registry.url": "http://schema-registry:8081",
        "value.converter.schema.registry.url": "http://schema-registry:8081"
    }
}
```

Some more details about how to reproduce:
I am running Debezium Postgres Source -> Snowflake Sink using docker.  Here is my docker-compose:
```
version: '2'
services:
  zookeeper:
    image: debezium/zookeeper:${DEBEZIUM_VERSION}
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
  kafka:
    image: debezium/kafka:${DEBEZIUM_VERSION}
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
  schema-registry:
    image: confluentinc/cp-schema-registry
    ports:
     - 8181:8181
     - 8081:8081
    environment:
     - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=zookeeper:2181
     - SCHEMA_REGISTRY_HOST_NAME=schema-registry
     - SCHEMA_REGISTRY_LISTENERS=http://schema-registry:8081
    links:
     - zookeeper
  connect:
    image: debezium/connect:${DEBEZIUM_VERSION}
    ports:
     - 8083:8083
    links:
     - kafka
     - schema-registry
    volumes:
     - $PWD/connect-plugins:/kafka/connect
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses
```

My $PWD/connect-plugin directory:
```
$ ls -1 connect-plugins/
debezium-connectors
snowflakeinc-snowflake-kafka-connector-1.0.0
$ ls -1 connect-plugins/debezium-connectors/
debezium-connector-postgres-1.0.0.Final.jar
debezium-core-1.0.0.Final.jar
postgresql-42.2.9.jar
protobuf-java-3.8.0.jar
$ ls -1 connect-plugins/snowflakeinc-snowflake-kafka-connector-1.0.0/
assets
doc
lib
manifest.json
```

Reproduce:
```
# Containers up
$ docker-compose -f my-docker-compose.yaml up

# Register Snowflake Connector
$ curl -X POST -H "Content-Type: application/json" --data @register-sf.json http://localhost:8083/connectors
# Everything works fine here, but there is still no Avro data in Kafka

# Now add the Debezium Postgres connector - this starts populating data in Kafka in Avro format
$ curl -i -X POST -H "Accept:application/json" -H  "Content-Type:application/json" http://localhost:8083/connectors/ -d @register-postgres-on-prem-avro.json

# There is schema registry data
$ curl -X GET http://localhost:8081/subjects/
["__debezium-heartbeat.foo_debezium-value","foo_debezium.debezium.customers-value","__debezium-heartbeat.foo_debezium-key","foo_debezium.debezium.dummy_data-key","foo_debezium.debezium.customers-key","foo_debezium.debezium.dummy_data-value"]
```

Any insight much appreciated!

**Comment by jfinzel** [comment]
A documentation fix should be forthcoming, because this was fixed by changing a config parameter that docs claim is "not used" by the connector:

https://docs.snowflake.net/manuals/user-guide/kafka-connector-install.html#configuring-the-kafka-connector
> `key.converter`
> This is the Kafka record’s key converter (e.g. "org.apache.kafka.connect.storage.StringConverter"). This is not used by the Kafka connector, but is required by the Kafka Connect Platform.

The problem above was solved by changing the above value to:
```
"key.converter": "com.snowflake.kafka.connector.records.SnowflakeAvroConverter"
```

Docs should indicate that `key.converter` actually matters.
