### ISSUE TITLE
Avro dependencies should be provided by runtime

### ISSUE THREAD

**Issue by seruman** [snowflakedb/snowflake-kafka-connector#99]
Version 1.1.0 has `org.apache.avro 19.0` and `io.confluent.kafka-connect-avro-converter 5.3.0`(which has `org.apache.avro 1.8.1` as compile time dependency) as compile time dependencies. [Installation Prerequisites](https://docs.snowflake.net/manuals/user-guide/kafka-connector-install.html#installation-prerequisites) document says that you can use Avro 1.8.2+ and Kafka Connect Avro Connector 5.0.0+.

Since Avro version 1.9.0 comes with the artifact it overrides Avro dependency in the runtime. Due to API changes on version 1.9.0 this causes other issues for other connectors that using it.

In our case, we have Avro version 1.8.2 and Kafka Avro Converter version 5.1.2 in our Kafka Connect deployment. While running with Snowflake Kafka Connector, Debezium connector throws following;

```
java.lang.NoSuchMethodError: 'void org.apache.avro.Schema.addProp(java.lang.String, org.codehaus.jackson.JsonNode)'
	at io.confluent.connect.avro.AvroData.fromConnectSchema(AvroData.java:916)
	at io.confluent.connect.avro.AvroData.addAvroRecordField(AvroData.java:1059)
	at io.confluent.connect.avro.AvroData.fromConnectSchema(AvroData.java:900)
	at io.confluent.connect.avro.AvroData.addAvroRecordField(AvroData.java:1059)
	at io.confluent.connect.avro.AvroData.fromConnectSchema(AvroData.java:900)
	at io.confluent.connect.avro.AvroData.fromConnectSchema(AvroData.java:732)
	at io.confluent.connect.avro.AvroData.fromConnectSchema(AvroData.java:726)
	at io.confluent.connect.avro.AvroData.fromConnectData(AvroData.java:365)
	at io.confluent.connect.avro.AvroConverter.fromConnectData(AvroConverter.java:80)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.lambda$convertTransformedRecord$2(WorkerSourceTask.java:270)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:128)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:162)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:104)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.convertTransformedRecord(WorkerSourceTask.java:270)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.sendRecords(WorkerSourceTask.java:294)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:229)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

``` 

Avro converter is optional, due to that I think both Avro and Kafka Avro Converter should be provided by runtime.

**Comment by seruman** [comment]
https://docs.confluent.io/current/connect/userguide.html#installing-plugins
> A Kafka Connect plugin is:
>
>an uber JAR containing all of the classfiles for the plugin and its third-party dependencies in a single JAR file; or
>a directory on the file system that contains the JAR files for the plugin and its third-party dependencies.

> Now, when we start our Kafka Connect workers with that configuration, Kafka Connect will discover all connectors, transforms, and/or converters defined within those plugins. When we use a connector, transform, or converter, the Kafka Connect worker loads the classes from the respective plugin first, followed by the Kafka Connect runtime and Java libraries. Kafka Connect explicitly avoids all of the libraries in other plugins and prevents conflicts, making it very easy to use connectors and transforms developed independently by different providers.

This happens when using `CLASSPATH` based plugin installation. Does not cause any problem with `plugin.path` mechanism.

Feel free to close it.

**Comment by binglihub** [comment]
@seruman thank you for your comment.

**Comment by danksim** [comment]
was this solved by setting `plugin.path` to `/opt/kafka/plugins`? @seruman
